### ISSUE TITLE
[Bug] Documentation: yarn add pkg@<git repo> syntax missing from CLI / website

### ISSUE THREAD

**Issue by rlue** [yarnpkg/berry#1085]
- [x] I'd be willing to implement a fix

**Describe the bug**

`yarn add` supports adding git repos as dependencies (as opposed to registered npm packages). I'm not 100% certain of what's supported, but it seems that yarn's syntax differs from npm's:

```sh
# npm
$ npm install https://github.com/indexzero/forever

# yarn
$ yarn add forever@https://github.com/indexzero/forever
```

It would be really nice to have CLI help documentation that covers this. I'd be willing to prepare a PR it, but since I don't know what's possible and what's not, I wouldn't exactly say that I'm qualified.

**Comment by paul-soporan** [comment]
### Short answer:

The valid syntaxes for adding a github repo are:
* `yarn add forever@https://github.com/indexzero/forever`
* `yarn add forever@indexzero/forever`
* `yarn add forever@github:indexzero/forever`

You can also append `.git`.

For a specific branch, append `#branch`.

I'll add these examples to the documentation.

### Long Answer:

Yarn installs packages in 4 different steps (see https://yarnpkg.com/advanced/architecture#install-architecture): Resolution, Fetch, Link, Build.
At the Resolution step, Yarn resolves your dependencies using `Resolver`s.
Every dependency you provide is parsed as a [`Descriptor`](https://yarnpkg.com/advanced/lexicon#descriptor). A `Descriptor` represents a combination of a package scope, a package name, and a package range.
`yarn add https://github.com/indexzero/forever` doesn't work because `https://github.com/indexzero/forever` is a range, not a `Descriptor`. A valid `Descriptor` would be `forever@https://github.com/indexzero/forever`.

Each descriptor is tested to see which Resolver supports it.
The `GitResolver` tests if the range of the `Descriptor` matches one of [these patterns](https://github.com/yarnpkg/berry/blob/ab2e84588b1eacb2ec60a751f12b168415224a19/packages/plugin-git/sources/gitUtils.ts#L13).

Patterns (optional parts put inside paranthesis):
* The first pattern tests if the range matches the pattern `git(+ssh):`
* The second pattern tests if the range matches the pattern `(git+)protocol:owner/repo.git(#branch)`
* The third pattern tests if the range matches the pattern `git@owner/repo.git(#branch)`
* The fourth pattern tests if the range matches the pattern `(github: OR https://github.com/)owner/repo(.git)(#branch)`

Also, see the [Github Protocol](https://yarnpkg.com/features/protocols).

**Comment by rlue** [comment]
> Also, see the [Github Protocol](https://yarnpkg.com/features/protocols).

Wow yes, this is exactly what I was looking for (and also thanks for your very detailed and instructive write-up).
