### ISSUE TITLE
[Bug] Azure OSX tests are broken

### ISSUE THREAD

**Issue by arcanis** [yarnpkg/berry#109]
**Describe the bug**

It seems like the agents don't boot anymore. We didn't change anything as far as I know 🤔

Would you have an idea of who we could speak with to figure out the problem, @kaylangan?

**To Reproduce**

Open a PR against master.

**Screenshots**

https://dev.azure.com/yarnpkg/berry/_build/results?buildId=944

![image](https://user-images.githubusercontent.com/1037931/56994215-bb20bb00-6b9e-11e9-81ba-c142a7b5b275.png)

**Environment if relevant (please complete the following information):**

 - OS: OSX w/ Azure

**Comment by kaylangan** [comment]
@arcanis thanks for your patience. The issue should be mitigated. We had an outage in our West Europe region. The incident was mitigated around 8/8:30 AM EST. You can find more info here: https://status.dev.azure.com/_event/117874362 (note, it says the issue was "build delays" but it actually caused build failures).

**Comment by arcanis** [comment]
Sounds good, thanks Kayla!
