### ISSUE TITLE
react-dnd console error moving from rc.29 to rc.30

### ISSUE THREAD

**Issue by dalinarkholin** [yarnpkg/berry#1113]
When moving from 2.0.0-rc.29 to 2.0.0-rc.30 we got an error with react-dnd 9.3.4.

Nothing outside of the version of yarn was changed.

Follow the steps in the README.md [here](https://github.com/dalinarkholin/yarn-v2-rc-30-repro) to reproduce the issue.

If you need anything else let me know!

**Comment by arcanis** [comment]
I'm not entirely sure why the upgrade broke, but there's a semantical change you should do that happens to fix the problem: in shared, mark `react-dnd` as a peer dependency (you probably should do it on `react` and `react-dom` as well).

This is the only sound way to ensure that project and shared will use the exact same instance of `react-dnd` (otherwise, there's a risk that they are different instances, which will break the React contexts as they are kinds of singletons).

**Comment by dalinarkholin** [comment]
@arcanis can confirm that was the issue. Thanks for the enlightenment around dependency behavior.
