### ISSUE TITLE
[Feature] disable lockfile

### ISSUE THREAD

**Issue by marechal-p** [yarnpkg/berry#1175]
- [ ] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

When developing libraries, having a lock file can prevent the detection of issues with newer packages, that ultimately will be pulled by dependents.

But maybe still locking dev-dependencies can be useful. This would be up to the developer?

**Describe the solution you'd like**

In a perfect world, we should be able to choose what dependencies to lock: `all`, `dev`, `none`.

- `all` would primarily be used by applications (no dependents).
- `dev` and `none` could be used for libraries (that have dependents).

It can be a field in `.yarnrc.yml`, maybe `lock: (all|dev|none)` ?

Berry should be able to replace already installed dependencies by a new one if available (and not locked) when doing `yarn install`. It can be annoying to delete the whole `node_modules` folder every time. Edit: ~~or should a dev use `yarn upgrade` in this case?~~ it would upgrade dev dependencies as well, which we might not want.

**Describe the drawbacks of your solution**

Maybe slower installs? I can live with that as long as it does what I want. Only impacts people disabling the lockfile.

**Describe alternatives you've considered**

Running `yarn upgrade` often. But this pollutes the commit history in some way, and might lead to merge conflicts on the lockfile. Even though old yarn was able to resolve those conflicts, it is still annoying to land in that state.

**Additional context**

N/A

**Comment by arcanis** [comment]
This isn't something we'll implement. More details [here](https://yarnpkg.com/advanced/qa#should-lockfiles-be-committed-to-the-repository).

**Comment by marechal-p** [comment]
So the alternative for an active project would be to regularly manually run `yarn upgrade` and push it upstream every so often?

**Comment by arcanis** [comment]
Yep. To make that easier, various bots exist that automatically run upgrades periodically and open PRs to run the tests against the new set of dependencies (Renovate / Dependabot).

**Comment by elgs** [comment]
I tend to get whatever latest and resolve issue if there is any. If they don't want to implement it, whenever I saw that file, I do:
```
rm -rf yarn.lock 
```

**Comment by JounQin** [comment]
We have `yarn --no-lockfile`, why we can't config it via `.yarnrc`? It is not constant. And for some libraries, they'd prefer always keeping latest compatible version.

See https://github.com/eslint/eslint-plugin-markdown/pull/182#discussion_r602799343

**Comment by merceyz** [comment]
See https://yarnpkg.com/getting-started/qa/#should-lockfiles-be-committed-to-the-repository

**Comment by JounQin** [comment]
> See https://yarnpkg.com/getting-started/qa/#should-lockfiles-be-committed-to-the-repository

I've already read it several times. And why `yarn --no-lockfile` is provided then?

**Comment by arcanis** [comment]
All softwares require baselines, and this is part of ours. There are workarounds if you really want to ignore our advices, there's no reason for us to change anything.

**Comment by elgs** [comment]
This is hindering many software from upgrading their dependencies to the latest, and is overkill for most software projects. To me, the lockfile is a monkey patch of npm, and many others followed. I started moving my nodejs projects to deno, and I found deno is a lot saner.

**Comment by RoyTinker** [comment]
I think this ExpressJS maintainer's comment sums it up pretty well:

> Since `npm` ignores a `package-lock.json` file that is in a package, adding one here will have no effect on consumers and will make the CI no longer represent the dependencies a consumer would get by running `npm install express`.

Source: https://github.com/expressjs/express/issues/3963#issuecomment-493460138

I know Yarn strongly argues in favor of committing lockfiles to libraries, but for most cases I *don't* think lock files should be committed to library repos. I'd probably carve out an exception for sparsely-maintained libraries, like long-lived npm utility packages that aren't under active development, but for libraries in active development I think it's a mistake to commit lock files to repos.

Library *consumers* always get the latest dependency tree when they run `npm install example-library`, regardless of whether a lock file is present. If that's a potential problem, there are 2 ways to mitigate it: version limiting and CI testing. I think the best approach is a combination of both:
1. pin a specific version for low-trust dependencies
2. allow automatic point/security updates for higher-trust dependencies using the `~` operator
3. run regular CI tests on fresh installs of the library

If we do 1-3 above for the sake of library consumers, I don't see much reason to use a lock file:
- it could only benefit *new* maintainers who are running `npm install` or `yarn install` for the first time
- all library maintainers should be cycling out and refreshing dependencies periodically anyway as they do their work
- the chance of 1-3 above *not* catching an issue is low. Note that the CI system will be exercising `devDependencies` as well as `dependencies`.

---

In principle, a library lock file *codifies* a bifurcation of functionality between consumers and maintainers of the library -- which is an effect I believe ought to be avoided as much as possible.

If there were a way to restrict lock files on a library to its `devDependencies` only, I'd likely advocate for using that, to add further stability to the developer experience and CI tooling. But since there isn't such a way, I don't think a lock file is worth the consumer/maintainer bifurcation it creates on `dependencies`.
