### ISSUE TITLE
[Bug] Error: typescript [...] Cannot apply hunk #7 

### ISSUE THREAD

**Issue by Luxcium** [yarnpkg/berry#1188]
how can I install  typescript@3.9.0-dev.20200324 ? 

I receive an error message:`YN0001: │ Error: typescript@patch:typescript@npm%3A3.9.0-
dev.20200324#builtin<compat/typescript>::version=3.9.0-dev.20200324&hash=270b6c: Cannot apply hunk #7`

I am using  `yarn add typescript@3.9.0-dev.20200324` and I dont know the implications of  ` yarn pnpify --sdk` etc.

I am using: ` yarn -v > 2.0.0-rc.31`

```
Version: 1.44.0
Commit: 2aae1f26c72891c399f860409176fe435a154b13
Date: 2020-04-08T08:23:56.137Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0
```

**Comment by merceyz** [comment]
Support for ts 3.9 was added in #1154, but it hasn't been released yet. You can try updating to master by running `yarn set version from sources` and see if that works.

**Comment by paul-soporan** [comment]
I can reproduce this issue for `typescript@3.9.0-dev.20200324`, but now that `typescript@3.9.3` and all the stable 3.9 versions are released and our patch works with them ([Playground Link](https://yarnpkg.com/playground?code=Y29uc3QgaW5zdGFsbFByb21pc2UgPSBwYWNrYWdlSnNvbkFuZEluc3RhbGwoew0KICBkZXBlbmRlbmNpZXM6IHsNCiAgICBbYHR5cGVzY3JpcHRgXTogYH4zLjlgLA0KICB9LA0KfSk7DQoNCmF3YWl0IGV4cGVjdChpbnN0YWxsUHJvbWlzZSkNCiAgLnJlc29sdmVzLnRvQmVUcnV0aHkoKTsNCg%3D%3D)), I'm going to close this issue, as it doesn't make sense for us to try to support a long forgotten 3.9 dev TS version, when we already support all the stable versions of TS 3.9. That's why I'm going to close this issue.
