### ISSUE TITLE
[Case Study] Yarn removes node_modules

### ISSUE THREAD

**Issue by zdm** [yarnpkg/berry#1273]
Hi.
I found, that yarn removes `node_modules` completely on `yarn install`.
I am using cordova, that installs platforms and plugins into the node_modules, so remove this directory - is not quite correct behavior.
Is it possible do do not touch it? Some option in config?

**Comment by arcanis** [comment]
No, that's expected. Leaving the node_modules could cause dangerous resolutions with various tools that would incorrectly load files from there instead of the PnP map.

The only exception, precisely for caching purposes, are dot-folders. So if you can configure cordova to store its artifacts into `node_modules/.cache/cordova`, it's the way to go.

**Comment by merceyz** [comment]
Cordova runs npm commands to do anything so you'll have a hard time with yarn (1 and 2) anyways. I have a plugin for yarn that fixes this that I made for work, i'll see if I can get it into berry. 

Due to how cordova works it will only work with `nodeLinker: node-modules` or `pnpMode: loose` and `pnpFallbackMode: all`
