### ISSUE TITLE
[Bug] An unexpected error occurred: "Invalid value type 2:0 in [root]/berry/.yarnrc".

### ISSUE THREAD

**Issue by tiansijie** [yarnpkg/berry#128]
**Describe the bug**

When I run `yarn build:cli`, I am getting this error `An unexpected error occurred: "Invalid value type 2:0 in [root]/berry/.yarnrc".`

I don't get this error if I check out earlier commits in this repo.

**To Reproduce**

Run `yarn build:cli` on your berry directory.

**Environment if relevant (please complete the following information):**

 - OS: OSX
 - Node version: 8.9.2
 - Yarn version: v1.15.2

**Comment by arcanis** [comment]
Thanks for the report! I've updated the local bundle, it should be fixed 👍

**Comment by arcanis** [comment]
Ah! I just got that the problem was different from what I originally assumed: since we know use a yaml-like syntax for our yarnrc files, you need to have Yarn 1.16+ in your global PATH to parse them properly.

The 1.16 is currently an rc release; check the [install instructions](https://yarnpkg.com/en/docs/install) to see various ways to install it (I'll move it to stable this week-end).

**Comment by juanpicado** [comment]
Furthermore, if the initial installation was done with `homebrew` on Mac.

```
➜ brew uninstall yarn
Uninstalling /usr/local/Cellar/yarn/1.13.0... (14 files, 4.7MB)
```

Then all works fine using the recommended above.

**Comment by bradleyayers** [comment]
I just hit this as well because I was using Yarn 1.13, I'll upgrade to 1.16 but it might be worth adding something to the README.

**Comment by syd192** [comment]
升级yarn，就解决了
which yarn可以查找yarn的安装位置
