### ISSUE TITLE
[Feature] why not keep npm name "yarn" for yarn1, and use "ya" for yarn2(berry)

### ISSUE THREAD

**Issue by 3cp** [yarnpkg/berry#1326]
Instead of breaking user apps with yarn v2. Why not pick a new name "ya"?

You can acquire the npm name "ya" from this dead project https://www.npmjs.com/package/ya

https://www.npmjs.com/policies/disputes

**Comment by paul-soporan** [comment]
Yarn 2 is Yarn, and it will stay Yarn in the future.

> Instead of breaking user apps with yarn v2.

Yarn 2 isn't breaking any user apps.

1) The global binary is locked on Yarn Classic (including the `latest` tag on npm), which means that you can't accidentally install Yarn 2 instead of Yarn 1. Yarn 2 has to be explicitly installed using `yarn set version berry` and I don't see how you could ever type that by accident.
2) We offer 3 migration paths: PnP `strict` mode (the default), the `node-modules` plugin, and PnP `loose` mode, which is a hybrid between the other 2. We can almost guarantee (and by almost I mean that if something is behaving differently, it's probably a bug either in Yarn Classic or in the `node-modules` plugin) that **any** existing project using Yarn Classic can be migrated to Yarn 2 using the `node-modules` plugin, without needing to do anything other (excluding the fact that some commands are a bit different/missing) than creating a `.yarnrc.yml` and adding the line `node-linker: node-modules`.

More details can be found in this thread: #766.

And to quote @arcanis from that thread:

> ### Should this be named differently?
> This is Yarn, it will stay Yarn. More than an implementation, we see this project as a focus. Yarn was first released focused on providing a “fast, reliable, and secure“ package manager, and this is the foundation upon which we will keep building.

**Comment by 3cp** [comment]
Thanks for the detailed explanation!
