### ISSUE TITLE
[Question] - How can I use Yarn 2 with husky and commitlint?

### ISSUE THREAD

**Issue by IT-CASADO** [yarnpkg/berry#1373]
Hi,

I'm trying to use Yarn 2 in conjunction with husky & commitlint.

It's easy to configure with version 1 of Yarn.

See here for a [working repro](https://github.com/IT-CASADO/yarn-husky-commitlint/commits/master).

But if I try to migrate to version 2 of Yarn i always get this error:

...
husky > commit-msg (node v12.16.3)
**sh: commitlint: command not found**
husky > commit-msg hook failed (add --no-verify to bypass)
...

[See here for code with version 2 of Yarn](https://github.com/IT-CASADO/yarn-husky-commitlint/commits/yarn-v2)

I also give **nodeLinker: node-modules** a try, but get the same error.

What have i to do to get it working?

Steps to reproduce my issue:

1. clone above linked git repository
2. make some modifications in both branches master and yarn-v2 (e.g.: adding new file)
3. commit changes with a commitlint message (e.g.: chore: testing yarn 2)

In version 1 you can commit, but not with version 2.
My used environment is Windows!

Regards
Daniel

**Comment by merceyz** [comment]
You need to prefix your command with `yarn`, so change your scripts to `yarn commitlint -E HUSKY_GIT_PARAMS`

**Comment by IT-CASADO** [comment]
> As a workaround you can prefix your command with `yarn`, I.e. change your script to `yarn commitlint -E HUSKY_GIT_PARAMS`

This is working for me, thanks a lot.
Is this only a workaround or an official solution?

Is the reason that this doesn't work with out prefixed with yarn, that commitlint isn't supporting PnP?

**Comment by arcanis** [comment]
Works for me; are you on Windows?

![image](https://user-images.githubusercontent.com/1037931/82434984-f0db5f00-9a93-11ea-81b8-31b6ab8cea30.png)

**Comment by IT-CASADO** [comment]
Yes I'm on Windows?

**Comment by bgotink** [comment]
I can reproduce this on windows, not on WSL or macOS

**Comment by bgotink** [comment]
Okay, I've looked into this a bit more. I'm by no means an experienced Windows user, so feel free to correct me if I'm wrong.

Short explanation for the cause: It appears that processes spawned within git BASH on Windows don't resolve `*.cmd` executables on the PATH.

Longer explanation:

I've tried to create the following script in package.json:

```json
"scripts": {
  "test": "husky-run commit-msg whatever"
}
```

This fails with the same error message when running `yarn test` via git BASH, but fails with only the two lines logged by husky in its output when run via PowerShell (which can't find the `sh` executable on the PATH).
In other words: husky-run only works when run via BASH on windows, and that's probably fine because if you're running husky-run, you're running it via a git hook, which are run via git's BASH shell.

Changing the commit-msg hook into `which yarn && which run && which commit-lint` gives the following piece of the puzzle:

```
husky > commit-msg (node v14.3.0)
/c/Program Files (x86)/Yarn/bin/yarn
which: no run in <entire $PATH>
husky > commit-msg hook failed (add --no-verify to bypass)
```

So what's happening: git BASH on Windows doesn't resolve `.cmd` files yarn has put on the PATH.

So the fix appears to be easy: remove the `else` keyword in the following code block: 

https://github.com/yarnpkg/berry/blob/5003627b14d9ee082e63d6aa757f3b14e13dff77/packages/yarnpkg-core/sources/scriptUtils.ts#L27-L34

If I remove the `else`, i.e. always run the content of the current `else` block, it works fine.
