### ISSUE TITLE
[Bug] yarn up upgrade to latest tagged

### ISSUE THREAD

**Issue by ChiefORZ** [yarnpkg/berry#1419]
- [ ] I'd be willing to implement a fix

**Describe the bug**

As already described in the issue #1414, `yarn up foo@canary` will not upgrade to the latest package tagged with the **canary** tag.

Like @arcanis mentioned:
> running `yarn up foo@canary` will literally set the range of your dependencies to canary. Since canary is already in the lockfile, it won't get re-locked. I think that should be considered as a bug 🤔

**To Reproduce**

```json
# package.json
{
  "dependencies": {
    "foo": "canary"
  }
}
````

```bash
yarn up foo@canary
```

**Comment by zmoshansky** [comment]
We have an internal library that is "versioned" by its git SHA1. This works great for us as the yarn.lock of the various consuming projects ensures this resolves to the same version. We save work not having to do version management around our library (Otherwise we'd just have a build bot literally increment version every build).

This did work in yarn 1.x.

To emulate the behaviour in yarn 2.x, I've been deleting the module and it's resolution in yarn.lock and running `yarn install` to re-pull the latest. This feels a bit clunkier but running `yarn up` gives:

```
BR0027: some_library@git+ssh://git@git-website.org/some_library.git can't be resolved to a satisfying range
```
