### ISSUE TITLE
[Bug] Cannot link 2 patches with each other

### ISSUE THREAD

**Issue by alubbe** [yarnpkg/berry#1547]
Everything here is reproducible by cloning https://github.com/alubbe/patch-depends-on-patch and running `yarn install`

**Describe the bug**

I need to patch 2 dependencies that depend on each other. So I added this to the package.json:
```json
  "dependencies": {
    "react-d3-core": "patch:react-d3-core@^1.3.9#./patches/react-d3-core",
    "react-d3-shape": "patch:react-d3-shape@^0.3.25#./patches/react-d3-shape"
  }
```
I need the patched `react-d3-shape` to use the patched `react-d3-core` dependency. With just the above, the patched `react-d3-shape` will use the public `react-d3-core` instead. So I tried setting this in `.yarnrc.yml`:
```yml
yarnPath: ".yarn/releases/yarn-berry.js"

packageExtensions:
  "react-d3-shape@^0.3.25":
    dependencies:
      "react-d3-core": "patch:react-d3-core@^1.3.9#./patches/react-d3-core"
```
But that throws the following error when running `yarn install`:

```
➤ YN0000: ┌ Resolution step
➤ YN0013: │ react-d3-shape@npm:0.3.25 can't be found in the cache and will be fetched from the remote registry
➤ YN0001: │ Error: react-d3-core@patch:react-d3-core@^1.3.9#./patches/react-d3-core::locator=react-d3-shape%40npm%3A0.3.25: ENOENT: no such file or directory, open './patches/react-d3-core'
    at n (/patch-depends-on-patch/.yarn/releases/yarn-berry.js:31:45807)
    at Object.A (/patch-depends-on-patch/.yarn/releases/yarn-berry.js:31:46062)
    at C.resolveFilename (/patch-depends-on-patch/.yarn/releases/yarn-berry.js:31:153926)
    at C.readFileSync (/patch-depends-on-patch/.yarn/releases/yarn-berry.js:31:160910)
    at C.readFilePromise (/patch-depends-on-patch/.yarn/releases/yarn-berry.js:31:160776)
    at i.readFilePromise (/patch-depends-on-patch/.yarn/releases/yarn-berry.js:31:136120)
    at onRelative (/patch-depends-on-patch/.yarn/releases/yarn-berry.js:77:110839)
    at O (/patch-depends-on-patch/.yarn/releases/yarn-berry.js:77:110259)
    at /patch-depends-on-patch/.yarn/releases/yarn-berry.js:77:110639
    at Array.map (<anonymous>)
➤ YN0000: └ Completed
➤ YN0000: Failed with errors in 0.1s
```

I thought it might a problem with the relative file path and I've tried every combination of relative and absolute paths I could think of, but can't get it to work. What am I doing wrong?

**Comment by arcanis** [comment]
I suspect the relative paths are resolved against the path of the cached module, not the root project. To make it more annoying, third-party packages aren't allowed to access paths outside of their own sources, so even using something like `..` won't work in the current model.

**Comment by merceyz** [comment]
In the meantime you can use resolutions https://yarnpkg.com/cli/set/resolution

**Comment by alubbe** [comment]
So that would be `yarn set resolution -s 'react-d3-core@^1.3.9' 'patch:react-d3-core@^1.3.9#./patches/react-d3-core'`, right? Where is that saved/persisted? I can only see changes to `.yarn/install-state.gz` after running that command.

**Comment by paul-soporan** [comment]
@alubbe It looks like the `--save` flag hasn't been implemented yet (but someone apparently took the time to document it, not sure how that happened 😅), so you should try modifying the top-level manifest manually.

---

🤔 This has already been closed as working as intended in https://github.com/yarnpkg/berry/issues/1127 and the current behavior makes sense and I don't think we should modify it. I don't really see another solution other than resolutions, but probably @arcanis has one, since he marked this as `help wanted`.

**Comment by alubbe** [comment]
Gotcha - that works now! Thank you :)

**Comment by arcanis** [comment]
> probably @arcanis has one, since he marked this as `help wanted`

We could solve this the same way we do with resolutions, by binding the ranges to the root workspace rather than the modified package. As for whether it's worth the effort however, it's unclear (I usually tag "help wanted" in those cases, which I mean as "probably can be fixed by anyone who care enough about it").
