### ISSUE TITLE
[Bug] yarn install fails if casing is inconsistent for workspace directory

### ISSUE THREAD

**Issue by dpolivy** [yarnpkg/berry#1639]
- [ ] I'd be willing to implement a fix

**Describe the bug**

I am using yarn on Windows. This is the `workspaces` definition:

```
  "workspaces": [
    "packages/*",
    "mobile"
  ],
```

If the path listed is not an exact-case match to the current directory, then `yarn install` will fail with:

```
d:\git\Website\Mobile>yarn install
Usage Error: This command can only be run from within a workspace of your project (Mobile isn't a workspace of /d:/git/Website/package.json).
```

Windows treats paths as case-insensitive, so I would expect yarn to do so as well. This problem is exacerbated by the fact that if you use PowerShell as your shell, it lets you `cd` into a directory with any casing variant you want. (`cmd`, on the other hand, seems to always use the casing on disk regardless of what you type.)

**To Reproduce**

Create directory structure as follows:
```
\Test
   \packages
      \a
   \Mobile
```

Add a `package.json` to the root:

```
{
  "name": "test",
  "description": "test Monorepo",
  "private": true,
  "workspaces": [
    "packages/*",
    "mobile"
  ]
}
```

Add a basic `package.json` to the `packages/a` and `Mobile` directories.

Run `yarn install` from `Mobile`.

**Environment if relevant (please complete the following information):**

 - OS: Windows
 - Node version: 12.18.1
 - Yarn version 2.1.1

**Comment by arcanis** [comment]
I think it's fine to be case-sensitive. Generally speaking, we try to enforce that projects are as portable as possible, and in this case there is very little benefits in supporting accesses through different path cases (similarly, if you run `require('foo/PACKAGE.JSON')`, it won't work under PnP even though it would have with node_modules).

That said there was a display issue - the error message we print should have been much more descriptive, but a bug was causing the incorrect one to be displayed. This will be fixed with https://github.com/yarnpkg/berry/pull/1683.
