### ISSUE TITLE
[Bug] Init fails when package.json exists

### ISSUE THREAD

**Issue by olingern** [yarnpkg/berry#165]
**Describe the bug**

I would expect yarn to create a `yarn.lock` file and skip creating package.json if it already exists.

**To Reproduce**

- Create repo with basic `package.json`
- Run `yarn init`

**Screenshots**

![image](https://user-images.githubusercontent.com/1470297/57743199-0d192300-76ff-11e9-9ca2-3622b60536eb.png)

**Environment if relevant (please complete the following information):**

 - OS: Ubuntu 18.04.2 LTS
 - Node version: 10.1.0 
 - Yarn version: nightly

**Comment by arcanis** [comment]
Wouldn't that make it duplicate with `yarn install`? 🤔

**Comment by olingern** [comment]
For some reason I thought the current version of yarn did this as npm did, but that's not the case.

![image](https://user-images.githubusercontent.com/1470297/57817829-351a8c00-77bc-11e9-9e77-ca4e4b1dd3cc.png)

Ergonomically, I think it would be nice to have a prompt that says:

> A package.json already exists, would you like to create a new one?

**Comment by olingern** [comment]
Since this is maintaining current Yarn functionality, not a bug. What do you think @arcanis about adding the prompt?

Closing this, but can open a feature issue if the prompt is :+1:

**Comment by arcanis** [comment]
A prompt might be interesting - I think the best would be to turn `init` into some kind of (very) basic package.json editor using enquirer's snippet prompts:

https://github.com/enquirer/enquirer#snippet-prompt

The way I see it:

- When you run `init` on an empty project it opens the editor with the fields empty (or prepopulated by the configuration in the `init-*` variables). You enter the values, press enter, it gets saved.

- When  you run `init` on an existing project it still opens the editor, but this time you see the values that currently are in your `package.json`. You can leave them as they are, or modify them as you like (empty fields are removed from the manifest).

- For simplicity I think we can only allow edition for the supported files - name, version, description, license. We can add other fields later on if they make sense, but I'd like to keep the command light.

- If possible (maybe it isn't?), it would also be nice to have one virtual boolean field that indicates whether the package dependencies should be kept or not (only for existing projects, of course). It would default to `true`. We could name it `preserve_dependencies`.

One problem is that we're already using inquirer so that would duplicate a bit the features ... it would be nice to find a way to avoid that. Maybe the `Report` class should provided tiny abstracted members. So that instead of using `inquirer.prompt` we would instead do `report.prompt(..., {stdin})`.

Would you be interested to tackle that? 😃

**Comment by olingern** [comment]
> Would you be interested to tackle that?

@arcanis yah, I'll give that a look today and open an feature issue :slightly_smiling_face:
