### ISSUE TITLE
[Bug] packages missing from node_modules when using workspaces

### ISSUE THREAD

**Issue by mikaelkolkinn** [yarnpkg/berry#1677]
- [ ] I'd be willing to implement a fix

**Describe the bug**

I have a workspace setup with a few workspaces/packages in it.
Yarn is configured with `nodeLinker: node-modules`.

When doing a yarn install in the workspace root, some packages required by one of the workspaces seem to be missing from node_modules.

When instead doing a focused install `yarn workspaces focus [workspace]` all the required packages for that workspace go into the node_modules directory.

**To Reproduce**

I've created a reproduction repository here https://github.com/mikaelkolkinn/yarn_unfocused_issue_repro
It contains four workspaces/packages, where the one that fails is called "sanity-studio". It will fail when building after a regular `yarn install`, but will succeed when doing a focused install.

With the regular `yarn install`, `ls node_modules | grep slate` will return five results.
With a focused install `yarn workspaces focus sanity-studio`, `ls node_modules | grep slate` will return 10 results.

<details>
  <summary>Quick reproduction commands</summary>

  ```sh
# initial install
yarn

# build fails
yarn reproduce

# build succeeds
yarn workaround
  ```
</details>

**Environment if relevant (please complete the following information):**

 - OS: OSX
 - Node version: v14.4.0
 - Yarn version: 2.1.1

**Additional context**

The sanity-studio workspace/package was manually copied into the "packages" directory after initializing through a command line tool.

**Comment by larixer** [comment]
This is not a bug in Yarn, but it is rather a bug in some of slate dependencies. They must not assume that all of the slate dependencies will be hoisted to the top-level node_modules. The hoisting layout between focused and unfocused installs can very  well be different, because dependency graphs are different, this is not a bug.

**Comment by mikaelkolkinn** [comment]
> This is not a bug in Yarn, but it is rather a bug in some of slate dependencies. They must not assume that all of the slate dependencies will be hoisted to the top-level node_modules. The hoisting layout between focused and unfocused installs can very well be different, because dependency graphs are different, this is not a bug.

Thank you for pointing me in the right direction @larixer.
I was clueless as to where the issue lied. I'll investigate how to resolve this with slate.

**Comment by larixer** [comment]
@mikaelkolkinn You can understand why hoisting layout ended up being like this via:
```
NM_DEBUG_LEVEL=2 yarn
```
You will see that `slate` are stuck inside `@sanity/form-builder` because there are two versions of `immutable` used within project. So the quick workaround will be to add `immutable` to the resolutions, e..g
```
  "resolutions": {
    "immutable": "3.8.2",
    "lodash": "4.17.19",
    "react-dev-utils": "^10.0.0"
  }
```

But this is a workaround. The real bug is probably inside `@sanity/form-builder` code or inside one of the `slate` deps code. They make incorrect assumptions about hoisting layout.

**Comment by mikaelkolkinn** [comment]
Thank you so much @larixer!
The workaround worked perfectly, and now I have something concrete to talk to the sanity/slate guys about.
