### ISSUE TITLE
IPC is not enabled while using spawn. [Bug]

### ISSUE THREAD

**Issue by LvChengbin** [yarnpkg/berry#1696]
IPC is not enabled while using `child_process.spawn`, and the `process.send` in child process is undefined.

```js
spawn( 'yarn', [ 'node', 'index.js' ], {
    stdio : [ 'inherit', 'inherit', 'inherit', 'ipc' ]
} );
```

**Comment by paul-soporan** [comment]
I think this is intended: the `yarn node` command sets up the environment (registers the PnP runtime in the current environment using `NODE_OPTIONS`) and spawns a new node process, so the `ipc` connection isn't "forwarded" to the subprocess (I don't think it's even possible to inherit an IPC connection, correct me if I'm wrong).
A solution would be to drop the `yarn node` and just use `node` if already running inside a context with `NODE_OPTIONS` setup (meaning if the entry is already run via `yarn node`), since `NODE_OPTIONS` affects all subprocesses.

**Comment by arcanis** [comment]
Yep, we won't open IPC for all processes, so we can't forward them at all. If you need them, call the binaries your own way (ie setting `NODE_OPTIONS` and all).
