### ISSUE TITLE
[Feature] Case sensitivity of PnP virtual filesystem

### ISSUE THREAD

**Issue by charlessuh** [yarnpkg/berry#1762]
- [ ] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

Hi. I'm running into an issue with PnP where `eslint-plugin-import` attempts to detect the case sensitivity of the underlying filesystem (which is used for rules like `no-unresolved`) by using `fs.existsSync` like so: 

https://github.com/benmosher/eslint-plugin-import/blob/1737429e3b3c91974498fcb49a3e167b9e49b53b/utils/resolve.js#L13

My testing shows the virtual zip filesystem when using PnP is case sensitive, so if this is accurate, this detection would result in different behavior on macOS / APFS where previously a real `node_modules` folder would have been on a case insensitive filesystem.

I haven't given this much thought, and was wondering if there has been any previous discussion on this?

**Describe the solution you'd like**

Could yarn emulate the case sensitivity of the underlying filesystem?

**Describe the drawbacks of your solution**

Could this break packages which makes assumptions in the opposite direction (have multiple files which both resolve to the same case insensitive name, like `src/fileA.js` and `src/filea.js`)?

**Describe alternatives you've considered**

Should packages like `eslint-plugin-import` not rely on case sensitivity tests like these and be fixed?

**Additional context**

See issue here: https://github.com/benmosher/eslint-plugin-import/issues/806#issuecomment-679322268

**Comment by arcanis** [comment]
The case sensitivity is intended. Reimplementing case insensitivity would open a large surface for problems in terms of security, correctness, and just code complexity.

Since we're dealing with a virtual filesystem, it sounds reasonable to instead just define it as case sensitive and avoid all those potential issues. After all, it's more or less what would happen if you really mounted a case sensitive filesystem in your project.
