### ISSUE TITLE
Shared ESLint config with yarn workspace aliases

### ISSUE THREAD

**Issue by brandon-leapyear** [yarnpkg/berry#2115]
There are a couple conflating issues going on here, that only really create a problem when combined, so please bear with me for a bit.

First, in our monorepo, we define aliases for workspaces
```json
{
  "workspaces": [ "./foo" ],
  "scripts": {
    "@foo": "yarn workspace foo"
  }
}
```
so that we can run workspace commands from the top-level (`yarn @foo build`). Maybe this isn't best practice, but we can discuss that later. Now, immediately, we see an inconsistency between the two possible invocations. Let's say we install `eslint` in the top level `package.json` and then call it in the subworkspace.
```json
// package.json
{
  "devDependencies": {
   "eslint": "latest",
  },
}

// foo/package.json
{
  "scripts": {
    "lint": "eslint",
  },
}
```
```bash
$ yarn workspace foo lint . && echo $?
command not found: eslint
1

$ yarn @foo lint . && echo $?
0
```
The first line makes sense, since Yarn 2 now isolates commands to the package.json that defines it in dependencies. The second line, however, gets `eslint` on PATH, presumably because the `package.json` invoked was the top-level `package.json`, even though it then delegated to the workspace.

Second issue: if `foo/.eslintrc.js` uses a plugin, like
```js
module.exports = {
  extends: ['plugin:react/recommended'],
}
```
and we install `eslint-plugin-react` in the top-level (because we want to use the `eslint-plugin-react` plugin in multiple packages), we get
```
$ yarn @foo lint .

Oops! Something went wrong! :(

ESLint: 7.13.0

ESLint couldn't find the plugin "eslint-plugin-react".

(The package "eslint-plugin-react" was not found when loaded as a Node module from the directory "/Users/bchinn/Desktop/foo/bar".)

It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm install eslint-plugin-react@latest --save-dev

The plugin "eslint-plugin-react" was referenced from the config file in ".eslintrc.js".

If you still can't figure out the problem, please stop by https://eslint.org/chat/help to chat with the team.
```
So using the alias, we still get `eslint` on PATH, but then we can't load in any modules.

For our exact situation, we have ESLint and all the plugins defined in the top-level `package.json`, and then use `yarn lint ./foo/path/to/index.js` to lint all the Javascript files, in any workspace. This works fine, except for one situation. One of our workspaces uses `graphql-codegen` and we have a hook that runs eslint/prettier on the generated file, and while `eslint` is on PATH (due to using an alias for the workspace) it can't find any eslint plugins (due to the second issue).

There's a lot here, so I'll try to sum it all up with the following questions:
1. Is using workspace aliases as described here undefined behavior and should be considered unsupported?
2. Is it possible to still define all the eslint deps in the top-level to be used by everything below, or will we have to redeclare the eslint deps in every workspace?

**Comment by merceyz** [comment]
> Is it possible to still define all the eslint deps in the top-level to be used by everything below, or will we have to redeclare the eslint deps in every workspace?

Just to note: the docs mention this here https://yarnpkg.com/getting-started/qa/#how-to-share-scripts-between-workspaces

**Comment by brandon-leapyear** [comment]
> > Is using workspace aliases as described here undefined behavior and should be considered unsupported?
> > Is it possible to still define all the eslint deps in the top-level to be used by everything below, or will we have to redeclare the eslint deps in every workspace?
> 
> The docs for sharing scripts might be what you're after https://yarnpkg.com/getting-started/qa/#how-to-share-scripts-between-workspaces

I don't think that section is applicable. I'm not talking about using the same commands in each workspace. I'm talking about:
1. Having an alias for `yarn workspace foo asdf` as `yarn @foo asdf`. Now, we could change everything to be `yarn foo:asdf`, but it would be nice if we could keep our existing configuration using aliases
2. Workspaces inheriting dependencies from the top-level, e.g. the top-level having `"eslint-plugin-react": "1.2.3"` in deps, and all the other workspaces having access to that module without needing to redeclare it in their `package.json` files

**Comment by bgotink** [comment]
> 1. Is using workspace aliases as described here undefined behavior and should be considered unsupported?

You're effectively running two yarn scripts with the `@foo` alias, which ends up adding _two_ binary folders to the PATH of the inner script: the inner script is `yarn workspace foo eslint`, the outer script is `yarn run @foo eslint`

If you run

```
yarn workspace foo eslint
```

yarn adds a folder to the PATH that contains scripts to execute any binary exposed to the `foo` workspace, as well as scripts named `yarn` and `yarnpkg`, `run`, `node` and `node-gyp`.

The same happens if you run a command in your top-level workspace, except it adds the binaries that are exposed in the top-level workspace. This one contains `eslint` in your project.

To show what's going on, I've created a script called `@core` in the berry repo:

```json
{
  "scripts": {
    "@core": "yarn workspace @yarnpkg/core"
  }
}
```

This is the output:

```
bram $ yarn workspace @yarnpkg/core exec bash -c 'echo $PATH' | sed 's/:/\n/g'
/private/var/folders/_d/ch2kc4h960d10cy_2c41qqzw0000gn/T/xfs-a3061d54 <-- binaries available to @yarnpkg/core
/Users/bram/.nvm/versions/node/v12.19.0/bin
... the usual stuff like /usr/local/bin etc

bram $ yarn @core exec bash -c 'echo $PATH' | sed 's/:/\n/g'
/private/var/folders/_d/ch2kc4h960d10cy_2c41qqzw0000gn/T/xfs-657bcff2 <-- binaries available to @yarnpkg/core
/private/var/folders/_d/ch2kc4h960d10cy_2c41qqzw0000gn/T/xfs-e2ecf12e <-- binaries available to root package
/Users/bram/.nvm/versions/node/v12.19.0/bin
... the usual stuff like /usr/local/bin etc
```

> 2. Is it possible to still define all the eslint deps in the top-level to be used by everything below, or will we have to redeclare the eslint deps in every workspace?

There are multiple solutions.

You could introduce a script with a colon in the name, like the FAQ answer @merceyz already linked to.
That would mean adding a script called e.g. `:eslint` in the root workspace which executes `cd $INIT_CWD && eslint`. You can then run

```
yarn @foo :eslint
```

and that'll do what you want it to do: run the eslint installed in the root workspace in the `foo` workspace.

An alternative is to use the `--top-level`/`-T` flag to run `eslint`, e.g.

```
yarn @foo run -T eslint
```

For both of those solutions you could define an alias in the `foo` workspace, mapping `eslint` to either `run :eslint` or `run -T eslint`, which would allow running

```
yarn @foo eslint
```

See also: #953.
As an update to that ticket: I've written an angular plugin for yarn which, among a bunch of other things, makes the `ng` script installed by `@angular/cli` in the root workspace available in every workspace of the project.
That's a lot more developer friendly than having to memorize `yarn :ng` and it's a lot more maintainer friendly than having a `"ng": "run -T ng"` script defined in every package.json.

**Comment by brandon-leapyear** [comment]
So the use-case we have is running `yarn @foo codegen`, where the `codegen` script calls `graphql-codegen` with the following config file:
```yaml
schema: ...
documents: ...
generates: ...
hooks:
  afterAllFileWrite:
    - eslint --ext .js,.ts,.tsx --fix
```
which will generate files like `getUsers.generated.tsx` and then run the given command like `eslint --ext .js,.ts,.tsx --fix ./src/getUsers.generated.tsx`

So we can't use `cd $INIT_CWD` because the paths are relative to the workspace.

I tried make it `run -T eslint --ext .js,.ts,.tsx --fix`, but it doesn't seem to work; I still get "ESLint couldn't find the plugin 'eslint-plugin-react'". Your example of
```
yarn @foo run -T eslint .
```
shows me the same error

**Comment by bgotink** [comment]
Oh right, the config issue.

ESLint 7 by default resolves plugins relative to the configuration file that's being used. In other words, if your eslint config is in the `foo` workspace, then you'll have to install the plugins used in the configuration in that workspace.

You can override eslint's behaviour using the `--resolve-plugins-relative-to` flag. For example, if your `foo` package is in `packages/foo` that could be

```yaml
hooks:
  afterAllFileWrite:
    - run -T eslint --ext .js,.ts,.tsx --fix --resolve-plugins-relative-to ../..
```

**Comment by brandon-leapyear** [comment]
That works, thank you!
