### ISSUE TITLE
Alternative to committing the yarn binary to every repo

### ISSUE THREAD

**Issue by whatisaphone** [yarnpkg/berry#2216]
I started trying to move our company onto Yarn 2 recently. One thing that jumped out at me as peculiar was the requirement to commit the yarn binary to the repo. After all, you don't commit other binaries, and (except in rare cases) you don't commit node_modules either.

How crazy would it be to have .yarnrc.yml look like this:

```yaml
yarnVersion: 2.4.0
```

and have yarn 1.x locale the matching yarn binary using its package caching system that already exists?

**Comment by arcanis** [comment]
It's in our plans, but the idea is to make this part of Node itself (as a joint work). We'll hopefully have more to share in a few months, until then checking-in the binary is still recommended. I'd advise to make a trial run, and see how it works in practice.

Closing since non-actionable for the time being.

**Comment by larixer** [comment]
@whatisaphone See also:
https://github.com/yarnpkg/berry/issues/969

**Comment by whatisaphone** [comment]
Ah nice, I wasn't aware you had a grander plan in mind. I'll follow that other issue, thanks
