### ISSUE TITLE
[Feature] Allow disabling plugin-compat while using node-modules linker.

### ISSUE THREAD

**Issue by rehikari** [yarnpkg/berry#2277]
- [ ] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [x] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

I want to use yarn 2 in my project without pnp enabled for some reason. In this case, `plugin-compat` doesn't make a lot of sense. Instead, it may crash in some rare conditions (e.g. installing a dev version of TypeScript). Currently, the only solution is to create an empty plugin to override the existing plugin, which seems a bit weird.

**Describe the solution you'd like**

Allow users to opt-out of the compat plugin, or more generally, any of the built-in plugins.

**Describe the drawbacks of your solution**

Allow users to disable any of the built-in plugins may cause a crash, but at least, it's safe for the compat one.

**Describe alternatives you've considered**

/

**Comment by arcanis** [comment]
While it would allow some things like using nightly TS builds without the patch, it would also cause installs to be more different from one user to the other than they currently are, increasing the surface for edge cases. Additionally, `plugin-compat` is important even with PnP, since properly listing dependencies has a direct impact on the hoisting correctness.

And as you mentioned, you already can disable it by overriding it if you so choose - it's just that we won't support this by default, since the value / cost ratio isn't very high.
