### ISSUE TITLE
[Feature] is there something like `prune`?

### ISSUE THREAD

**Issue by pvinis** [yarnpkg/berry#228]
- [ ] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

- I had my project all good.
- I add a lib with `yarn add bla`. (package.json, lockfile and .yarn stuff get added)
- I remove the lib manually from package.json
- How do I remove the unneeded .yarn stuff?

**Describe the solution you'd like**
maybe after running `yarn` again they get cleaned? or maybe i run `yarn prune` or something?
whats the idea of doing that?

**Comment by arcanis** [comment]
`yarn cache clean` will do exactly that (you can check our Azure jobs for an example of how to integrate it on CI, too) 🙂

Autoprune is not part of the software yet because the cache is possibly shared by multiple projects. We could imagine doing it when we detect that it's inside the project, though (since it's the default) 🤔

**Comment by pvinis** [comment]
ah ok. I thought cache clean would also clean the global cache.

**Comment by deini** [comment]
Implemented in https://github.com/yarnpkg/berry/pull/372
