### ISSUE TITLE
[Feature] Use nodeLinker: node-modules for a particular workspace instead of project wide

### ISSUE THREAD

**Issue by sunniejai** [yarnpkg/berry#2301]
Yarn version: 2.4

We have a monorepo that's setup like this:

- webapp
- shared packages
- mobile 

For our web app, we're able to set it up to use pnp successfully, but our mobile app is using react native, so we are not able to use pnp there.

Currently, it looks like you can only have one .yarnrc.yml file for the entire project that will either turn pnp on or off. Is there a way to setup nodeLinker: node-modules on a workspace level instead so that we can use pnp linker in the web app and node-modules linker in the mobile app? Perhaps some config on package.json?

Thanks,

**Comment by theseyi** [comment]
I think this is a very useful feature to have for workspaces that include incompatible packages, I have a similar issue with a package that uses the `serverless` library. Is there a workaround in the interim, or guidelines on how we can help add this feature?

**Comment by juuyan** [comment]
I think this feature is very important for mono-repo. Most of time a project for web frontend only would be fine with pnp, but when a mono-repo included workspaces for mobile and backend, things started to get really painful.

**Comment by arcanis** [comment]
I'll close this issue as a wontfix. While it's something that would be really nice to have, implementing a system like that would have a far too heavy cost on the Yarn core itself - many assumptions would have to be broken down, reengineered, and the result would be significantly more complex than now. In short, it's one of those cases where the cons outweigh the pros.

With that being said, I believe you can already achieve a somewhat similar effect using a combination of:

- Multiple lockfiles (basically, the main project uses the PnP linker, and a nested subproject uses the nm linker)
- Use of [`pnpIgnorePatterns`](https://yarnpkg.com/configuration/yarnrc#pnpIgnorePatterns) to tell Yarn to ignore PnP for the subproject
- Use the [`portal:` protocol](https://yarnpkg.com/features/protocols) to cross-reference packages from the main workspace.
- Configure the subproject cache to share the main one (or use the global cache, perhaps)

Perhaps a plugin could generate the boilerplate needed to make that work without user interaction, kinda similar to what Lerna used to do back when workspaces weren't native features yet?

**Comment by andreialecu** [comment]
I'm using this sort of setup semi-successfully with Angular (because it doesn't support PnP).

Basically my setup looks like the following:

```
nm-packages/some-angular-project
packages/* (pnp workspaces)
```

`nm-packages/some-angular-project` has its own `.yarnrc.yml` that only has this in it:

```yaml
nodeLinker: node-modules
```

You also need to create an empty `yarn.lock` file. Afterwards, running `yarn install` within this directory will detach it from the main pnp root and create its own `node_modules` based installation

I was able to use the `link:` protocol to cross-reference a `pnp` workspace within the `nm` one via:

```json
    "data-models": "link:../../packages/data-models",
```

There's a caveat. In this example you'll need to manually install any dependencies that `data-models` depends on into `some-angular-project`, `yarn` won't do it by itself.

`portal` and `link` are equivalent in this case, because the nm linker will not install any of the referenced project's dependencies into the target project. (ref: https://github.com/yarnpkg/berry/issues/2265#issuecomment-751231630)

This is also important to add in the main `.yarnrc.yml`:

```yaml
pnpIgnorePatterns:
  - ./nm-packages/**
```

You may run into VSCode not recognizing types properly in the nm-based project, which has been fixed by: https://github.com/arcanis/TypeScript/pull/3 but I don't think it is in any release yet. I'm currently using my own fork of yarn that has this patch in it. If anyone needs it let me know and I'll write up an explanation on how to use it.

**Comment by theseyi** [comment]
@andreialecu interesting. You said "semi-successfully" other than the obvious unwanted complexity, what other issues make this semi successful?

I've opted to using the node_modules nodeLinker currently in my workspace

**Comment by andreialecu** [comment]
Well, everything works as long as you keep things simple because of the caveat I mentioned.

Your linked pnp workspaces cannot depend on a specific version range of a package (say `pnp-lib-a` needs `lodash@2` while your nm workspace needs `lodash@3`).

This hasn't been a problem for me, and I tried limiting the number of dependencies needed by the linked workspaces to a minimum.

So it's been successful for me so far. I guess "semi" wasn't warranted. 🙂

**Comment by abh1kg** [comment]
@andreialecu : If you have your repository on github.com, would you mind sharing a link? I created #2432 (with a repro at https://github.com/abh1kg/yarn-multiproject-repro ) - for me, `yarn install` within the sub-project fails. The stacktrace is also added in the repro. Did you not face this for your setup?

**Comment by sukjae** [comment]
> I'll close this issue as a wontfix. While it's something that would be really nice to have, implementing a system like that would have a far too heavy cost on the Yarn core itself - many assumptions would have to be broken down, reengineered, and the result would be significantly more complex than now. In short, it's one of those cases where the cons outweigh the pros.
> 
> With that being said, I believe you can already achieve a somewhat similar effect using a combination of:
> 
> * Multiple lockfiles (basically, the main project uses the PnP linker, and a nested subproject uses the nm linker)
> * Use of [`pnpIgnorePatterns`](https://yarnpkg.com/configuration/yarnrc#pnpIgnorePatterns) to tell Yarn to ignore PnP for the subproject
> * Use the [`portal:` protocol](https://yarnpkg.com/features/protocols) to cross-reference packages from the main workspace.
> * Configure the subproject cache to share the main one (or use the global cache, perhaps)
> 
> Perhaps a plugin could generate the boilerplate needed to make that work without user interaction, kinda similar to what Lerna used to do back when workspaces weren't native features yet?

Thanks for giving possible solution. 🙏
What i want to achieve is basically to use both PNP and node_module in single repo. 
I think your solution fits my use case, but i couldn't implement your guidance.
Do you have any code example which i can refer to? It would be very helpful if so. Thank you. 

Also, I am very curious about what `Multiple lockfiles` means. is it yarn.lock files?

**Comment by djaax** [comment]
Thanks for the inspiration, @andreialecu.

I implemented your suggested solution but couldn't live with the VSCode issue. I implemented something slightly hackier but less invasive. In my case, I only needed the node_modules for a particular deployment – for Google Cloud Functions with `firebase deploy`.

My solution is a little bash script `predeploy.sh` that uses `yarn prod-install` to pack everything into a dedicated directory `deploy`.

```
#!/usr/bin/env bash

yarn prod-install deploy

# outDir in tsconfig.json: deploy/lib
tsc -b

# Overwrite .yarnrc.yml to use node_modules
echo "nodeLinker: node-modules" > deploy/.yarnrc.yml

cd deploy

# Install dependencies as node_modules
yarn
```

And in my `.yarnrc.yml` in root:

```
pnpIgnorePatterns:
  - ./packages/*/deploy/**
```

**Comment by adrian-gierakowski** [comment]
I’m in the same boat since we recently added a mobile RN based app to a large monorepo using pnp linker. Solution I’m thinking about is to have a single workspace and to switch to node-modules linker when working on the mobile app. An issue I’m facing is slow installs when switching, for which a workaround is to always use yarn workspace focus when working on mobile. 

@arcanis could be useful to think about how this could be improved in [next supermajor ](https://github.com/yarnpkg/berry/discussions/6608) release
