### ISSUE TITLE
[Bug] Boolean env var inside .yarnrc.yml is not correctly interpreted

### ISSUE THREAD

**Issue by kakawait** [yarnpkg/berry#2339]
- [ ] I'd be willing to implement a fix

**Describe the bug**

When using env var for boolean value, is not correctly valued or interpreted.

**To Reproduce**

Create `.yarnrc.yml` and put

```yml
enableScripts: ${MY_ENV:-true}
```

Without `MY_ENV` set (or set using correct boolean value)

Failed with 

```
Internal Error: Couldn't parse "${MY_ENV:-true}" as a boolean in <PAHT>/.yarnrc.yml (in <PATH>/.yarnrc.yml)
```

**Environment if relevant (please complete the following information):**

 - OS: MacOs 10.14.6
 - Node version: v15.5.1
 - Yarn version: yarn-2.4.0

**Comment by gaelhameon** [comment]
I have the same issue.

I think the problem comes from here:

https://github.com/yarnpkg/berry/blob/74579e605e35efeb14df96aa9c3cd72ea9209537/packages/yarnpkg-core/sources/Configuration.ts#L611-L620

The code tries to parse as boolean before calling `miscUtils.replaceEnvVariables`

I'm guessing there is probably a reason for that and the solution can't be as simple as moving lines 618-620 above line 612 ...

Or can it ? @merceyz , is there anything I can do to help on this issue ?

**Comment by paul-soporan** [comment]
Fun story: @merceyz originally looked into it, changed it, and left it in a stash and then I discovered the cause independently and I was told "feel free to take it" only for me to also change it and leave it forgotten inside a stash. 😅

I'm going to open a PR in a few minutes after I add a test.

> I'm guessing there is probably a reason for that and the solution can't be as simple as moving lines 618-620 above line 612 ...

We first have to handle the case where it's not a string, as we have a few `configuration.use` calls that use a boolean directly.
