### ISSUE TITLE
[Feature] yarn npm publish set the tag accordingly to the version number

### ISSUE THREAD

**Issue by Divlo** [yarnpkg/berry#2444]
- [x] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [x] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

As discussed in this npm discussions : https://github.com/npm/feedback/discussions/194
We want to automate the workflow to publish npm packages with GitHub Actions, we run this command : `npm publish --access public`, the yarn equivalent is this one : `yarn npm publish`

The problem is that by default it publishes the package with the latest tag, without taking care of the version number, quote from the [doc](https://yarnpkg.com/cli/npm/publish) : 
> The package will by default be attached to the `latest` tag on the registry, but this behavior can be overriden by using the --tag option.

Currently : Versions numbers have no direct connection with dist-tags
That makes difficult to automate the release process on different tags with git tag/release.

**Describe the solution you'd like**

The solution is that, the version number (inside `package.json`) tells on what tag the package will be attached on the registry.
Examples of various versions values inside my `package.json`
- `16.0.3` release the package attached to the `latest` tag
- `16.0.3-tagname.1` release the package attached to the `tagname` tag
- `16.0.3-beta.1` release the package attached to the `beta` tag

And so on, you've got the idea, currently we can have a version number with the value : `16.0.3-beta.1` but released under the `latest` tag, that makes no sense in my opinion.

**Describe the drawbacks of your solution**

I don't see any use case, where you want to release under a version number with the value : `16.0.3-tagname.1` under the `latest` tag, but maybe there are some packages that rely on this, so it's a **BREAKING CHANGE**, and we should consider it for Yarn 3 : #1406
 
But I see rarely that sort of version number under `latest` tag, although apparently [clipanion](https://www.npmjs.com/package/clipanion), the npm package that power this code base, use this behavior : currently the package is released under the `latest` tag with this version number : `3.0.0-rc.6`, that version number should be instead release under the `rc` tag, not to the `latest`.

In my opinion, if we considering adding this feature, we should also consider removing the `--tag #0` option for the publish command, so it's again a **BREAKING CHANGE**, because instead to rely on this flag, we rely on the version number.

Also in terms of code inside the `publish` command, we would need to add a little bit of code since we need to parse the version number and to see if there is a tag name or not, if not we release under `latest` else we release under the tag name.
I don't think it's that hard, I already have some pseudocode in my head to implement this, even if I don't really know how works the yarn cli codebase and I would be happy to open a PR. :smile:

**Comment by arcanis** [comment]
> In my opinion, if we considering adding this feature, we should also consider removing the `--tag #0` option for the publish command, so it's again a **BREAKING CHANGE**, because instead to rely on this flag, we rely on the version number.

I don't think removing the `--tag` flag would be wise. Current workflows are working fine, there's no point breaking them by enforcing a particular tag schema - the only thing that I think is in question is the way the default tag is extracted (currently the default tag is always latest). 

> But I see rarely that sort of version number under `latest` tag, although apparently [clipanion](https://www.npmjs.com/package/clipanion), the npm package that power this code base, use this behavior : currently the package is released under the `latest` tag with this version number : `3.0.0-rc.6`, that version number should be instead release under the `rc` tag, not to the `latest`.

This is mostly because I'm lazy and never bother to check which tag should be set when doing a publish. This is partially why I think it's an interesting idea: if I'm too lazy to set tags, I suspect more projects might be and would benefit from a smarter default.

On the other hand, there are a few other things that need to be considered regarding `latest`, in particular when it doesn't actually point to the latest release .. for instance, I opened a few months ago https://github.com/npm/feedback/discussions/109, which argues that `latest` being anything else than `latest` has potential for troubles. With this in mind, perhaps this tagging behaviour should be slightly more complex? For instance, for every publish:

- If the current version is anterior to a published version (for instance publishing `3.2.0` when `3.3.0` exists)
  - Ask confirmation if `--interactive` is set
  - Otherwise, exit with an error unless `--force` is set
- If `--tag` is set, point the tag to the newly published version; otherwise:
  - Set `latest` as default tag if the version has no prerelease qualifier
  - Set `<pre qualifier>` as default tag if the version has a prerelease qualifier (`alpha`, `beta`, `rc`, ...)
  - Abort if the default tag has a version higher than the one we're about to publish
