### ISSUE TITLE
[Feature] `yarn workspaces foreach` should pass through TTY to stdout and stderr

### ISSUE THREAD

**Issue by mariusmarais** [yarnpkg/berry#2548]
**Describe the user story**
`yarn workspaces foreach` does not pass the stdout and stderr TTY through to the running process, as `yarn run` does.

This makes many tools use a different logging format, typically disabling colors.

**Describe the solution you'd like**
Given the correct project setup (repro https://github.com/mariusmarais/repro-yarn-workspaces-tty), I would like these two commands to expose a similar environment to scripts:
 - `yarn workspace package1 run test` => TTY passes through (stdout & stderr), so colors are used automatically.
 - `yarn workspaces foreach run test` => TTY does not pass through

This makes more of a difference when running something like tests across all packages in the workspace.

As a more complicated case, here's my root workspace `dev` script for a repo with a browser frontend and a backend:
`yarn workspaces foreach -vpi --include server --include client run dev` to run the browser and backend in parallel.

The reproduction repo https://github.com/mariusmarais/repro-yarn-workspaces-tty contains a shell script that shows the difference:
```sh
~/play/yarn-workspaces-colors ❯❯❯ ./test-redir.sh

...snip...

From workspace root with "workspace"...
Is TTY? { stdout: true, stderr: true, stdin: true }

From workspace root with "workspaces foreach"...
➤ YN0000: Is TTY? { stdout: false, stderr: false, stdin: true }
➤ YN0000:
➤ YN0000: Done in 0s 335ms
```

(Note, the `YN0000:` prefix is not under discussion, only the `Is TTY?` results.)

**Describe the drawbacks of your solution**

Is this even possible when multiple processes are invoked, as is typical with `workspaces foreach`?

**Describe alternatives you've considered**

None.

**Comment by arcanis** [comment]
While we technically could (by not catching the output of the commands, and just forwarding them to the underlying stream), it wouldn't be such a good idea. The problem is that the way streams work, there's no guarantee that chunks end with a line return - and as a result the output from the various commands could very well end up entangled inside the same line. To prevent that we catch the process output and either buffer it until it's completed (the default), or stream it line by line (with `--interlaced`).

The only safe option would be to simulate a tty, which is fairly difficult to do portably and would much more complex than just configuring your tools to force colored output when relevant (even if I understand the auto tty check comes handy).

**Comment by mariusmarais** [comment]
Thanks for the explanation, just so I understand:
 - The only way to get interleaved output *with reasonable newlines* is to buffer, thus detaching the TTY.
 - One can paper over that with a simulated TTY, but that's very complex.

That doesn't sound worthwhile.

Forcing colors isn't documented with my tool, but I'm sure there must be a way.

**Comment by arcanis** [comment]
Yep, exactly. If you're working with JS tools, in general they use `chalk`, which supports a `FORCE_COLOR=1` in the environment.

**Comment by sydonia86** [comment]
What about CI tools that use stderr for other things than coloring? Bamboo for example. It displays a very useful error summary textbox, where everything written to stderr is collected, isolated from all other output.

With nothing written to stdout, our team is forced to scroll through thousands of lines of plaintext to locate the source of an error.
