### ISSUE TITLE
[Bug] @yarnpkg/plugin-typescript cannot work with packages have hyphens

### ISSUE THREAD

**Issue by hckhanh** [yarnpkg/berry#2555]
I try to add some packages: `cross-spawn`, `ace-diff`. The `@types/**` packages are not added accordingly.
But when I try some packages: `lodash` or `lodash.isequal`, it works.
So I can conclude that `@yarnpkg/plugin-typescript` cannot work with packages which contain hyphens, only work with dot (.)

**Screenshots**

![image](https://user-images.githubusercontent.com/6380436/109741803-63bb5e00-7c00-11eb-8b18-36516842a36a.png)

**Environment if relevant (please complete the following information):**

 - OS: Windows 10
 - Node: 14.16.0
 - Yarn: Berry (Latest)

**Comment by paul-soporan** [comment]
It's not actually a problem with the characters the package name contains, it's just a lesser-known heuristic of the plugin (added in #1314) - it only installs types with a matching major and skips them otherwise. 

- `cross-spawn`'s latest version is 7.x, while `@types/cross-spawn`'s is 6.x
- `ace-diff`'s latest version is 3.x, while `@types/ace-diff`'s is 2.x

That said, I don't really like this heuristic anymore because I've discovered many packages that release new majors that work without any problems with the old typings and it can get annoying very quickly. 🤔
