### ISSUE TITLE
[Feature] yarn patch-commit don't have "-s, --save" option

### ISSUE THREAD

**Issue by chrisands** [yarnpkg/berry#2579]
- [ ] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [x] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

As a developer, I would like to make patches with less movement. Currently [documentation](https://yarnpkg.com/cli/patch-commit) says that there is `-s, --save` which add patch to your resolutions.

**Describe the solution you'd like**

Implement option. I think by passing "save" option it should save `.patch` file near `package.json` and add it to package resolution. As for workspaces, it should add `.patch` near `package.json` in which package is mentioned.

**Describe the drawbacks of your solution**

It can be hard to add patch to every package through workspaces. 

**Describe alternatives you've considered**

Also it is possible to edit documentation to match realization or mark it as not implemented yet not to confuse users.

**Comment by arcanis** [comment]
That's expected - the website uses our master branch, so it's unfortunately slightly ahead of itself. You can try out the new changes with [`yarn set version from sources`](https://yarnpkg.com/cli/set/version/from/sources), or wait for the next release to be shipped.

**Comment by Peeja** [comment]
@arcanis Might it make more sense to have the main website use the latest release, rather than the latest `master`? I've been confused by a number of "wrong" things in the docs, and this explains it. Ideally, I'd like to even see the version number somewhere on the page so I can easily check it against what I'm running, but even just using the latest release would save a bunch of headache.
