### ISSUE TITLE
[Feature] Add option to automatically apply dedupe strategy on add/remove cli command

### ISSUE THREAD

**Issue by noahnu** [yarnpkg/berry#2770]
- [x] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [x] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

As a developer, I always run `yarn dedupe` after adding, removing, or updating packages. I perform a `yarn dedupe --check` in CI to prevent unnecessarily duplicated packages from ending up in my production environment. This creates unnecessary complexity.

**Describe the solution you'd like**

Introduce a new config property to `.yarnrc.yml` that lets you specify the dedupe strategy used in the `yarn add` command.

**Describe the drawbacks of your solution**

If we default the stategy to "none" / "off", I don't see any drawbacks. Perhaps main drawback would be coupling `dedupe` with `add`, which are currently quite isolated in the codebase.

**Describe alternatives you've considered**

`postinstall` script to run dedupe: only want to run it in development and don't want to unnecessarily run it if packages haven't changed.

Custom plugin: it's an option and would be quite easy to implement, but this seems like it'd be valuable in the yarn core.

**Comment by arcanis** [comment]
I believe the additional coupling is something that would be best avoided. Additionally, it can be implemented via a contrib plugin (since we have hooks executing when adding something via `yarn add`), so it doesn't seem like something that should start as a core offering (I tend to be fairly conservative: core offering must be actively used by the active core team, otherwise we won't dogfood it and regressions are more likely).
