### ISSUE TITLE
Yarn berry doesn't recognize jest when it's a dependency of another package.

### ISSUE THREAD

**Issue by TarikGul** [yarnpkg/berry#2784]
- [ ] I'd be willing to implement a fix

Hey Yarn Berry Team, 

Thanks again for all the work, absolutely loving what I have used so far, I think it's a wonderful step in the right direction! Keep up the amazing work.

**Describe the bug**

Now my issue is most likely a lack of understanding on my part but I cant seem to understand what Berry is doing which is causing this issue or how to resolve it. 

I am migrating our repos from using classic Yarn to Berry, and we have an internal package that has our `jest` test library and `eslint` with all our configuration's that we use in all our repos. With classic it was pretty simple I would just `yarn add @substrate/dev` and the `jest` command would work right away. 

But after migrating to Berry i get `command not found: jest`. 

I wrote a very lightweight repo with a single dep below to demonstrate the issue I am having.

**To Reproduce**

Steps I took to create:

```
$ mkdir test-repo
$ cd test-repo
$ npm init -y
$ yarn set version berry
$ yarn add @substrate/dev

# <add script "test" to package.json as follows> "test": "jest --silent"
$ yarn run test
command not found: jest
```

Now if I delete the `.yarn` folder and `.yarnrc.yml` and rely on classic yarn, the script will recognize jest, and work. 

[The sample Repo](https://github.com/TarikGul/yarn2-migration-issue-reproduction).

Here's the package `@substrate/dev` includes both `jest` and `eslint`.

`package.json`
```
{
  "name": "test-yarn2",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "jest --silent"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@substrate/dev": "^0.4.1"
  }
}
```

`.yarnrc.yml`
```
nodeLinker: node-modules

yarnPath: ".yarn/releases/yarn-berry.cjs"
```

I looked through the docs, and couldn't find a solution that fits my needs. Looking for some direction if possible. Thanks again.

**Comment by TarikGul** [comment]
Closing issue due to resolving it.

**Comment by matzeeable** [comment]
Hey @TarikGul !

How did you solve this? 😊

**Comment by merceyz** [comment]
Yarn only lets you run binaries from direct dependencies, if you want to use it from a sub dependency that sub dependency needs to expose it in its `bin` field

**Comment by matzeeable** [comment]
Hey @merceyz !

Thanks for your reply. Today I started the next try to migrate to Yarn 2. 

Ok, I have the following structure:

```
packages/
  a/
    package.json (A)
package.json (B)
```

Now, I have defined the following in `package.json (A)`:

```json
{
    "bin": {
        "dotenv": "./node_modules/.bin/dotenv"
    },
    "devDependencies": {
        "dotenv-cli": "~4.0.0"
    }
}
```

I need to access the `dotenv` binary in `package.json (B)#scripts` but it always says:

```
Usage Error: Couldn't find a script named "dotenv".
```

**Comment by merceyz** [comment]
You shouldn't hardcode the `node_modules` path as that is not guaranteed to stay the same and it's an implementation detail you shouldn't rely on. You should point it to your own js file that requires the `dotenv-cli`.

> I need to access the dotenv binary in package.json (B)#scripts but it always says:

It needs to declare A as a dependency

**Comment by TarikGul** [comment]
Hey @matzeeable, to expand on what @merceyz is saying ill give you an example. 

You can have a folder `<ROOT>/scripts` and inside there lets say you have a file called `run-dotenv.js`.

The contents of that file would look something like: 

```
#!/usr/bin/env node

console.log('dotenv', process.argv.slice(2).join(' '));

require('dotenv-cli/bin/dotenv');
``` 

Then from there inside of your `package.json` you would have

```
{
    "bin": {
        "dotenv": "./scripts/run-dotenv.js"
    },
    "devDependencies": {
        "dotenv-cli": "~4.0.0"
  
```

Hope that helps.

**Comment by niieani** [comment]
Here's my workaround: 

Create a bin called e.g. `r` in your package (or your dependency):

`./bin/r.js`

```js
#!/usr/bin/env node
process.argv.splice(1, 1)
require(`${process.cwd()}/node_modules/.bin/${process.argv[1]}`)
```

Then add it to package.json

```json
  "bin": {
    "r": "./bin/r.js"
  }
```

Now you can use it to call transitive packages (or any packages) in your `node_modules` by prefixing them with `r`, e.g.:

```json
  "scripts": {
    "thing": "r my-transitive-bin"
  }
```

Same thing from command line, use `yarn r` instead of `yarn run`:

`yarn r my-transitive-bin`

This will work properly from any directory, because yarn sets `cwd` to package's root.

**Comment by merceyz** [comment]
@niieani Feel free to create a feature request for that but your workaround is relying on an implementation detail and shouldn't be used.

**Comment by niieani** [comment]
@merceyz 
@milesj previously created one https://github.com/yarnpkg/berry/issues/3109, but you closed it as 'not a bug'.
I think the community deserves at least workarounds, since this is a breaking change from all the other tools (yarn 1, yarn 2, npm, pnpm). Kinda stumped by the fact you've hidden the comment, when I'm only trying to be helpful to others that stumble upon this and need a one. I've explicitly mentioned this is a workaround.

**Comment by GeorgeTaveras1231** [comment]
Not sure what the best long term solution to this problem is, but just wanted to call out that the suggested workaround conflict with node's package exports feature as it requires that the maintainers of the original bin allow requires of the bin files.

For example, if I add

```
require('some-package/bin/some-file`)
```

And the maintainer of `some-package` has this in their package.json

```json
{
  "exports": {
     ".": "main.js"
  }
}
```

My require will break.

It will require that they add `./bin/some-file` to the `exports` entry in their package.json


```json
{
  "exports": {
     ".": "main.js"
     "./bin/some-file": "./path-to-bin"
  }
}
```

**Comment by IMalyugin** [comment]
Ouch, this is the exact and only solution I came up with, but in my opinion there should be a way for yarn to resolve transitive binaries without parsing package.json. For the same reason createRequire works, when making up a framework that incapsulates different configuration packages, there should be a way to traverse dependencies manually and use binaries.

**Comment by arcanis** [comment]
That's an interesting idea. It could make sense to support something like `yarn run my-tools/eslint` 🤔

**Comment by IMalyugin** [comment]
It should support multiple steps and scopes, like:
```
yarn run scope__react/scope__core/eslint/eslint
```
And it looks a bit too complicated?
Probably rather than that, would be nice to allow running binaries given a package origin, since in most of the cases it would be called programmatically.

So something between these lines:
```
yarn run eslint --origin="./.yarn/__virtual__/eslint-virtual-7aa56629bc/0/cache/eslint-npm-8.2.5-e749e26bb5-a660555788.zip"
```
where origin is the virtual folder for the package you want to call binary from, that can be created via createRequire

To make it fully programmatic, it could be an comma-separated array of dependencies:
```
yarn run eslint --resolveChain=@scope/react, @scope/core, eslint
```
That could read, execute eslint binary by resolving eslint package from @scope/core dependency of @scope/react dependency of current package
