### ISSUE TITLE
[Bug] TypeScript resolution in latest dev build

### ISSUE THREAD

**Issue by AaronDewes** [yarnpkg/berry#2799]
- [ ] I'd be willing to implement a fix

**Describe the bug**

The latest dev version of TypeScript 4.3 doesn't work anymore, it fails to import anything. This was probably introduced through https://github.com/microsoft/TypeScript/pull/43700.

**To Reproduce**

Create a project with typescript and any other package. Try to import the package in typescript.

**Environment:**

 - OS: Ubuntu 21.04
 - Node version 14
 - Yarn version 3.0.0-rc.2

**Comment by arcanis** [comment]
It seems this PR introduced conflicts. Starting from 3.0, when conflicts arise, rather than abort the install, we fallback on the regular TS package (so that you can at least switch to the `node-modules` linker until we can sort it out). Hence why resolutions don't work.

Note that the failed patch is probably in your install logs (at least the first time you install it).

**Comment by AaronDewes** [comment]
> Note that the failed patch is probably in your install logs (at least the first time you install it).

I don't have them anymore, but I can reinstall if you need them, but if you know what's wrong, you probably don't need it, do you?

**Comment by arcanis** [comment]
Yep I think the info are enough, it was just to provide a bit of context. Thanks for the report 👍

**Comment by wdfinch** [comment]
Noticing this on ts 4.3.2. Any updates here?

**Comment by SheepReaper** [comment]
It seems it's all 4.3.x 
4.3.1-rc likewise, patch fails to apply but 4.2.4 is fine
