### ISSUE TITLE
[Bug] Yarn does not handle redirecting shell output to non-existent file gracefully

### ISSUE THREAD

**Issue by noahnu** [yarnpkg/berry#2818]
- [ ] I'd be willing to implement a fix

**Describe the bug**

When executing a package.json script using Yarn, errors are usually surfaced to the console. In the case of redirecting output to a non-existent file, errors are hidden.

**To Reproduce**

Create a package.json with a script "example":

```
"example": "echo \"text\" > folder-that-does-not-exist/myfile.txt"
```

Run `yarn example`. You'll see it doesn't complain and we get a successful exit code.

**Screenshots**

**Environment if relevant (please complete the following information):**

 - OS: OSX Big sur
 - Node version v14.15.0
 - Yarn version 3.0.0-rc.2

**Additional context**

I see similar behaviour when using the API directly: `scriptUtils.executePackageScript`. When using the API, it seems to be either hanging or crashing. Hanging in a test environment such that jest times out, and crashing the node process when using it outside of jest.

**Comment by paul-soporan** [comment]
:thinking:  Can reproduce on Node v14.16.1, but not on v15.14.0 or v16.0.0.
![image](https://user-images.githubusercontent.com/32596136/116391409-cb201380-a827-11eb-9f15-ed1358ca31e2.png)

**Comment by paul-soporan** [comment]
Looks like it also works on Node 12 and 13.

**Comment by paul-soporan** [comment]
Found a fix for Node 14, I'll open a PR.

**Comment by noahnu** [comment]
@paul-soporan I'm trying to understand your fix for my own curiosity. Do you know what changed in Node 14?

**Comment by paul-soporan** [comment]
I honestly have no idea - I just expected the bug to affect streams since all of the previous Node bugs that have affected us were affecting streams. I then tested to see if [simply creating the stream](https://github.com/yarnpkg/berry/blob/93a43a8f4d1b82151e2aecc8ab378f79f66dd99e/packages/yarnpkg-shell/sources/index.ts#L211) throws anything (the answer was yes). It was then obvious that it was either because of the [piping](https://github.com/yarnpkg/berry/blob/93a43a8f4d1b82151e2aecc8ab378f79f66dd99e/packages/yarnpkg-shell/sources/index.ts#L249) or because of [this suspiciously looking promise that doesn't explicitly reject when the stream errors](https://github.com/yarnpkg/berry/blob/93a43a8f4d1b82151e2aecc8ab378f79f66dd99e/packages/yarnpkg-shell/sources/index.ts#L260). After adding the `reject` call it seems to work, but I don't exactly know why. :sweat_smile:
