### ISSUE TITLE
[Bug] Unable to install TypeScript 4.3.2

### ISSUE THREAD

**Issue by jtbandes** [yarnpkg/berry#2938]
- [ ] I'd be willing to implement a fix

**Describe the bug**

TypeScript 4.3.2 was [released today](https://devblogs.microsoft.com/typescript/announcing-typescript-4-3). It's not possible to install it because of an issue with `plugin-compat`:

**To Reproduce**

```
yarn init
yarn set version berry
yarn add typescript
```
```
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0013: │ typescript@npm:4.3.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ typescript@patch:typescript@npm%3A4.3.2#builtin<compat/typescript>::version=4.3.2&hash=a45b0e can't be found in the cac
➤ YN0013: │ typescript@npm:4.3.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0066: │ typescript@patch:typescript@npm%3A4.3.2#builtin<compat/typescript>::version=4.3.2&hash=a45b0e: Cannot apply hunk #2 (set enableInlineHunks for details)
➤ YN0000: └ Completed in 0s 442ms
➤ YN0000: Failed with errors in 0s 572ms
```

**Environment if relevant (please complete the following information):**

 - OS: macOS 11.3.1
 - Node version v15.9.0
 - Yarn version 2.4.1

Related: https://github.com/yarnpkg/berry/issues/2384

**Comment by merceyz** [comment]
The patch has been released in 2.4.2

**Comment by bobaaaaa** [comment]
For everyone who forget how to bump yarn (like me):

```
yarn set version latest
```

**Comment by miyaokamarina** [comment]
The same issue with TS 4.4.0-beta.

**Comment by strothj** [comment]
If you want to generate your own patches for TypeScript you can inspect the script here:
https://github.com/yarnpkg/berry/blob/master/packages/plugin-compat/extra/typescript/gen-typescript-patch.js

For custom TypeScript patches, I believe you need to be on Yarn v3 rather than v2. v3 will allow the installation of TypeScript even with a failing patch (the built-in one will fail). It will then proceed to use the patch specified in your `package.json`.

TypeScript 4.4 has some things moved around which adds a step to the rebasing.

This is the patch I've been using with success for now (`typescript@4.4.0-dev.20210725`): https://gist.github.com/strothj/c863b603e00c1a8cfe1b0d426b9d8327

I can't guarantee I made no mistakes generating the patch, etc., so you at your own risk. I just thought someone else might like to use it.
