### ISSUE TITLE
[Bug?]: hard-to-debug filesystem issues when upgrading to Yarn 3

### ISSUE THREAD

**Issue by seansfkelley** [yarnpkg/berry#3270]
### Self-service

- [X] I'd be willing to implement a fix

### Describe the bug

I'm attempting to upgrade to Yarn 3 but my build machines are consistently hitting one of two filesystem-related issues.

- `Couldn't acquire a lock in a reasonable time (via /home/circleci/project/harbor/.yarn/cache/has-yarn-npm-2.1.0-b73f6750d9-5eb1d0bb85.zip.flock)`
- `Error: While cloning /home/circleci/project/harbor/packages/unit-test-config/node_modules/find-up -> /home/circleci/project/harbor/packages/harbor-cli/node_modules/find-up ENOENT: no such file or directory, scandir '/home/circleci/project/harbor/packages/unit-test-config/node_modules/find-up'`

These are kind of flaky but mostly consistent. About 1 in 10 builds succeeds, and of the other 9, they're split pretty evenly between these two exact issues -- even the offending packages are always the same two.

These are the same machines that run Yarn 2 without a hitch. I've tried some shotgun debugging around CPU/RAM/storage sizes, caching and install configuration (like `nmMode`), but no dice.

### To reproduce

n/a :(

I am unable to reproduce the issue locally or even on the build machines when SSH'd in (?!) but it fails reliably when they are left on their own. 

How can I get more debugging information to provide? I don't see any options for verbose/debug logging/stack traces in `yarn install`. Are there such options that I'm missing?

### Environment

  System:
    OS: Linux 4.15 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (36) x64 Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz
  Binaries:
    Node: 14.15.1 - /tmp/xfs-42dcb969/node
    Yarn: 3.0.0 - /tmp/xfs-42dcb969/yarn
    npm: 6.14.8 - /usr/local/bin/npm

**Comment by larixer** [comment]
Regarding the latter bug:
`Error: While cloning /home/circleci/project/harbor/packages/unit-test-config/node_modules/find-up -> /home/circleci/project/harbor/packages/harbor-cli/node_modules/find-up ENOENT: no such file or directory, scandir '/home/circleci/project/harbor/packages/unit-test-config/node_modules/find-up'`
I bet you are caching and restoring `node_modules` from the cache, the problem, is that you don't restore all of the `node_modules` folders and because of this have the error during install, you are supposed not to intervene to the way Yarn manage `node_modules` folders. Either not cache them and let Yarn do it for you, or cache them properly - e.g. all of them.

**Comment by seansfkelley** [comment]
Of all the things I tried, removing the cache entirely wasn't one of them. Whoops, and thank you; 4/4 test builds have succeeded without it.

This is a little surprising. I thought it would have supported this use case, as it did in the past, and it doesn't seem meaningfully different from e.g. pulling a branch and re-installing on my dev machine.

**Comment by merceyz** [comment]
The first error was just fixed in https://github.com/yarnpkg/berry/pull/3465

**Comment by jshearer** [comment]
Just in case anyone happens to be reading this while debugging the above issue -- `Error: While cloning ... ENOENT: no such file or directory, scandir`, _and_ is building their site on Netlify, I discovered something interesting. 

Netlify attempts to cache and restore workspace `node_modules` folders, as well as the root `node_modules`. The way they determine workspace folders is by calling 
```
YARN_IGNORE_PATH=1 yarn workspaces --json info
```
I discovered that my workspace wasn't being picked up, and as it turns out, running that command myself results in this hidden log statement:
```
{"type":"warning","data":"Missing version in workspace at \"/Users/js/project/dir\", ignoring."}
```

So _apparently_ I had forgotten to add a `version` to my workspace's `package.json`, which didn't seem to make a difference anywhere else but in this specific scenario, so I never thought to add it. 

After adding a `version`, I can confirm that netlify caches my `node_modules` folders properly, and this flaky failure is resolved.
