### ISSUE TITLE
[Bug?]: yarn dlx not working if `yarn.lock` is moved under `.yarn` folder

### ISSUE THREAD

**Issue by FezVrasta** [yarnpkg/berry#3504]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Anytime I run `yarn dlx` I get the following error:

```
➤ YN0001: Error: ENOENT: no such file or directory, open '/private/var/folders/dm/r2yzz3ws2zxbpbmrg58q5mr00000gn/T/xfs-cf56aaca/dlx-69009/.yarn/yarn.lock'
➤ YN0000: Failed with errors in 3s 507ms
```

### To reproduce

In my `.yarnrc.yml` I specified `lockfileFilename: .yarn/yarn.lock` and I think it's the reason why `dlx` is failing. If I move the `yarn.lock` file back to its original position and remove the configuration line it works again.

### Environment

```shell
System:
    OS: macOS 11.4
    CPU: (4) x64 Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz
  Binaries:
    Node: 14.17.4 - /usr/local/bin/node
    Yarn: 3.0.2 - /usr/local/bin/yarn
    npm: 7.21.0 - /usr/local/bin/npm
```

**Comment by paul-soporan** [comment]
`lockfileFilename` was never supposed to allow moving the lockfile to a subfolder (though it wasn't enforced) - notice how it's specifically called `lockfileFilename` and not `lockfilePath` (like the other settings which allow actual paths).

The lockfile is only allowed at the project root because it's used for project detection.

In any case, the `lockfileFilename` setting will be removed starting from 4.x (https://github.com/yarnpkg/berry/pull/5604).
