### ISSUE TITLE
[Feature] Support .yarnrc.yaml

### ISSUE THREAD

**Issue by Kurt-von-Laven** [yarnpkg/berry#3535]
- [ ] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [x] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

Most tools with YAML config files support both .yml and .yaml extensions. Some, such as [pre-commit](https://pre-commit.com/) only support .yaml, while some, such as Yarn, only support .yml. It can be a minor inconvenience to mix .yml and .yaml extensions in the same repository, because some tools (e.g., [jscpd](https://www.npmjs.com/package/jscpd)) are configured on a per-extension basis. When one is using many such tools, it can become easy to omit .yml or .yaml from one of the configurations, particularly if .yarnrc.yml is the only .yml file in a repository.

**Describe the solution you'd like**

Treat a .yarnrc.yaml file the same way you presently treat a .yarnrc.yml file.

**Describe the drawbacks of your solution**

This slightly increases the complexity of configuration file loading, and necessitates that an arbitrary decision be made if both config files are present. My suggestion would be to exit with a helpful error message if both files are present since this is unlikely to be an intentional or desirable state of affairs. Silently choosing one file over the other can lead to confusion when changes to the other configuration file don't have the expected effect.

**Describe alternatives you've considered**

I can't see a meaningful way to implement support for .yarnrc.yaml as a plugin since Yarn itself presently can't do much of anything if .yarnrc.yml is absent. The most compelling alternative would simply be to do nothing and continue to accept the minor inconvenience of inconsistent YAML extensions in some downstream projects.

**Comment by arcanis** [comment]
> This slightly increases the complexity of configuration file loading, and necessitates that an arbitrary decision be made if both config files are present.

I'm seeing that as a significant drawback. Having a single place where the configuration can be helps not only users configuring Yarn, but also us providing support. If we had to ask them to check two places for each folder it'd become really annoying as we'd never be sure they didn't forget one.

**Comment by Kurt-von-Laven** [comment]
@arcanis, [SchemaStore's catalog](https://github.com/SchemaStore/schemastore/blob/31d43a19364287d1d505577d30c6c34d09af5bf1/src/api/json/catalog.json) demonstrates that many projects support multiple config files (e.g., `.yml`, `.yaml`, `.json`).

**Comment by arcanis** [comment]
- `.yml`: [22.2M matches](https://github.com/search?q=path%3A*.yml&type=code&ref=advsearch)
- `.yaml`: [16.3M matches](https://github.com/search?q=path%3A*.yaml&type=code&ref=advsearch)

In any case, perhaps if we were creating Yarn from scratch it'd be `.yaml` from the beginning, but for an existing project there's almost no value in doing so - and significant risks of confusion. I'll close this issue, it's not in our plans.

**Comment by RomainLanz** [comment]
Thank you for your response.

However, I believe this issue deserves another look. The fact that Yarn still uses the `.yml` extension for configuration files, despite the YAML FAQ recommending the use of `.yaml`, doesn't seem to have a strong technical justification. The argument that it "was like that since the start" or that it "can be confusing" is subjective and doesn't provide concrete reasoning for continuing with the outdated naming scheme.

Looking at the numbers, the `.yaml` extension has seen a significant rise in usage, which is entirely expected since it is the recommended naming convention. Continuing to enforce `.yml` may create unnecessary friction for users who prefer the `.yaml` extension, which has become the more widely accepted and standard format.

I would appreciate it if this issue could be reconsidered and potentially reopened, as supporting `.yaml` would align Yarn with best practices.

Thank you for your time!

**Comment by nothub** [comment]
The [FAQ on yaml.org](https://yaml.org/faq.html) states:
> 1. Is there an official extension for YAML files?
> Please use ".yaml" when possible.
