### ISSUE TITLE
[Feature] Support monorepo in monorepo

### ISSUE THREAD

**Issue by MrCheater** [yarnpkg/berry#356]
Now `yarn` does not support different `nohoist` at different levels of monoreps. This is critical when working with react-native.

* my-project  <- monorepo 
  * packages
    * package-a
    * package-b
  * examples
    * my-example <- monorepo in monorepo
      * react-native
      * web

I hope this will change in the future

**Comment by arcanis** [comment]
Because we're not using `node_modules` anymore (and thus don't have any hoisting), Yarn 2 will not support nohoist, which was always a workaround to a more serious problem.

The real solution here would be for RN to have a native compatibility with PnP, which I expect will have to come from the community (I'll be happy to provide context when needed, but I have very little experience on the RN architecture itself).

Refs: https://github.com/facebook/react-native/issues/22163
Refs: https://github.com/react-native-community/cli/issues/27

cc @empyrical, I remember you started evaluating it last year. Do you think it would be worthwhile to make a new case study to figure out what would be needed for RN to work with PnP?

In the meantime I'll be closing this issue for now as we don't have action items related to nohoist.

**Comment by MrCheater** [comment]
Now `react-native` (metro bundler) has big problems finding node_modules outside the root of the react-native application and therefore requires manual configuration. Will react-native (metro bundler) really get PnP support in the future?
