### ISSUE TITLE
[Bug] "Unknown Syntax Error: Command not found" with `yarn workspaces foreach`

### ISSUE THREAD

**Issue by jacobrask** [yarnpkg/berry#364]
**Describe the bug**

`yarn workspaces foreach run build` gives

```
Unknown Syntax Error: Command not found, but we're not sure what's the alternative.
```

**To Reproduce**

`package.json`
```
{
  "name": "workspaces-foreach",
  "version": "1.0.0",
  "private": true,
  "workspaces": ["packages/*"]
}
```

`packages/test-1/package.json`
```
{
  "name": "test-1",
  "version": "1.0.0",
  "script": {
    "build": "build"
  }
}
```

**Environment if relevant (please complete the following information):**

 - OS: OSX
 - Node version: 12.2
 - Yarn version: 2.0.0

**Comment by jacobrask** [comment]
Fixed by running `yarn plugin import @berry/plugin-workspace-tools`. Will add this to https://yarnpkg.github.io/berry/cli/workspaces/foreach

**Comment by jacobrask** [comment]
That was easier said than done sine the documentation is auto-generated though 😕

**Comment by phogel** [comment]
The source of the plugin has changed in the meantime. Instead of @berry/plugin-workspace-tools you can now use
`yarn plugin import @yarnpkg/plugin-workspace-tools`.

**Comment by erodrigufer** [comment]
I was having this same issue, I followed @phogel instructions and the issue was resolved :)

FYI: With Yarn 4 it should be unnecessary to import `@yarnpkg/plugin-workspace-tools` since it should be included per default (see [npm @yarnpkg/plugin-workspace-tools](https://www.npmjs.com/package/@yarnpkg/plugin-workspace-tools#install))
