### ISSUE TITLE
[Feature] make generated docs friendlier

### ISSUE THREAD

**Issue by kidonng** [yarnpkg/berry#3809]
- [ ] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [ ] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

There are currently two generated docs page:

- [`yarn sdks`](https://yarnpkg.com/sdks/cli/default), linked from [Editor SDKs](https://yarnpkg.com/getting-started/editor-sdks#:~:text=found%20on%20the-,dedicated%20page,-.%20Generally%20speaking%3A)
- [`yarn pnpify run`](https://yarnpkg.com/pnpify/cli/run), linked from [PnPify](https://yarnpkg.com/advanced/pnpify/#:~:text=found%20on%20its-,dedicated%20page,-.)

These pages make sense when you are reading the corresponding part of the docs and clicking into it, but not when you find it via search (either the Algolia one on the site or another one like Google). They don't have "context".

The commands in those pages also don't make it clear that corresponding plugins are needed (`@yarnpkg/sdks` or `@yarnpkg/pnpify`), or they are subcommands of `yarn`, i.e. you have to call `yarn sdks vscode vim` instead of `sdks vscode vim`.

**Describe the solution you'd like**

Prefix the page title, commands with `yarn` and mention the needed plugin. A link to where they are mentioned would also be welcome.

**Describe the drawbacks of your solution**

Please tell me 😄

**Describe alternatives you've considered**

N/A

**Comment by paul-soporan** [comment]
> The commands in those pages also don't make it clear that corresponding plugins are needed

Those are not plugins, they are Yarn packages that expose binaries but they aren't related to the CLI itself.

> or they are subcommands of yarn

They aren't subcommands, they are binaries exposed by those packages. Just like any other binary (e.g. `jest`, `eslint`), you can either run them via `yarn dlx`, install them locally and run them via `yarn run`, or install them globally and directly call them.

> Prefix the page title, commands with yarn

I don't think that should happen since they don't require Yarn to work.

> mention the needed plugin

I agree that we should mention the package that exposes them and how they can be run via `dlx` or per-project install & `yarn run`.

> A link to where they are mentioned would also be welcome

Sounds like a good idea :+1:
