### ISSUE TITLE
[Bug?]: yarn link failing with NodeModulesLinker with workspaces

### ISSUE THREAD

**Issue by kldavis4** [yarnpkg/berry#3873]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

I'm running into an issue very similar to #3413 but it appears to be related to workspaces. In this case, I have a workspace project which has a dependency from the linked project and I have a conflicting dependency between the root project and the dependency.

This repo has the reproduction: https://github.com/kldavis4/yarn-link-example

### To reproduce

```
# setup
git clone https://github.com/tinacms/tinacms.git
git clone https://github.com/kldavis4/yarn-link-example
cd tinacms && git checkout 7a5e47394a7e6c59cb7cd5e00358aa7331bd67ad && yarn && cd ..
cd yarn-link-example && yarn

yarn link ../tinacms -rp

➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 252ms
➤ YN0000: ┌ Link step
➤ YN0001: │ Error: Assertion failed: Writing attempt prevented to /path/to/tinacms/packages/@tinacms/graphql/node_modules/fs-extra which is outside project root: /path/to/projects/yarn-link-example
    at $0 (/Users/kldavis/projects/example/.yarn/releases/yarn-3.1.1.cjs:695:1626)
    at Bce (/Users/kldavis/projects/example/.yarn/releases/yarn-3.1.1.cjs:695:2199)
    at T6e (/Users/kldavis/projects/example/.yarn/releases/yarn-3.1.1.cjs:695:6703)
    at yce.finalizeInstall (/Users/kldavis/projects/example/.yarn/releases/yarn-3.1.1.cjs:680:26260)
    at async Ke.linkEverything (/Users/kldavis/projects/example/.yarn/releases/yarn-3.1.1.cjs:441:14966)
    at async /Users/kldavis/projects/example/.yarn/releases/yarn-3.1.1.cjs:444:4329
    at async Fe.startTimerPromise (/Users/kldavis/projects/example/.yarn/releases/yarn-3.1.1.cjs:412:3730)
    at async Ke.install (/Users/kldavis/projects/example/.yarn/releases/yarn-3.1.1.cjs:444:4105)
    at async /Users/kldavis/projects/example/.yarn/releases/yarn-3.1.1.cjs:514:1744
    at async Function.start (/Users/kldavis/projects/example/.yarn/releases/yarn-3.1.1.cjs:412:2287)
➤ YN0000: └ Completed in 0s 306ms
➤ YN0000: Failed with errors in 0s 738ms
```

### Environment

```shell
System:
    OS: macOS 12.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.18.0 - /private/var/folders/_k/hrm7yp1x19ndv337vd1ktq0r0000gn/T/xfs-6a0788e2/node
    Yarn: 3.1.1 - /private/var/folders/_k/hrm7yp1x19ndv337vd1ktq0r0000gn/T/xfs-6a0788e2/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.0/bin/npm
```

**Comment by larixer** [comment]
Thank you for the reproduction @kldavis4. I have examined what happens. The main issue is that the nm linker hoister uses eager approach - it hoists `@tinacms/graphql` from the workspace `foo` into the top-level first. Then it finds itself in the situation when it cannot hoist `fs-extra` from top-level `@tinacms/graphql` into the top-level, because of version conflict with root workspace's `fs-extra`. 

To fix this issue the hoister needs to be aware that the dependency is a portal and make sure the portal will not be hoistable until the point when all of its dependencies were hoisted, this is a medium complexity fix - cannot be done fast during one day and needs time for engineering and tests. It is doable however within timeframe of several days.

I don't see good ways to work around this problem, except the way that you already did by introducing the portal dependency directly to the root workspace to see the diagnostics. This work around is not perfect in the sense that the nm linker could have installed your project without making changes to `fs-extra` versions if the hoisting was not eager. So the best way would be to make the changes to the hoister and fix this class of issues.

**Comment by larixer** [comment]
@kldavis4 I have started to work on the fix at: #3898
So far it installs your repro correctly. To try the Yarn from this pull request use the following command:
`yarn set version from sources --branch 3898`

**Comment by kldavis4** [comment]
> @kldavis4 I have started to work on the fix at #3898 So far it installs your repro correctly. To try Yarn from this pull request - use the following command: `yarn set version from sources --branch 3898`

Thanks @larixer  - I will give that branch a try and report back

**Comment by kldavis4** [comment]
@larixer I have confirmed that everything appears to be working correctly with that branch

**Comment by lehni** [comment]
I have found a related situation that still fails with yarn 3.2.0, and have created a new bug for it: #4179. This used to work with yarn 2.
