### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by eps1lon** [yarnpkg/berry#392]
**Describe the bug**

`yarn version check` fails in a workspace whose dev dependency changed.

**To Reproduce**

```bash repro
$ cd packages/plugin-workspace-tools
$ yarn version prerelease
$ yarn version check
```
**Screenshots**

N/A

**Environment if relevant (please complete the following information):**
* https://github.com/yarnpkg/berry/tree/471fb6b8348f9e65233b36573d4cb23546339a29

**Additional context**

[yarn version check loops through `workspace.dependencies`](https://github.com/yarnpkg/berry/blob/842cd3406305779a9330b3e29ade95eef75ebab6/packages/plugin-version/sources/commands/version/check.ts#L93) which [includes "dependencies + devDependencies + child workspaces"](https://github.com/yarnpkg/berry/blob/5c1906cdbd79d40481ab78745b58f4de1776c103/packages/berry-core/sources/Workspace.ts#L39). If the consumer doesn't install the package than we don't need to bump the dev-dependant.

Aside: This behavior should be downgradable to a warning in general. While it might make sense to bump dependants if dependencies affect the public interface it is not always given that dependencies are part of the public interface. yarn makes very strong claims about how SemVer should be applied and whether those claims are even valid is still [discussed in the SemVer spec repo](https://github.com/semver/semver/issues/341).

**Comment by arcanis** [comment]
> If the consumer doesn't install the package than we don't need to bump the dev-dependant.

But for example bumping `@babel/core` (or `typescript`) means you may need to rebuild and republish the package, so a dev dependency changing needs to be reported.

> yarn makes very strong claims about how SemVer should be applied and whether those claims are even valid is still discussed in the SemVer spec repo.

Yes and no - it merely tells you that you need to decide *something* (whether you should bump it or not really depends on the situation). If you don't wish to bump the dependent when one of its dependencies upgrades, you can just run `yarn version decline` in its directory.

I prefer to keep it an error because it would otherwise be a bit useless for CI purposes, and because the `decline` strategy makes it easily fixable.

**Comment by eps1lon** [comment]
> yarn version decline

Makes sense. I wasn't aware of this that sub-command.
