### ISSUE TITLE
[Bug?]: Resolution priority issue?

### ISSUE THREAD

**Issue by Hideman85** [yarnpkg/berry#3948]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

I have so much issues with my packages version resolution.
In my project I use the tilde ~ notation to avoid undesired updates (I basically accept only patch and the rest need to be manually handled)

I do have then these dependencies:
```js
    "video.js": "~7.17.3",
    "videojs-record": "~4.5.0",
    "videojs-wavesurfer": "~3.8.0",
```

But yarn produce me this:
```js
yarn why video.js
├─ video.js@npm:7.17.3 (via npm:~7.17.3)
│
├─ videojs-record@npm:4.5.0
│  └─ video.js@npm:7.18.0 (via npm:>=7.0.5)
│
└─ videojs-wavesurfer@npm:3.8.0
   └─ video.js@npm:7.18.0 (via npm:>=7.0.5)
```

For me as a user of yarn the rule `>=` is more permisive and the rule `~` specific. As the tilde rule is in respect with the permisive rule it should not select the latest version but the only one required.

### To reproduce

- Init a project with the above deps
- Run `yarn`
- Then `yarn why video.js` 

### Environment

```shell
System:
    OS: Linux 5.13 Ubuntu 21.10 21.10 (Impish Indri)
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 14.18.2 - /tmp/xfs-c758339a/node
    Yarn: 3.1.1 - /tmp/xfs-c758339a/yarn
    npm: 6.14.15 - /usr/bin/npm
```

### Additional context

As a current workaround I have to add lot of resolutions rules to force the version :(

**Comment by arcanis** [comment]
The tilde (and caret) only apply on your own direct dependencies, and have no public-facing impact on how nested dependencies will be resolved. Yarn only guarantees that each package will get the dependencies it asks for, nothing more.

Presumably, if you need to enforce that a single `video.js` version is used, then it should be a peer dependency in both `videojs-record` and `videojs-wavesurfer` (you can fix that with [`packageExtensions`](https://yarnpkg.com/configuration/yarnrc#packageExtensions), although an upstream fix would be ideal).

**Comment by Hideman85** [comment]
Thanks for the quick reply, the thing is that at the end I have more than 20 libs that have the same issues.
So either this is a misunderstanding from the dev community either in some way yarn do not satisfy the expectation (I do not mean this is wrong or good I just facing the reality)
How I can avoid these chaotic version resolution? Should I manually set for everything I use the `resolutions` in my package.json?

**Comment by arcanis** [comment]
> How I can avoid these chaotic version resolution? Should I manually set for everything I use the `resolutions` in my package.json?

As I mentioned, you should probably fix the two plugin packages by turning `video.js` into a peer dependency.

**Comment by Hideman85** [comment]
Your suggestion is not feasible at scale, I do not own the dependencies and I can understand why they have chosen to use deps instead of peardeps since it would be installed at any case.

I think it should be part of the hoisting algorithm, evaluate the ranges and prefer the most precise version. Why this should be strictly the end user to "patch" every libs to fit yarn?

**Comment by arcanis** [comment]
> Why this should be strictly the end user to "patch" every libs to fit yarn?

Because the package manager states the rules and semantics, and packages abide to them, not the other way around.

If packages rely on [undefined behaviours](https://en.wikipedia.org/wiki/Undefined_behavior) (it's fine, it can happen, we all make mistakes), the best thing we can do on our side is to explain both problem and solution (like I did here), but it would be unreasonable to expect us to take responsibility for them and add layers of hotfix and new edge cases. Not only would it be more work for us, but it would also entangle the core rules and would endanger the project stability over the long term.

**Comment by Hideman85** [comment]
I do understand your point and agree at some point we need rules and the community need to follow.
In some cases it is also nice to update the rule according to the community.

If we take the role of a package manager (very simplified) is to gather the right libs versions and try to reduce duplicate libraries.
For that purpose we do have ranges:
- If my deps tree requires `libA >= 1.0.0` and I have a second requirement that is `libA = 1.2.3` why do I have `libA = 1.9.10` installed?
- If I have conflicting versions of course the resolution would be install the last version of the two conflicting areas

If I have a look to similar package manager and for example I take `apt` for linux system libraries it does the exact thing and even throw a version conflict error when we do have conflicting versions that are not available anymore.

To the last point, this is not a edge case because a lot of libraries prefer to use dependencies rather perrDependencies because the end user could only install the lib and get all the needed deps. In comparison of peerDeps that needs to be explicitely added.
Plus in term of logic peerDeps are more optional/soft dep like "if you have this lib we gonna work with but if you don't, we use something else'

**Comment by Hideman85** [comment]
Maybe I need to transform that as a feature request and be evaluated by more than 2 person.
Where can I submit a improvment of yarn that will be judged by more peers?

**Comment by arcanis** [comment]
> If my deps tree requires `libA >= 1.0.0` and I have a second requirement that is `libA = 1.2.3` why do I have `libA = 1.9.10` installed? If I have conflicting versions of course the resolution would be install the last version of the two conflicting areas

There are two things at play here. Let's use the [rfc2119](https://datatracker.ietf.org/doc/html/rfc2119) as terminology.

- A package manager **must** provide a dependency version compatible with what it's parent requests. This isn't optional, this is part of the contract.
- A package manager **should** provide consistent rules around how packages are resolved. By that I mean, a human should, assuming they know the specific rules around resolution, be able to mostly run it in their head.
- A package manager **may** apply specific optimizations to the resolution. For example, if it sees that something requires `^1.0.0` and something else requires `^1.1.0`, it may decide to only resolve `^1.1.0` since it'll cover both.

What you're suggesting goes into the third section. And what's important is that this last part is a **may**. As a result, we are free not to do it (and in this particular case we don't, because it would goes against the second point by making the resolution behavior less consistent), and as a result you **must not** rely on it, period.

> Where can I submit a improvment of yarn that will be judged by more peers?

Feel free to open an enhancement request here, but alternatively you can agree that after five years maintaining Yarn I have a good idea how package managers must work, should work, and may work, and take my word for granted 🙂

**Comment by Hideman85** [comment]
I do not say you are incompetent don't take it this way and even your explanations are really clear :wink: 

I agree it is part of the **may** then that mean it could be included only if it have a real user impact (meaning not only me :smile:)

Then since I cannot rely on the yarn resolution to solve my issue I **must** duplicate my deps into the `resolutions` section to force yarn behave like needed. I hope a day that would change.

**Comment by larixer** [comment]
Note, I am, as a member of Yarn team, would rather like the questions like this, which are brought up way too often here rather be peer-reviewed and voted as per our governance model:
https://github.com/yarnpkg/berry/blob/master/GOVERNANCE.md

While the voting process is formally defined in our governance model, it has not been practiced yet and this question is a good example because the opinion on it is certainly not unanimous.

**Comment by Hideman85** [comment]
I think it could be a good exercise but it mean to be properly formulated then and maybe like a rfc model.
How the versions should be resolve?
How do we match ranges?
What could be the resolution priority? (less to more precise?)
What to do in case of conflict? User interactive resolution?
etc

I don't think I have the time right now to produce that kind of documentation right now. In the end I just wanted to know why yarn behave like this specifically that video.js v7.18 is the next branch so I really don't understand why it gets resolved in place of my explicit version.

Personally I really like yarn it has solved my time on lot of point where npm remains worse. I even tried out more recent project like pnpm but they face the same issues. And for the end user this is really causing issue to have multiple package version, then this is up to the bundler to eleminate when possible thsese duplicata and there to this is like a patch of wrong version resolution.

I also know that this is not an easy probleme and lot of research has been made on the subject but if I can site one other project is `apt` I having rarely version conflict and most of the time it is either the lib do not have the right range or either I don't have the right ppa.

**Comment by merceyz** [comment]
> In the end I just wanted to know why yarn behave like this specifically that video.js v7.18 is the next branch so I really don't understand why it gets resolved in place of my explicit version.

The tag isn't used in this case so the fact that `next` points to `7.18.0` doesn't matter. Yarn follows semver and resolve `>=7.0.5` to the highest satisfying version which at the time of writing is `7.18.0`.

**Comment by paztis** [comment]
I reopen this thread as it is not really clear

I was yesterday on yarn 4.7 and switch to yarn 4.10.3

I have a module that has deps to 
```
"@type/react": "~19.1.0",
"react-intl": "~7.1.11",
```


react-intl has dept to
```
"@types/react": "16 || 17 || 18 || 19",
```

in yarn 4.7, I was installing an have a unique version at the root level that was *19.1.9*
in yarn 4.10.3 I have now *19.1.9* at the root level, and *19.2.2* under *react-intl/node_modules*

And this is really blocking because nothing compiles because of it

I want to understand the reason of it (mainly why it change recently)
Forcing resolution is not a solution
Upgrading the version of my package is also not a solution (I talk about maintenance of customer packages, nothing new has been released (react or react-intl), just the version of yarn)

Thanks

**Comment by arcanis** [comment]
Nothing changed, it's just like I explained [here](https://github.com/yarnpkg/berry/issues/3948#issuecomment-1006514951): when it comes to the `dependencies` field, package managers ONLY guarantee that each dependency will be assigned a version that matches the provided range. They don't guarantee **anything else,** including that it'd would be resolved to the same version as any other dependency range. It may happen, it may not. And since it's not guaranteed, no one should rely on that **optional optimization** to happen (otherwise it's [undefined behaviour](https://en.wikipedia.org/wiki/Undefined_behavior)).

Dependencies that must share the exact same version & package instance as other packages in the dependency graph shouldn't be declared through the `dependencies` field, it's not intended for that. They should use `peerDependencies` instead, which guarantees as part of its contract that the version will be the exact same one as the parent.

**Comment by paztis** [comment]
Tks. I create them a defect.
Let see their response

**Comment by arcanis** [comment]
It's unfortunately a very common issue in the ecosystem. For a while the DefinitelyTyped repository was forbidding peer dependencies in their types. They merged [more nuanced guidelines](https://github.com/DefinitelyTyped/DefinitelyTyped?tab=readme-ov-file#peer-dependencies) a year ago, but it'll take time for the ecosystem to take notice, especially given that some library maintainers won't be keen on fixing that outside of a major.

In the meantime, you can use [`packageExtensions`](https://yarnpkg.com/migration/pnp#fix-dependencies-with-packageextensions) to fix the missing peer dependencies.

**Comment by paztis** [comment]
Yes its a good idea, but it will not allow to remove their bad dependency
field.

**Comment by arcanis** [comment]
Yes and no. If there's both a normal dependency and a peer dependency, the peer dependency takes precedence and the dependency is only considered if the parent package didn't fulfill the peer dep. Acting kinda like a default value.

**Comment by larixer** [comment]
> If there's both a normal dependency and a peer dependency, the peer dependency takes precedence and the dependency is only considered if the parent package didn't fulfill the peer dep.

This is not true for all the package managers; it is true for Yarn Modern only. The `pnpm` has Yarn 1.x peer dependencies semantics. Yarn 1.x peer dependency semantics is also different from Yarn Modern. The `npm` peer dep semantics is different from Yarn 1.x and Yarn Modern, etc, etc. What we really have is a big mess from the very beginning, and to this day. There are multiple package managers, all having their own rules that only partially match. The situation is not too bad; you, as an author of a library, can still find a solution if you test your library with each package manager. But it is far from perfect. Many things need to be standardized across the package managers, starting from the peer dependencies semantics. It is difficult, though, and no one really wants to get out of their way to agree on semantic definitions, because it will lead to endless arguing.

**Comment by arcanis** [comment]
I think pnpm implemented it as well, see https://github.com/pnpm/pnpm/issues/5041. Most of the time we tend to find common grounds with pnpm on this kind of subjects (edit: [and perhaps npm as well](https://github.com/npm/arborist/commit/b0997c91083f1ebd1c4e8d4e996b7aa5e4c39ad2)? didn't test it).

**Comment by larixer** [comment]
I wish all package managers implemented peer dependencies with defaults. I think it's not the case for the `npm`, however. As far as I remember, they implemented it the way that when they see both `peer dep` and normal `dep`, they just treat it as `peer dep`, and that's it. I wish someone would prove that I'm wrong.
