### ISSUE TITLE
[Feature] Eslint plugin and preset for helping maintainers support pnp

### ISSUE THREAD

**Issue by willgriffiths** [yarnpkg/berry#438]
- [x] I'd be willing to implement this feature (I won't get to it for a little while. So if you want to implement then go for it :) )
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

 "I'm a maintainer of a third-party project; I'd like to support PnP but I can't use it right now. How can I make sure that at the very least my project won't break for users that do use it?"

**Describe the solution you'd like**

We could ship an eslint plugin + preset that would check that the project will work with the PnP rules.

Rules:
- Forbid the use of extraneous packages [(no-extraneous-dependencies)](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-extraneous-dependencies.md) 
- Ensure imports point to a file/module that can be resolved. [(no-unresolved)](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-unresolved.md)
- Add a rule that would warn for any string literal containing node_modules + something. This likely a sign that the package is doing shady things with node_modules which would likely fail under PnP
- And a rule to warn for unmet peer dependencies. For example you depend on babel-plugin-something, but you forgot to add @babel/core to your deps. (Not sure which file to attach peer dependencies to.)
- Add a rule to prevent "unqualified" loader name resolution. For warning third-party tools (CRA, Next, Vue-Cli, ...) when they reference a loader through their simple name rather than an absolute path. This is to guard against webpack frameworks that forget to call require.resolve when configuring their plugins. It's a stop gap measure to prevent this [issue](https://github.com/webpack/webpack/issues/9648).

**Describe the drawbacks of your solution**

- Packages with multiple entry points might not be linted correctly
- Not as nice of a user experience without autofix
- Re: the no-extraneous-dependencies.md rule, modules have to be installed for this rule to work. 
 And monorepos require extra configuration.
- Re: the no-unresolved.md rule, if you're using a module bundler other than Node or Webpack, you may end up with a lot of false positive reports of missing dependencies. 

**Describe alternatives you've considered**

- A package along the lines of [pkg-ok](https://github.com/typicode/pkg-ok) but this is more complicated and less user friendly than an eslint plugin.
- Tool/bot that makes a pr automatically against a broken repo that adds the missing dependencies. Too complicated and difficult to implement because "true fixes" depend on how the project is architectured, so only maintainers/contributors would really know how to fix it.

**Additional context** 

Ideas for the future: 
- Make those rules autofixable (by modifying the package.json)
- Ship the plugin + eslint itself under a standalone package. This way maintainers would just have to run yarn dlx @yarnpkg/pnp-check --fix to fix the problems in their repo
- From the user-side, when adding a package that doesn't support pnp, it be nice for missing dependency and other errors to be more visually friendly (colors) and possibly link to a page that explains these intricacies in more details

**Comment by arcanis** [comment]
I really really like this idea 👍 Could be the missing link to a wider PnP adoption if we do it right!

**Comment by willgriffiths** [comment]
@eps1lon regarding your comment in #445:
  
[no-extraneous-dependencies](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-extraneous-dependencies.md)
> This rule supports the following options:
> 
> devDependencies: If set to false, then the rule will show an error when devDependencies are imported. Defaults to true.

This will be enough to catch it, right? :)

**Comment by arcanis** [comment]
Hey! I've worked a bit on this - for simplicity (I wanted to have TypeScript support out of the box) I went with the following alternative:

> A package along the lines of pkg-ok but this is more complicated and less user friendly than an eslint plugin.

So it's not an eslint plugin after all. On the plus side, it gives us a bit of flexibility regarding performances and makes it easier to lint the `package.json` files.

I've just managed to publish my work on the registry under the name `@yarnpkg/check` (it was a pain because I had to fix the repository so that plugins would also get published, so that the check tool could depend on the Yarn core itself to fetch dependencies, so that we could validate peer dependencies). Now it works!

If you run it in a directory, it'll for now report three types of errors: undeclared dependencies, unmet peer dependencies, and unqualified loader references. For example, running it on `packages/yarnpkg-check/fixtures` yields the following report:

![image](https://user-images.githubusercontent.com/1037931/69095440-5afd4380-0a20-11ea-81c0-f6df701ae27f.png)

At the moment one rule is missing, it's the following:

> Add a rule that would warn for any string literal containing node_modules + something. This likely a sign that the package is doing shady things with node_modules which would likely fail under PnP

Would you like to try your hand at implementing it, @willgriffiths? After that we can think of ways to optimize the processing - it's likely many things can be made parallel, etc. At the moment the biggest issue I'm aware of are git dependencies, which are very slow to install since we need to install their own dependencies, then build the packages, etc (probably something we should improve in stock Yarn).

**Comment by willgriffiths** [comment]
Sure thing, I'll have a go at implementing the rule. :)

**Comment by merceyz** [comment]
I'll close this as implemented in `@yarnpkg/doctor`

> Add a rule that would warn for any string literal containing node_modules + something. This likely a sign that the package is doing shady things with node_modules which would likely fail under PnP

We have that rule now :+1:
