### ISSUE TITLE
[Bug?]: (PnP) VSCode doesn't have "Select Workspace Version" for "Select TypeScript Version"

### ISSUE THREAD

**Issue by ts-web** [yarnpkg/berry#4788]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

I'm setting up a fresh monorepo with yarn 2 and pnp. When I run `TypeScript: Select TypeScript Version`, there is no `Use Workspace Version` option, only `Use VS Code's version`.

vscode version:
```
$ code -v
1.70.2
e4503b30fc78200f846c62cf8091b76ff5547662
x64
```

### To reproduce

This involves VSCode so I don't think a sherlock repro can capture it.

Please advise on what kind of repro information you need for this kind of bug. I assume you can just fire up vscode for any yarn 2 repo and see if it works. If this issue is not reproducible that way, then should I create a repo to check out? 

### Environment

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
  Binaries:
    Node: 16.15.0 - /tmp/xfs-0b2c64a2/node
    Yarn: 3.2.2 - /tmp/xfs-0b2c64a2/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
```

### Additional context

![Screenshot from 2022-08-22 13-44-12](https://user-images.githubusercontent.com/1311744/185986994-5533d5ad-e56e-4b8d-9423-aed10642a36e.png)

**Comment by wegry** [comment]
Which version of typescript is this occurring with? There may not be a yarn patch for `typescript@rc` (4.8) yet.

**Comment by merceyz** [comment]
Based on your screenshot you haven't opened VSCode on the folder itself so VSCode doesn't see the `.vscode` folder to get the workspace version from.

**Comment by ts-web** [comment]
@wegry it looks like I'm using typescript `4.7.4`. I don't recall installing an rc.

@merceyz I'm afraid I don't understand. In the screenshot VSCode has the `pebble` folder open and there is `pebble/.vscode`. Do I need to save a VSCode workspace?

**Comment by thealjey** [comment]
@merceyz I'm experiencing the same thing
just setting up a new project like it is described on the website
```
corepack enable
yarn init -2
yarn install
yarn dlx @yarnpkg/sdks vscode
```
then I go to "Select TypeScript Version", like instructed
and "Use Workspace Version" is not on the list of the available options
the only thing I see in the sdks folder is an `integrations.yml` file with:
```
integrations:
  - vscode
```
I'm using the latest versions of vscode and node

**Comment by merceyz** [comment]
@thealjey You need to install `typescript` first, see https://yarnpkg.com/getting-started/editor-sdks/#tools-currently-supported

> @merceyz I'm afraid I don't understand. In the screenshot VSCode has the pebble folder open and there is pebble/.vscode. Do I need to save a VSCode workspace?

You need to open VSCode in the folder itself, not its parent, i.e. `code ./pebble`.

> and there is pebble/.vscode

VSCode only looks for `./.vscode` so it doesn't see that folder

**Comment by ottoborden** [comment]
I'm having the same issue. I tried `code .` from the project's root directory (the same where .vscode) is with no luck. TS -v 4.8.4. I followed the instructions on the website as closely as I could.

**Comment by eranikid** [comment]
I've stumbled upon the same issue, turns out it was because I didn't have `typescript` explicitly listed as a dependency in a `package.json`

**Comment by hadynz** [comment]
> I've stumbled upon the same issue, turns out it was because I didn't have `typescript` explicitly listed as a dependency in a `package.json`

Expanding further on the above answer.

If you have a monorepo setup (i.e. using yarn's workspaces feature), then you need to ensure that `typescript` is installed as a dev dependency (`yarn add -D typescript`) in the **root directory** of the monorepo. So it may look like:

```
{
  "name": "mono-repo-package",
  "packageManager": "yarn@3.6.1",
  "workspaces": [
    "packages/*"
  ],
  "devDependencies": {
    "typescript": "^5.1.6"
  }
}
```

**Comment by ndrewtl** [comment]
I've done all that's listed above-- installed the VSCode SDK, added typescript as a devDependency, opened the parent folder. And I still can't enable the workspace typescript version.

**Comment by KaugaKauga** [comment]
> I've stumbled upon the same issue, turns out it was because I didn't have `typescript` explicitly listed as a dependency in a `package.json`

Adding typescript as dev dependency at root level and running `yarn dlx @yarnpkg/sdks vscode` allowed me to select workspace version of typescript and got VSCode to work 👍

**Comment by edwarddoh** [comment]
In my case, I was able to make it work by removing target directory out of workspace and re-add it.

**Comment by enlguy** [comment]
I don't even get a .vscode folder with my Nextjs project.  Typescript is installed.  It's always worked.  For the past week or so, it's throwing a TON of errors in VS Code on almost every file, for things that should not be flagged.  No option to get Workspace version like above.  I have Typescript ^5 installed.  Is this a bug with the newest version?  Never had this happen before a matter of days ago.  It's now screwing up every single project I'm working on.  I don't know if I have to delete typescript from everything, or if this will be fixed...

**Comment by neoncube2** [comment]
I spent a few hours today trying to figure out why this wasn't working, and @merceyz's answer saved me! (Thank you! :D)

First off: Yes, you do need to first run these commands, in this order: 
1. `yarn add -D typescript`
2. `yarn dlx @yarnpkg/sdks vscode`

(If you also want `prettier`, etc. to work, you also need to install them before running `yarn dlx @yarnpkg/sdks vscode``)

When you just open a single file in VSCode, it doesn't check to see if the file is part of a project, and therefore it doesn't detect that there's a custom version of TypeScript.

For example, let's say that your code looks like this, and you open `index.js`. VSCode doesn't detect the `.vscode` folder, where the custom version of TypeScript is, because we're just opening a single file:

![Image](https://github.com/user-attachments/assets/c13394e9-34c0-4a2c-83d8-50136107d8fb)

In order to get VSCode to recognize yarn's custom TypeScript version, we need to have VSCode open our project's _entire folder_.

There are two ways to do this:
1. Open the command prompt in your project's root directory and run `code .`:
![Image](https://github.com/user-attachments/assets/ef064f83-50ef-4095-87ca-918e7e4e3fd3)
2. Open VSCode, click File -> Open Folder, select the root folder in your project, and click "Open":
![Image](https://github.com/user-attachments/assets/a531da98-e88f-4185-ada2-f1877ed212b4)
![Image](https://github.com/user-attachments/assets/4647d323-d583-4d58-9d0e-31f100ee6b8f)

VSCode should now look something like this:
![Image](https://github.com/user-attachments/assets/f6dd195e-2f91-4c37-a02d-c4227cb94a48)

After opening our project as a folder, you must first open a TypeScript (`.ts)` or JavaScript (`.js`) file, then press `Ctrl + Shift + P`, type "Select Typescript Version", and choose "User Workspace Version". If you don't find open a `.ts` or `.js` file, the "Select Typescript Version" setting doesn't show up when it's searched for.
