### ISSUE TITLE
[Feature] Support `rm` in shell

### ISSUE THREAD

**Issue by brc-dd** [yarnpkg/berry#4833]
- [x] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [ ] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

Mostly people have to write some script like `rimraf dist` to clean up things (say before build). (rimraf has like over 60M downloads per week, so there are really lot of people using it for a cross-platform `rm -rf`)

**Describe the solution you'd like**

It would be great if `rm` command can be supported in `@yarnpkg/shell`, allowing users to write cross-platform scripts without any extra package.

**Comment by paul-soporan** [comment]
Personally, I'm against reimplementing Posix utilities in the shell.

The only commands we currently implement are shell builtins (except for `sleep` which perhaps shouldn't have been implemented in the first place). 

Posix builtins are very complex and we'd have to reimplement all of their flags and all of their quirks in cross-platform ways, which would be a lot of unneeded complexity, since all scripts already have access to cross-platform `fs` APIs through `node`.

> allowing users to write cross-platform scripts without any extra package.

You can already do that in all versions supported by Yarn 4 using:
```sh
node -e "fs.rmSync('dist', {recursive: true, force: true})"
```
