### ISSUE TITLE
require local packages with canvas, very long installation time comparing to npm

### ISSUE THREAD

**Issue by dallmo** [yarnpkg/berry#5037]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

wrote a local package A which requires [canvas](https://www.npmjs.com/package/canvas).
wrote another local package B which requires local package A.

if package B is managed by npm, takes only 3 seconds for initial install, and less than 1 second for re-installation ( when updating package A ) ; 

if package B is managed by yarn, takes more than 3 minutes for initial install, and more than 1 minutes for re-installation.

whether package A is managed by npm / yarn made no difference.

### To reproduce

```
git clone git@gitlab.com:dallmo.com/tmp/canvas-test.git
```

do installation in the folder "package-A" ; 
then do the installation in folder "package-B" ; 

### Environment

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (4) x64 Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz
  Binaries:
    Node: 18.9.1 - /tmp/xfs-510e7821/node
    Yarn: 3.2.4 - /tmp/xfs-510e7821/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v18.9.1/bin/npm

in terms of node version, sames result on the same system with : 
"Node: 16.4.2 - /tmp/xfs-7d1d0e6f/node"

---

also tested with another system with : 
  System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (2) x64 Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
  Binaries:
    Node: 18.7.0 - /tmp/xfs-b8bda0c3/node
    Yarn: 3.2.4 - /tmp/xfs-b8bda0c3/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v18.7.0/bin/npm
```

**Comment by merceyz** [comment]
This is happening because Yarn and npm treat `../package-A` differently, npm essentially just creates a symlink while Yarn packs the entire target folder and copies it into the cache to install it.

If you want the same behaviour from Yarn change it to `link:../package-A`, if you want it to resolve dependencies as well use `portal:../package-A`.

https://yarnpkg.com/features/protocols/#whats-the-difference-between-link-and-portal
