### ISSUE TITLE
[Bug?]: `yarn pack` the date on files

### ISSUE THREAD

**Issue by yarinsa** [yarnpkg/berry#5047]
### Self-service

- [X] I'd be willing to implement a fix

### Describe the bug

We are running `yarn pack` and publishing the packages using a in-house script
(yarn npm publish doesn't work with jFrog for some reason). 
Then this .tgz is pulled from the artifactory, unpacked and deployed to s3. 
s3 have a behavior where older files won't be uploaded.
After checking why our versions were not get deployed we found out that `yarn pack` command reset the date on the file to 

### To reproduce

1. running ls -l before packing:
<img width="589" alt="Screen Shot 2022-11-10 at 13 26 39" src="https://user-images.githubusercontent.com/44482362/201079465-7c024d6b-2002-4391-b415-fb631ed9623b.png">

2. running `yarn pack` -> creates a package.tgz
3. Unpacking packages.tgz -> package
4. Running `ls -l package` 
<img width="658" alt="Screen Shot 2022-11-10 at 13 27 49" src="https://user-images.githubusercontent.com/44482362/201079680-db376848-ea2e-4872-b1af-e36e5e849dcc.png">

<img width="583" alt="Screen Shot 2022-11-10 at 13 30 56" src="https://user-images.githubusercontent.com/44482362/201079971-7c231b3d-54fa-46c5-b98c-8028d1538687.png">

### Environment

```shell
System:
    OS: macOS 12.6
    CPU: (8) x64 Apple M1 Pro
  Binaries:
    Node: 18.11.0 - /private/var/folders/n_/c3nqmfn54qnbtq0zgvvcvh4r0000gp/T/xfs-8246237e/node
    Yarn: 3.2.2 - /private/var/folders/n_/c3nqmfn54qnbtq0zgvvcvh4r0000gp/T/xfs-8246237e/yarn
    npm: 8.19.2 - /usr/local/bin/npm
```

**Comment by arcanis** [comment]
This is the expected behaviour: Yarn guarantees that calling `yarn pack` multiple times on the same package will always yield the same result. This is important when for example installing dependencies from Git, as otherwise the checksums would always fluctuate. To this end, Yarn normalizes all the file times (and chmod, iirc) to standardized values.

I'd check whether AWS allows you to disable this time check.
