### ISSUE TITLE
[Bug] Yarn does not build modules without install script

### ISSUE THREAD

**Issue by Embraser01** [yarnpkg/berry#51]
**Describe the bug**

Some packages does not set an `install` script in there `package.json` even if they have to build a native module.

I tried to use https://github.com/ranisalt/node-argon2, but no `argon2.node` file was created at installation.

It's because their `pacakge.json` does not contain any information about building the module.

It currently works with npm or yarn because they check if the project contain a `binding.gyp` and create a `install` script if needed:

https://github.com/yarnpkg/yarn/blob/b409261b76f3a6506d7dc9e627a49eb02ef170c5/src/util/normalize-manifest/fix.js#L182-L186

**To Reproduce**

You can clone this repo https://github.com/Embraser01/scratch-repo and run `yarn start`.

**Screenshots**

Error when starting the script.

![image](https://user-images.githubusercontent.com/8802277/55359007-1cd30400-54d1-11e9-9ce5-7ffe26c6c25d.png)

**Environment if relevant (please complete the following information):**

 - OS: Windows
 - Node version 11
 - Yarn version latest available

**Additional context**

I also unplugged the package to be sure it wasn't related to the zip system...

It's not really a bug but will prevent an easy migration from Yarn V1

**Comment by arcanis** [comment]
Which build scripts should be run is decided here:

https://github.com/yarnpkg/berry/blob/master/packages/plugin-pnp/sources/PnpLinker.ts#L69-L110

The problem is that while we could add a new script to the build definition if we notice a `bindings.gyp` file, there is no script that we could actually run - we would need to generate one on the fly, which we can't do in this oart of the code 🤔 

An alternative would be to hydrate the missing script in [`Manifest.loadFile`](https://github.com/yarnpkg/berry/blob/master/packages/berry-core/sources/Manifest.ts#L60-L65), but I don't like this too much as it would introduce a big special case at the wrong place (what if we call `load` directly, without going through `loadFile`?).

Something I was considering some time ago was that maybe we should have a [hook](https://github.com/yarnpkg/berry/blob/master/packages/berry-core/sources/Plugin.ts#L19-L39) that allows plugins to extend manifests based on the packages that own them. The main use case I had in mind was to allow for plugins to hydrate the Manifest class based on any type of format. It was a bit heavy so I didn't pursue it further ...

**Comment by arcanis** [comment]
Thinking about it, the best would likely be to make build directives more powerful so that something like this would become possible. I doubt it's the only time we'll need this kind of capabilities:

```js
return {
      packageLocation,
      buildDirective: [
        [BuildDirective.SCRIPT, `preinstall`],
        [BuildDirective.SCRIPT, `install`],
        [BuildDirective.SHELLCODE, `node-gyp`],
        [BuildDirective.SCRIPT, `postinstall`],
      ],
};
```

That would be implemented in the `Project` class, like here:

https://github.com/yarnpkg/berry/blob/master/packages/berry-core/sources/Project.ts#L1051-L1075

Would you like to take a shot at it, @Embraser01? I think what would need to be done:

  - Implement the `BuildDirective` enumeration
  - Implement a new `executePackageShellcode` / `executeWorkspaceShellcode`
      - The `executePackageScript` and `executeWorkspaceScript` function would probably have to be refactored so that they would call those new methods (to avoid duplicating code)
  - Turn `buildDirective` into an array of tuple, and call the right action based on the enumeration
  - And of course return the build directive for `node-gyp` if the package has no build script but happens to contain a `bindings.gyp` file.

**Comment by Embraser01** [comment]
Good idea!

I'll will start working on it asap (I'll open a Draft PR as soon as I've got something).

I'll ping you if I've any questions :wink:
