### ISSUE TITLE
[Bug?]: berry-cli/bin/berry.js 3.3.0 not 3.3.1 (latest)

### ISSUE THREAD

**Issue by rawfg** [yarnpkg/berry#5191]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

There was a fix for the [TS 4.9.4 bug](https://github.com/yarnpkg/berry/issues/5125) with the [3.3.1 release](https://github.com/yarnpkg/berry/releases/tag/%40yarnpkg%2Fcli%2F3.3.1)  but the https://github.com/yarnpkg/berry/blob/master/packages/berry-cli/bin/berry.js contains version `3.3.0`. 

As I work in the enterprise environment our access is limited to this particular URL to download latest Yarn Berry version.

### To reproduce

- goto https://github.com/yarnpkg/berry/blob/master/packages/berry-cli/bin/berry.js
- tthe location contains previous version 3.3.0 not the latest one 3.3.1

### Environment

```shell
System:
    OS: Linux 5.10 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
  Binaries:
    Node: 18.5.0 - /tmp/xfs-696d0a64/node
    Yarn: 3.3.1 - /tmp/xfs-696d0a64/yarn
    npm: 8.12.1 - ~/.nvm/versions/node/v18.5.0/bin/npm

Irrelevant here.
```

**Comment by arcanis** [comment]
I updated the checked-in file; not sure how it happened though, since [the script is supposed to make a `cp`](https://github.com/yarnpkg/berry/blob/master/scripts/release/01-release-tags.sh#L71-L73), and the command in run to forward the `bin` update to the master branch [is supposed to cover `berry-cli`](https://github.com/yarnpkg/berry/blob/mael/stable-release-workflow/.github/workflows/release-branch.yml#L65) 🤔
