### ISSUE TITLE
[Bug?]: Some pakage is missing from the website

### ISSUE THREAD

**Issue by NaufalF22** [yarnpkg/berry#5579]
### Self-service

- [X] I'd be willing to implement a fix

### Describe the bug

So i want to install vscodium on arch and when its time to install yarn they produce 404 error

### To reproduce

Install vscodium like usual on cli

yay -S vscodium

### Environment

```shell
Os = Arch linux
CPU = AMD Ryzen 5 3500u
```

### Additional context

![image](https://github.com/yarnpkg/berry/assets/63091744/e10245d9-4716-4ca3-ba88-c65f04e471df)

**Comment by geemus** [comment]
FWIW, I'm also seeing very similar behavior for these:
- https://registry.yarnpkg.com/@esbuild/darwin-x64/-/darwin-x64-0.18.11.tgz:
- https://registry.yarnpkg.com/@stoplight/spectral-ruleset-bundler/-/spectral-ruleset-bundler-1.5.1.tgz:

Looking at the esbuilds page (https://yarnpkg.com/package/esbuild), the latest version that is available appears to be about 4 months out of date, with the newer versions (which one can see on github or npm) missing.

**Comment by quinnjn** [comment]
npm updated their incident page: https://status.npmjs.org/incidents/jglnklhspsnm

package publish/install impacted
This incident affects: www.npmjs.com website, Package installation, and Package publishing.

I'm not to sure how registery.yarnpkg.com works but if it acts like a proxy the issue is probably on npm's side.

**Comment by merceyz** [comment]
See https://yarnpkg.com/getting-started/qa/#queries-to-registryyarnpkgcom-return-a-404500-is-it-down
