### ISSUE TITLE
[Feature] Use ky-universal instead of got

### ISSUE THREAD

**Issue by willemneal** [yarnpkg/berry#562]
- [X] I'd be willing to implement this feature

**Describe the user story**

I'm trying to move yarn into the browser and one issue is that the http request library got is node only.

**Describe the solution you'd like**
Use [ky-universal](https://github.com/sindresorhus/ky-universal) which works in both a browser and node context.

**Describe the drawbacks of your solution**

Size of installation and perhaps performance issues for node.

**Describe alternatives you've considered**

Adding a separate httpUtil for browser context.  However, it would be better for core functionality to work in both contexts.

**Comment by arcanis** [comment]
We don't have super high need at the moment in term of http support so I guess it should be fine, however I'm curious about the following note:

> If you only target Node.js, I would strongly recommend using Got instead.

Any idea why's that? Will it impact us negatively?

**Comment by willemneal** [comment]
I assume that it less performant than Got since it has to support both.  Perhaps the better solution would be to abstract http request in the core and then the default plugin uses Got.

**Comment by arcanis** [comment]
And what about polyfilling `http` and `https` for the browser with something like https://github.com/browserify/http-browserify? Maybe that would be a reasonable indirection, since anything we use will eventually use it underneath 🤔

Btw, do you have details on this Yarn-in-the-browser experiment? I'd be super curious to see what it would look like, especially for when we write artifacts on the disk. Do you generate them to an in-memory filesystem?

**Comment by arcanis** [comment]
Going to close this issue as I think for now we will keep using `got`. Things are working pretty well, so no need to make a change at the moment.
