### ISSUE TITLE
[Feature] Help devs to migrate to pnpm. 

### ISSUE THREAD

**Issue by chakAs3** [yarnpkg/berry#5671]
- [ ] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [ ] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

As a developer, I often  run into frustration and stress just looking into yarn.lock. spend more time to solve yarn issues instead of fixing the product issue 

**Describe the solution you'd like**

Just help devs to move their legacy projects to pnpm, it is really like.

**Comment by arcanis** [comment]
I won't block you from the org because I have good prior experience with the Storybook team, but I'd expect a better behavior from someone familiar with the dynamics of popular open-source projects.

Since it needs to be clearly spelled out:

- Posting trolls on an open-source project's issue tracker is the **absolute** wrong way to engage with a community.

- If you have a problem, assume good intent, explain the _exact_ issue, and optionally suggest a production solution.

- While using our competitors to demonstrate specific things we could do better is perfectly fine, messages like yours just make you look short-sighted.

If you want your issue to be fixed, open a new issue following these rules.

**Comment by larixer** [comment]
I'd like to add on the topic of why the proposed solution to "help devs to move their legacy projects to pnpm" is not good. This solution imposes restriction on us, the people who use and develop Yarn, caused by your preference, it limits our liberty, which is not acceptable, because we are free people and we respect liberty of others and ourselves.
