### ISSUE TITLE
[Bug?]: `enableGlobalCache: false` + `nmMode: hardlinks-global` does not hardlink to `cacheFolder`

### ISSUE THREAD

**Issue by polarathene** [yarnpkg/berry#5745]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Possibly a misunderstanding from what docs imply.

Should `cacheFolder` with `enableGlobalCache: false` be ignored by `nmMode: hardlinks-global`? (_which still creates hard links to `globalFolder` cache_)

---

I have been experimenting with different yarn 3.x config options within a Docker container, where the `package.json` exists in a volume mount.

That introduces a boundary, so:
- `enableGlobalCache: true` + `nmMode: hardlinks-global` => Hardlinks cannot cross boundary, terminal output notifies that `nmMode` was downgraded to `hardlinks-local`. No local yarn cache folder, non-issue.
- `enableGlobalCache: false` + `nmMode: hardlinks-global` => If the `yarn install` _did not have the boundary restriction_, this will **still link to the global cache**, not the project/local cache folder populated instead (_which may be irrelevant since the global cache would have that same content_).

Additionally:
- `hardlinks-local` has different semantics and is not to be confused with a projects `cacheFolder` (_I initially mixed the two modes with hardlinks to the local or global cache_).
- `enableGlobalCache: false` will still populate the global cache, which is understandable. While the project maintains a separate cache location that is pruned to only relevant dependencies. As `cacheFolder` is not considered for `hardlinks-global`, despite being in the same filesystem/mount boundary you end up with a fair amount of duplicated storage (`compressionLevel: 0`).

Some additional clarification in the docs might be useful if this is not a bug?

Semi-related: https://github.com/yarnpkg/berry/issues/2483

### To reproduce

`yarn install` with any `package.json` that has dependencies should work.
- `node_modules` will hardlink to global cache if there is no separate boundary downgrading to `hardlinks-local`. Easily reproducible with a Docker container and a volume mount.
- `.yarn/cache` is populated but has no hardlinks shared with `node_modules`.

---

`.yarnrc.yml`:
```yaml
compressionLevel: 0
enableGlobalCache: false
nodeLinker: "node-modules"
nmMode: "hardlinks-global"
```

`package.json`:
```json
{
  "name": "example",
  "packageManager": "yarn@3.6.3",
  "dependencies": {
    "imurmurhash": "^0.1.4"
  }
}
```

Example reproduction:
```console
# Start a container with the above `.yarnrc.yml` + `package.json`
$ docker run --rm -it -v "./:/is-a-volume" node:20-bookworm-slim bash

# Switch away from Yarn 1.x:
$ corepack enable
$ corepack prepare yarn@3.6.3 --activate


# Setup with boundary:
$ cd /is-a-volume
$ yarn install

# Notice that `.yarn/` and `node_modules/` are both large in size:
$ du -h
# Grab the inode of any file in `node_modules` and have `find` identify any files sharing it:
# - Verifies that `hardlinks-global` (which degraded to `hardlinks-local`) has no shared hardlink between the two dirs.
# - This is rather obvious already due to `du -h` which will detect duplicate size via hardlinks only counting unique size.
$ find . -inum "$(stat ./node_modules/imurmurhash/imurmurhash.js | sed -Ern 's/.*Inode: ([[:digit:]]+).*/\1/p')"
./node_modules/imurmurhash/imurmurhash.js

# Setup without a boundary:
$ mkdir /not-a-volume && cd /not-a-volume
$ cp /is-a-volume/{.yarnrc.yml,package.json} .
$ yarn install

# Verify `globalFolder` is used for `hardlinks-global`:
$ find / -inum "$(stat ./node_modules/imurmurhash/imurmurhash.js | sed -Ern 's/.*Inode: ([[:digit:]]+).*/\1/p')"
/root/.yarn/berry/store/v1/a4/09233f0435a13ad4905543dfae94e3f950916c.dat
/not-a-volume/node_modules/imurmurhash/imurmurhash.js
```

### Environment

```shell
System:
    OS: Linux 5.15 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (16) x64 AMD Ryzen 9 7940HS w/ Radeon 780M Graphics
  Binaries:
    Node: 20.6.1 - /tmp/xfs-7fc31d05/node
    Yarn: 3.6.3 - /tmp/xfs-7fc31d05/yarn
    npm: 9.8.1 - /usr/local/bin/npm
```
```


### Additional context

_No response_

**Comment by polarathene** [comment]
## Resolved (Misunderstanding)

I appear to have mixed up the `store/` with the `cache/` in `globalFolder` 😅 

Misunderstanding on my part, these two settings have nothing to do with each other.

---

> _If `hardlinks-global`, hardlinks to a global content-addressable store will be used._ - [Docs `nmMode`](https://yarnpkg.com/configuration/yarnrc#nmMode)

If setting `globalFolder: .global` + `enableGlobalCache: true`:
- 542M for `.global/` (_268M `cache/` + 275M `store/`_).
- 279M for `node_modules` (_hardlinked / shared with the global store (`.global/store/`)_).
- 555M total.

When `enableGlobalCache: false`:
- The `cacheFolder` (`.yarn/cache/`) is added and duplicates the weight of `.global/cache/` (_no links used_) increasing unique size by 268M (_total 823M_).
- `rm -rf node_modules` will reduce size to 811M, as the hard-links continue to work there.

> _If `pnpm`, a node-modules will be created using symlinks and hardlinks to a global content-addressable store._ - [Docs `nodeLinker`](https://yarnpkg.com/configuration/yarnrc#nodeLinker)

`nodeLinker: pnpm` has similar observations in size with:
- Duplicated `.{yarn,global}/cache/`, but `node_modules/.store/` does not seem to hardlink to `.global/store`, total 844M (`du -h`).
- `rm -rf node_modules` will reduce size to 536M, as the store only exists in `node_modules/.store/`, with symlinks from `node_modules` into that store (_the "global content-addressable store" no longer lives in `globalFolder`?_).
- Presumably `nmMode` has no effect on this linker?

---

**Takeaways:**
- `nodeLinker: pnp` is space efficient, while the other two won't utilize the cache content after an install, thus could discard it.
- `nmMode`:
  - `hardlinks-global` is only relevant to `nodeLinker: node-modules`? Unrelated to cache and not likely that relevant within containers. Since this store would only exist in `globalFolder` not `cacheFolder`, it's intentional and not a bug.
  - `classic` would be a better choice when reflink is supported / available. In this scenario with a container and a volume boundary, it'd likewise have no benefit without moving the `globalFolder` into it (_redundant in an image build / CI context?_).
- `nodeLinker`:
  - `pnp` uses the existing cache as equivalent to a store? (_which the other two derive cache into stores?_)
  - `pnpm` can be self-contained in `node_modules` (_"global" store as `.store/` subdir_).
  - `node-modules` performs a copy/clone. Alternatively hardlinks to a global store (_`store/` subdir at `globalFolder` location_).

**Comment by clemyan** [comment]
To fully understand this, I think it pays to understand a little bit of yarn's architecture. Although you are asking about 3.x I am going to refer to the v4 docs as these features do not change significantly in v4, and I will call out the differences as they come up.

Refer to the install architecture documented [here](https://yarnpkg.com/advanced/architecture#install-architecture).

----

During the **fetch step**, Yarn needs to obtain the resolved packages. Most commonly, "obtaining" means downloading them from the npm registry. This is where **caching** happens.

The fetched packages are stored in zip archives and saved at `{globalFolder}/cache` and/or `{cacheFolder}` as a cache, so that future fetches does not need to go though the network again. The caching behavior can be configured using the [`enableMirror`](https://yarnpkg.com/configuration/yarnrc#enableMirror) and the [`enableGlobalCache`](https://yarnpkg.com/configuration/yarnrc#enableGlobalCache) (which, I agree is a misnomer) configurations. Note that the default value for `enableGlobalCache` changed from `false` to `true` in v4. 

Note that "global" and "local", in this context, means "per-machine" and "per-project" respectively, which is moot for a docker environment where each "machine" only has one project.

----

During the **link step**. Yarn writes files onto disk in a way the node understands how to resolve. This is where different `nodeLinker` works differently.

- The `node-modules` linker creates a `node_modules` directory which node natively understands how to resolve. The structure of the `node_modules` directory mimics that created by `npm`.
- The `pnpm` linker also creates a `node_modules` directory, but its structure mimics the [symlinked `node_modules` structure](https://pnpm.io/symlinked-node-modules-structure) first developed by `pnpm`. This includes hardlinking all files to a global content-addressable store (CAS), which has the side effect of saving disk space across multiple projects.
- The `pnp` linker does not create a `node_modules` directory. Instead it implements the [Plug'n'Play](https://yarnpkg.com/features/pnp) strategy and monkey-patches the `require` function and `fs` methods to teach node how to resolve from somewhere other than `node_modules`. As a side effect, Yarn can use the same mechanism to also teach node how to directly run JavaScript files stored inside zip archives so Yarn can get away with not extracting the files from the zip archives in the cache.

When using the `node-modules` linker, it can also use hardlinks like the `pnpm` linker as a space-saving mechanism, enabled via the [`nmMode`](https://yarnpkg.com/configuration/yarnrc#nmMode) configuration. This configuration is specific to the `node-modules` linker.

- `classic` is the old behavior of just extracting the needed files into the local `node_modules` directory. No hardlinks.
- `hardlinks-local` also extracts files into the local `node_modules` directory but if the same package needs to be written multiple times, their files are hardlinked to each other.
- `hardlinks-global` extracts all needed files into a global CAS at `{globalFolder}/store`, then hardlinks them into the local `node_modules` directory. Just like the `pnpm` linker, it saves disk space across multiple projects.

----

In summary

- The caches and the global CAS are used during different phases of an install to serve different purposes
  - The global cache (`{globalFolder}/cache`) and the local cache (`{cacheFolder}`) are used by the fetcher for improved performance, network usage, and availability.
  - The global CAS is used by the `node-modules` linker for saving disk space
- The `pnp` linker indeed provide the mode space-efficient install, because only it can avoid extracting cached zip archives (possibly in the global cache and shared between projects) into local `node_modules` directories.
- In a docker deployment, it is best to avoid unnecessary duplication by using `enableGlobalCache: true` and either:
  - `nodeLinker: pnp`, or
  - `nodeLinker: node-modules` + `nmMode: hardlinks-local` to avoid writing extraneous hardlinks
