### ISSUE TITLE
[Bug?]: yarnpkg-sdks vscode needs to set `prettier.prettierPath` to '.yarn/sdks/prettier' not '.yarn/sdks/prettier/index.js'

### ISSUE THREAD

**Issue by SnowMarble** [yarnpkg/berry#5765]
### Self-service

- [X] I'd be willing to implement a fix

### Describe the bug

yarnpkg-sdk vscode sets `prettier.prettierPath` to '.yarn/sdks/prettier/index.js'.

But  `prettier.prettierPath` need to be a path of prettier module, not the path of index.js.

[document](https://github.com/prettier/prettier-vscode#prettierprettierpath) says:
> Supply a custom path to the prettier module. This path should be to the module folder, not the bin/script path. i.e. ./node_modules/prettier, not ./bin/prettier.

So, this should be '.yarn/sdks/prettier'

### To reproduce

You can check it by running `yarn dlx @yarnpkg/sdks vscode` and see `.vscode/settings.json`.

### Environment

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
  Binaries:
    Node: 20.6.1 - /tmp/xfs-60ada332/node
    Yarn: 3.6.3 - /tmp/xfs-60ada332/yarn
    npm: 9.5.1 - /mnt/c/Program Files/nodejs/npm
```

**Comment by arcanis** [comment]
Using `./node_modules/prettier` is, in this context, the same as `./node_modules/prettier/index.js`, due to the Node.js resolution algorithm turning the first into the second. The point that matters in the Prettier documentation is that it needs to point to the index of the library, not the bin script.

Unless there's a concrete bug caused by it?

**Comment by SnowMarble** [comment]
@arcanis Thanks for the reply. I reported this issue because I got an error when prettier.prettierPath is .yarn/sdks/prettier/index.js and fixed it via changing it to .yarn/sdks/prettier

The error occurred when I used plugins config in .prettierrc.js. This is my .prettierrc.js:
```js
module.exports = {
  semi: false,
  singleQuote: true,
  trailingComma: 'all',
  organizeImportsSkipDestructiveCodeActions: true,
  plugins: [require(require.resolve('prettier-plugin-organize-imports'))],
}
```

vscode prettier works fine without plugins config, but as soon as I add that plugins, it makes an error:
```text
["ERROR" - 12:24:39 PM] Invalid prettier configuration file detected.
{}
["ERROR" - 12:24:39 PM] Invalid prettier configuration file detected. See log for details.
```

and I found that changing prettier.prettierPath to 'yarn/sdks/prettier' fixes the issue.

This made me so confused that I also browsed the source code of prettier-vscode, but I haven't figured out what's the problem.

Do you think it's not for the problem of the vscode setting?

**Comment by clemyan** [comment]
I tried debugging with [`prettier-vscode`](https://github.com/prettier/prettier-vscode) current `main` and I found the opposite -- `.yarn/sdks/prettier/index.js` "works" but `.yarn/sdks/prettier` doesn't. Which version of the extension are you using? Do you have a clonable repro?

Also, since the prettier extension transfers the prettier config across a worker boundary through a `MessagePort`, your config does not work with the extension. The plugin is not structured-clonable.

**Comment by SnowMarble** [comment]
[@clemyan](https://github.com/clemyan) I'm using v10.1.0. And, since I found my issue in a private repo, please understand I can't share a repo right now.

My first attempt was to pass the package name as a string(`'prettier-plugin-organize-imports'`), but somehow prettier couldn't find the plugin. (probably prettier-vscode can't import from the file? I'm not sure about it.).

If you can share a repo that works with yarn berry, prettier, and vscode, it'd be very helpful for me to figure out my problem. Thanks for your advice! 😊

**Comment by clemyan** [comment]
Okay I can reproduce now. Unfortunately this is a bug/limitation on the extension itself.

As noted above, your config does not work with the extension since it cannot be transmitted across a worker boundary through a `MessagePort`. However, the extension determines whether prettier should run in a worker or in the main thread by detecting the version of prettier you are using:

https://github.com/prettier/prettier-vscode/blob/affc1e5/src/ModuleResolver.ts#L227-L236

This where the `prettier.prettierPath` config has an effect

- when using `.yarn/sdks/prettier`, the extension will **incorrectly use the version of the project as your prettier version**. It still correctly resolves your prettier instance so you are actually running prettier v3 but the extension thinks you are on v2 or lower
- when using `.yarn/sdks/prettier/index.js`, the extension correctly detects you are using prettier v3 and runs prettier in a worker, which fails for your config

You can test this by changing the version in your project root `package.json` to `3.0.0`, and `.yarn/sdks/prettier` and `.yarn/sdks/prettier/index.js` should both fail for you.

Thus, `.yarn/sdks/prettier/index.js` is the correct config to use. Your original issue is due to your config (specifically the plugin) being incompatible with running prettier in a worker.

**Comment by SnowMarble** [comment]
@clemyan I get it. I also found some comments about this from other issues. I appreciate your explanation. 🙇‍♂️

And I finally solved the problem. Changed `prettierPath` to the original value, and unplugged the prettier plugin.
I'm pretty sure prettier-vscode can't import modules from yarn pnp environment.
