### ISSUE TITLE
[Bug] yarn cache clean changed behaviour

### ISSUE THREAD

**Issue by ulrik-s** [yarnpkg/berry#588]
- [ ] I'd be willing to implement a fix

**Describe the bug**

Behaviour of "yarn cache clean" has changed. It used to remove all packages except for the
ones that had a dependency. This has changed into "rm -rf .yarn/cache" forcing us to do 
a "yarn install" in our build system. The only problem with that approach is that the link step
takes a long time:
```
2118 #13 200.8 ➤ YN0000: ┌ Link step
2119 #13 402.0 ➤ YN0000: └ Completed in 3.35m
```
Is there a way to persuade "yarn install" to not run the link step?

**To Reproduce**
run "yarn cache clean" and observe the removal of .yarn/cache folder

**Comment by arcanis** [comment]
> Behaviour of "yarn cache clean" has changed.

We've changed it because `yarn install` added autoclean support, so `yarn cache clean` became a bit redundant.

A 3mns link step is extremely weird - we shouldn't have to do much during this step, because in the best case we write a single file (the `.pnp.js`). Can you check how many directories are inside `.yarn/unplugged`?

And by any chance, can you share your `package.json` to see if I can reproduce this time on my side?

**Comment by ulrik-s** [comment]
The link step on my laptop is 12 seconds and the reason it is slow on the server is that the build is done inside a docker container. I also noticed that the removal step also takes a long time:
```
1969 #14 40.91 ➤ YN0019: │ zip-stream-npm-2.1.2-26384297be-1.zip appears to be unused - removing
1970 #14 40.91 ➤ YN0000: └ Completed in 38.97s
```

We have 27 unplugged packages:
```
16:25 $ find .yarn/unplugged -type d -maxdepth 1 | wc -l
      28
``` 

We are running a mono-repo with something like 30 sub-projects. Would you need the all of them or would the top one and a sub-project do?

**Comment by arcanis** [comment]
Interesting - something that could be helpful would be to run `yarn` through [`tracefs`](https://next.yarnpkg.com/package/?tracefs) to have a better idea about which FS calls are taking that much time.

> We have 27 unplugged packages

27 seems like a lot - do they all make sense (are they all native packages)? I wouldn't expect more than 10 🤔 Note that some packages (for example `core-js`, or `webpack-cli`) have postinstall scripts that trigger deoptimizations. In such cases they will be unplugged (because Yarn doesn't know that their postinstalls don't have side effects), and their build scripts must be [disabled manually](https://next.yarnpkg.com/configuration/manifest#dependenciesMeta.built).

> We are running a mono-repo with something like 30 sub-projects. Would you need the all of them or would the top one and a sub-project do?

I think the whole thing would be helpful (otherwise with a single subproject I'm afraid it'll be difficult to distinguish a perf issue and a fluke), although I guess it might be difficult if it comes from an internal project ... I think I could potentially sign an NDA, but I need to double-check with my employer to be safe.
