### ISSUE TITLE
[Bug?]: Can't find vite module using yarn pnpm mode

### ISSUE THREAD

**Issue by kogeletey** [yarnpkg/berry#5893]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

When using the latest yarn package manager,  and pnpm settings for modules resolutions  the following error appear
```
Error when evaluating SSR module /workspaces/workspace/astro.config.mjs: failed to import "@astrojs/vue"
|- Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'vite' imported from /workspaces/workspace/node_modules/.store/@vitejs-plugin-vue-virtual-57f61a4b96/node_modules/@vitejs/plugin-vue/dist/index.mjs
    at new NodeError (node:internal/errors:405:5)
    at packageResolve (node:internal/modules/esm/resolve:782:9)
    at moduleResolve (node:internal/modules/esm/resolve:831:20)
    at defaultResolve (node:internal/modules/esm/resolve:1036:11)
    at DefaultModuleLoader.resolve (node:internal/modules/esm/loader:251:12)
```
  
 I haven’t tested it with other modules except Vue. When using the `node-modules` setting, everything works fine.

### To reproduce

Repduction environment prepared on codesandbox:
[goofy-tree-yx5r5k - CodeSandbox](https://codesandbox.io/p/sandbox/goofy-tree-yx5r5k)

### Environment

```shell
System:
    OS: Linux 6.1 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (2) x64 AMD EPYC
  Binaries:
    Node: 20.5.1 - /tmp/xfs-d6a5509c/node
    Yarn: 3.6.4 - /tmp/xfs-d6a5509c/yarn
    npm: 9.8.0 - /usr/local/bin/npm
```

### Additional context

I already left issues in [astro](https://github.com/withastro/astro/issues/8882), but I was advised to write to you

**Comment by clemyan** [comment]
`@astro/vue` depends on `@vitejs/plugin-vue` which has a peer dependency on `vite`, but `@astro/vue` does not depend or peer-depend on `vite`. Thus, `@vitejs/plugin-vue` is unable to resolve `vite`.

`@astro/vue` should depend and/or peer-depend on `vite` and `@babel/core`. In the meantime you can unblock yourself with a [`packageExtension`](https://yarnpkg.com/configuration/yarnrc#packageExtensions).

**Comment by kogeletey** [comment]
I tried as you said and nothing worked...

**Comment by longhoang0304** [comment]
Hi @kogeletey,

I'm having the same problem. Have you figured out a way to fix it?

Thank you.

**Comment by levrik** [comment]
@clemyan But shouldn't it be enough if the package that depends on `@astro/vue` has `vite` as dependency? I have a similar issue right now with Vitest where it also seems that a transitive dep looks for `vite` but only 2 levels up in the chain it's present. PNPM seems to resolve this in a different way as I do not have this issue there but Yarn's PNPM linker has.

**Comment by clemyan** [comment]
@levrik 

No. In Yarn, if you depend on a peer requester (i.e. a package that has a peer dependency) and you want your parent package to satisfy that peer dependency instead of doing it yourself, you must explicitly declare it as a peer dependency yourself.

I'm no expert in how `pnpm` works, but as far as I understand, in `pnpm` a peer dependency can be satisfied by any ancestor of the requester. This effectively means if you depend on a peer requester, and you don't declare the requested package as a dependency or a peer dependency, you implicitly peer-depend on it, requesting your parent to provide the requested package.

However, this has some (probably unexpected) consequences. This means that you can suddenly peer-depend on a package simply by removing it as a dependency, and adding a peer-dependency is a breaking change. So removing a dependency from your package *may* be a breaking change. And to determine whether that *is* a breaking change, you must check your entire dependency tree to see if any peer requests from your dependencies (direct or transitive) bubbles up to your package.

The way Yarn manages peer dependencies means that if you remove a dependency that was satisfying a peer dependency, that is treated as an unsatisfied peer dependency instead of implicitly causing a breaking change. Whether a `package.json` diff is a breaking change can be determined by looking at just the diff, without referencing other files/context.
