### ISSUE TITLE
[Bug?]: sherlock link in bug report template is broken

### ISSUE THREAD

**Issue by zach-betz-hln** [yarnpkg/berry#6004]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

I was creating a bug report for [something else](https://github.com/yarnpkg/berry/issues/6005) and stumbled upon this. 
Not a big deal but just putting on your radar 🙂 

### To reproduce

1. Go to https://github.com/yarnpkg/berry/blob/839aabd1668f837c346504e62d1c71c1cbd89c22/.github/ISSUE_TEMPLATE/bug-report.yml?plain=1#L30
2. Go to link `https://yarnpkg.com/advanced/sherlock`
3. Get a 404

### Environment

```shell
System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 18.14.0 - /private/var/folders/yp/mzkjybsx3r9czv6jyg4cmw_m0000gn/T/xfs-d87a3aae/node
    Yarn: 4.0.2 - /private/var/folders/yp/mzkjybsx3r9czv6jyg4cmw_m0000gn/T/xfs-d87a3aae/yarn
    npm: 9.3.1 - ~/bin/node-v18.14.0-darwin-arm64/bin/npm
    pnpm: 8.6.3 - ~/bin/node-v18.14.0-darwin-arm64/bin/pnpm
    bun: 1.0.3 - ~/.bun/bin/bun
```

### Additional context

![Screenshot 2023-12-07 at 2 46 25 PM](https://github.com/yarnpkg/berry/assets/119352232/6792f2cf-4ab4-43ee-a208-0eb7c1701c99)

**Comment by geisterfurz007** [comment]
And even if one went to https://v3.yarnpkg.com/advanced/sherlock for a "working" (albeit technically outdated) link, the playground link there (https://yarnpkg.com/sandbox) only shows `Internal Server Error`.

**Comment by zach-betz-hln** [comment]
Closing.
There are bigger fish to fry for the maintainers.

**Comment by geisterfurz007** [comment]
That doesn't seem like a good reason to close the issue, does it? The issue is still relevant and it's still an issue. Creating a new issue explicitly requests a sandbox reproduction and the site you land on explicitly requests to let the owner of the site that was linked from know about the page not being found.

Just because there are other issues, doesn't mean this isn't one and it makes sense to keep this open, because otherwise this ends up as a closed dupe target and the issue is never getting resolved. It also removes this from the list of issues for the maintainers to work on which it shouldn't be because it's integral to the bug reporting workflow on GitHub.

**Comment by zach-betz-hln** [comment]
@geisterfurz007 fair points. 
I closed it because I created a minimal, reproducible example on my own for a separate issue.
I'll re-open it.

**Comment by zach-betz-hln** [comment]
Closed by https://github.com/yarnpkg/berry/pull/6306

Thanks @mitchhentgesspotify
