### ISSUE TITLE
[Bug]:  Yarn workspaces focus does not install peer dependencies for a package in a monorepo

### ISSUE THREAD

**Issue by kamleshFC** [yarnpkg/berry#6168]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Consider a below mono repo structure where the client package is consuming utils packages.
```
Root
   | - packages
          | - client
               package.json
          | - utils
               package.json
```
               
package.json inside client dir
```
{
  "name": "@org/client"
  "dependencies": {
    "@org/util": "workspace:*"
    "react": "^18.2"
  },
}
```

package.json inside utils dir
```
{
  "name": "@org/util"
  "peerDependencies": {
    "react": "^18.2"
  },
}
```

With Obove, If I run `yarn workspaces focus @org/util` and try to run test cases on that package it will fail as react is declared as peerDendencies and it is not installed

Not sure if this case is considered or my implementation is incorrect

### To reproduce

Create a project structure with 

```
Root
   | - packages
          | - client
               package.json
          | - utils
               package.json
```

### Environment

```shell
all
```

**Comment by arcanis** [comment]
The `react` package is only available when `@org/util` is accessed through `@org/client`. If you access it without the indirection (which can be the case when running your tests, for example) the workspace will have no parent in the dependency tree, and thus won't have access to `react`.

To address this, when declaring a peer dependency, consider also listing it as a dev dependency. Yarn will use the peer dependency when possible, and fallback to the dev dependency when the package is the top of the dependency tree.

**Comment by tmc-adept** [comment]
I am having a similar issue. I have dependencies shared across many packages and when I use `yarn workspaces focus --production` peer dependencies causes errors when accessed:

```
Error: Your application tried to access <peerDependency>, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.
```
The dependency is set in the project root package.json, so the resolutions should be computable. However, I am simply unable run dists when I install using `yarn workspaces focus --production`.

I am confused what purpose the `--production` flag serves if it does not install peer dependencies. The purpose I assumed was that I could omit dev dependencies and have my deployment size reduced.

**Comment by clemyan** [comment]
@tmc-adept

It is not just with `--production`. Even with a full-on `yarn install` of the whole project, workspaces shouldn't be able to resolve packages they specify only as `peerDependencies`. To allow such resolution, specify those packages as the workspace's dependency or devDependency as appropriate. Since 4.3.0, a warning is generated if a workspace's peer dependency is not also specified as either a dependency or devDependency.

If the peer dependency in question is also a dependency of the project root then I *think* workspaces would be able to resolve it with a full (i.e. unfocused) install. It is simply a case of the default settings not being strict enough to catch this mistake. Try setting [pnpFallbackMode](https://yarnpkg.com/configuration/yarnrc#pnpFallbackMode) to `none` to increase strictness in this regard.

**Comment by tmc-adept** [comment]
In my use-case, my project is part of a `monorepo` and package A depends on package B which depends on an external package C.

Packages A and B are in my project and are installed. Since B is installed, I know that C is also installed. In order to avoid version mismatch between dependencies of A and B, I have marked C as a `peerDependency` in package A.

If I add C as a full dependency in package A, I add more maintenance since I need A and B to use the same version.

Also, if I cannot install `peerDependency` in any other way than via `yarn install`, then what is the difference between `devDependency` and `peerDependency` in practice?

I can only install `peerDependency` when I also install `peerDependency`, so why include `peerDependency` at all?

**Comment by clemyan** [comment]
A `peerDependency` requests the *parent* to depend on something

If `A` depends on `B`, and `B` peer-depends on `C`, it represents the constraint "If `A` can resolve `C`, `B` resolving `C` will resolve to the same instance of `C`". One of the main use cases of this is for plugins/libraries for a larger system. For example, a react component library doesn't just need to be able to resolve `react`, it must access the **same instance of `react` that it is being used with**. So it needs a `peerDependency`, not a `dependency`

But that is problematic for workspaces, because a workspace is the root of a dependency tree -- it has no parent to provide the peer dependency. Imagine developing the said react component library itself. You'd probably also need `react`, but since the workspace has no parent there is no constraint on the package manager to provide `react` to it. For such cases, the workspace need to also declare it as a dependency or dev-dependency. In Yarn, this represents a peer-with-fallback -- Yarn prefers using peer-dependency semantics if the parent provides, but falls back to treating it as a regular dependency if not.

Note that workspaces can depend on each other, so a workspace *can* have other workspaces as parents. In this case, the dependency workspace does *not* act as the root of a dependency tree, but rather a node in another workspace's dependency tree, and peer dependency constraints are enforced. However, only `pnp` can correctly enforce such constraints, `node_modules` and `pnpm` cannot always correctly do so.

> Packages A and B are in my project and are installed. Since B is installed, I know that C is also installed. In order to avoid version mismatch between dependencies of A and B, I have marked C as a peerDependency in package A.

In this case, the peer dependency needs to be declared on B instead.

> I can only install peerDependency when I also install peerDependency, so why include peerDependency at all?

As a workspace the peer-dependency doesn't matter, because there is no parent. But when there are parents (e.g. after it is published and becomes another project's dependency), the semantics of having the peer-dependency or not are different.

**Comment by tmc-adept** [comment]
@clemyan 
> if A depends on B, and B peer-depends on C, it represents the constraint "If A can resolve C, B resolving C will resolve to the same instance of C". One of the main use cases of this is for plugins/libraries for a larger system. For example, a react component library doesn't just need to be able to resolve react, it must access the same instance of react that it is being used with. So it needs a peerDependency, not a dependency

This is my exact use-case, but not for `react`. Package A (not the root workspace) imports the framework. My other package B (also not root workspace) depends on A. It cannot function without A, and also depends on the framework.

If I put the frame work in the `dependency` property, then I will have to repeat that dependency in my root workspace, package A and package B. If I need to update the frame work version I will need to do it all three package.json files.

Therefore I would expect to be able to set the framework as a peerDependency on B. Since any installation of B must include A and A does not work without the framework. However, when I try to install this setup in a production-ready environment i.e. a docker container or some server, I get errors at run time because yarn does not install the frame work when installing package B.

I would expect `yarn workspaces focus --production` to install the frame work too. You mentioned using `nodeLinker` options other than `node-modules`, but I am locked into `node-modules` for now by another frame work used in the project.

Since I can replicate the expected behaviour with `npm`, I don't fully understand why `yarn` can't do it when using `nodeLinker: node-modules`.
