### ISSUE TITLE
[Bug] Not running simple yarn install

### ISSUE THREAD

**Issue by sibelius** [yarnpkg/berry#625]
- [ ] I'd be willing to implement a fix

**Describe the bug**

I've tried to run `yarn install` here (https://github.com/sibelius/yarn-workspaces-slow) and got the following error:

I did this 

```
yarn policies set-version v2
````

yarn install
```
Usage Error: The project in /app/package.json doesn't seem to have been installed - running an install there might help
```

the repo was like this:

/app/yarn-workspaces-slow

**To Reproduce**

The _minimal_ information needed to reproduce your issue (ideally a package.json with a single dep). Note that bugs without minimal reproductions might be closed.

IMPORTANT: We strongly prefer reproductions that use Sherlock. Please check our documentation for more information: https://next.yarnpkg.com/advanced/sherlock

run `yarn berry` here https://github.com/sibelius/yarn-workspaces-slow

**Screenshots**

**Environment if relevant (please complete the following information):**

 - OS: [e.g. OSX, Linux, Windows, ...] mac
 - Node version [e.g. 8.15.0, 10.15.1, ...] 12.13.0
 - Yarn version [e.g. 2.0.0-rc1, ...] 2.0.0-rc.19

**Additional context**

**Comment by arcanis** [comment]
Do you by any chance have a `yarn.lock` in `/app`? The error message doesn't reference the cloned project, which leads me to believe that Yarn thinks `/app` is the root of your app. This should only happen if you have a lockfile in an ancestor folder.

**Comment by willgriffiths** [comment]
FWIW, I could reproduce. I had unused yarn.lock files in two ancestor files. Deleting them fixed it for me.
```
~/yarn.lock
~/Projects/yarn.lock
```

**Comment by sibelius** [comment]
I can confirm that this is the case

but should this work? as it worked with `yarn`, but no work with `berry`?

**Comment by sibelius** [comment]
I've deleted all package.json and yarn.lock from other packages

but I got this error

```jsx
Usage Error: The project in /Users/sibelius/package.json doesn't seem to have been installed - running an install there might help
``` 

`/Users/sibelius/` is my home dir `~`

the problem now is that there are no package.json there to be excluded

**Comment by willgriffiths** [comment]
> the problem now is that there are no package.json there to be excluded

Sorry if I'm making you repeat yourself but did you also remove a yarn.lock from the home dir? `/Users/sibelius/yarn.lock`

Yarn 2 supports nested workspaces which may relate to the change in behaviour. arcanis would know more.

**Comment by sibelius** [comment]
got working here

there are a `yarn.lock` there on home dir as well

**Comment by willgriffiths** [comment]
Thanks for creating an issue @sibelius. I added a feature request based on your feedback. 

Let us know if you hit any other blockers with yarn 2. :)

**Comment by adamhp** [comment]
@willgriffiths Just a heads up, I had a `package.json` randomly in my User directory that was also causing me the same issue in `~/dev/projectdir`.

**Comment by avimehenwal** [comment]
> @willgriffiths Just a heads up, I had a `package.json` randomly in my User directory that was also causing me the same issue in `~/dev/projectdir`.

I can confirm, I has the same issue and remove `yarn.lock` and `package.json` file from root directory solved the issue for me on fedora linux. yarn version `3.1.1`

**Comment by matthias-ccri** [comment]
Can we reopen this in order to improve the error or the behavior of yarn?

Maybe the error message could be clearer. Something like:
```
Usage Error: A yarn.lock file was found in a higher directory ({path}), but it doesn't seem to have been installed. Either run an install there, or delete the file.
```

Or perhaps yarn should not regard stray `yarn.lock` files in ancestor directories. Is this a valid use case with yarn? Should yarn stop at the first package.json it finds when searching upward in the directory tree?

In my case, I ran yarn from a directory with a `package.json`, but my home directory had a `yarn.lock` but no `package.json`. I'm not familiar with yarn 2, and I admit I didn't fully read the file path in the error message. I was running a storybook setup command (`npx sb@next repro`) as you can see in the above linked issue. So this caused confusion for me.

**Comment by Ryukyo** [comment]
I encountered this error also with yarn3 and found some yarn.lock files and package.json files outside of the projectdir, but removing them didn't resolve the issue

**Comment by soujvnunes** [comment]
> > @willgriffiths Just a heads up, I had a `package.json` randomly in my User directory that was also causing me the same issue in `~/dev/projectdir`.
> 
> I can confirm, I had the same issue and removing `yarn.lock` and `package.json` files from root directory solved the issue for me on fedora linux. yarn version `3.1.1`

This worked for me as well. Just wondering why would these files need to be removed and why are they there in the first place.

**Comment by leemacpherson** [comment]
When i ran `yarn install`, I too got the message "Usage Error: The project in /Users/l<username>/package.json doesn't seem to have been installed - running an install there might help.  I moved from version 1.22.x to 3.1.1 about the same date as the date i saw on the yarn.lock file.  I had never tried to rebuild my project from the package.json file before so this was the first time it had to go look for yarn.lock and package.json and it found those two there.  Deleting these files allowed it to install my dependencies in my project folder when i ran 'yarn install'

**Comment by andresogando** [comment]
Hi Solved this issue: 
1. Delete your yarn.lock and package.json files outside the working directory.
2. If you're using private dependencies use the migration guide: https://yarnpkg.com/getting-started/migration#update-your-configuration-to-the-new-settings  specifically the section of .npmrc .yarncr files where it guides you thru the process of migration in order to yarn fetch the private repos. 
3. yarn install 
4. yarn run 
Enjoy !

**Comment by frank-unovica** [comment]
Nested workspaces is an undesired and undocumented feature. How do I disable this (globally)?

The issue remains (version berry and stable) - package.json and yarn.lock are there legitimately, and properly freshly installed (monorepo dev libraries such as prettier). But one directory down (the actual project) it keeps complaining. node_modules and yarn.lock have been removed several times at all locations (there are more nested further down the monorepo).

**Comment by mschnee** [comment]
I have a file named `package.json` file in a distant parent directory that is completely unrelated to the project I am currently working on.  It is frustrating beyond relief that I have to rename it just so that yarn thinks `$(pwd)/package.json` is the root of a workspace; and I cannot find any means to tell it explicitly so.

`eslint` has a `root: true` option, which tells it not to scan up the directory tree any further.  Does `yarn` have a similar `.yarnrc.yml` option?

**Comment by LukePammant** [comment]
FWIW the quickest fix if you can't find the offending yarn.lock file is to simply `touch yarn.lock` from the folder you're trying to run your other yarn commands from.

**Comment by rofrol** [comment]
After `yarn set version latest` the error was more detailed. I needed to remove `~/package.json`.

**Comment by movy** [comment]
Ugdating yarn from 3.2 to the latest version fixed this for me.

**Comment by OmarSherif96** [comment]
> FWIW the quickest fix if you can't find the offending yarn.lock file is to simply `touch yarn.lock` from the folder you're trying to run your other yarn commands from.

Worked for me!

**Comment by Joelasaur** [comment]
This issue is still happening for me, but from inside a dockerfile build. It seems to be related to [this solution](https://github.com/yarnpkg/berry/issues/5380 ) of "delete the parent folder's yarn.lock file", but the docker container does not have a parent directory with these extra files, since I'm running in either root or a workdir specified like `/app`.

**Comment by clemyan** [comment]
@Joelasaur 

`COPY . .` is probably overwriting/undoing what `yarn install` did, in particular `.yarn/install-state.gz`
