### ISSUE TITLE
[Bug?]: yarnpkg.com Discord link broken

### ISSUE THREAD

**Issue by dylanh724** [yarnpkg/berry#6273]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

See https://www.yarnpkg.com -> click Discord link -> Broken

### To reproduce

See above

### Environment

```shell
n/a
```

**Comment by clemyan** [comment]
Does it point to https://discord.gg/yarnpkg?

**Comment by trivikr** [comment]
The Discord link from yarn website is working for me.

**Comment by stephenh** [comment]
I'm still seeing a broken link:

![Image](https://github.com/user-attachments/assets/9fc99688-bb1e-451e-8028-89600f90d1b0)

**Comment by stephenh** [comment]
Hi @clemyan apologies for the really late reply, but yeah I'm clicking the Discord link on the home page:

![Image](https://github.com/user-attachments/assets/6de8a572-6240-47f2-b8a8-957e12b17061)

Which yeah links to:

https://discord.gg/yarnpkg

But when I click on that, it me redirects to

https://discord.com/invite/yarnpkg

And then I see the "invite invalid" screenshot.

Fwiw I think by default Discord invites expire, but you can't really notice/tell as an already-invited user, because when you click through `discord.gg/yarnpkg`, you'll go straight there.

Iirc I had the same issue on a discord invite link, and had to re-create it with a "never expires" option enabled.
