### ISSUE TITLE
[Bug] Yarn PnP does not work inside folder with path containing a space

### ISSUE THREAD

**Issue by hlegendre** [yarnpkg/berry#632]
- [ ] I'd be willing to implement a fix

**Describe the bug**

Yarn PnP does not work when inside a folder whose path contains spaces.

**To Reproduce**

Simply move a working project to a folder which path contains a space and try to run it.
A repo as been setup with a minimal case here : https://github.com/hlegendre/yarn_pnp_bug_with_space

I tried to move the cache to a folder (config set cache-folder or cacheFolder depending on version) without space to no avail.

**Environment if relevant (please complete the following information):**

 - OS: macOS 10.14.6
 - Node version 12.13.0
 - Yarn version 1.21.1 or 2.0.0-rc.19

**Additional context**

Same issue is being opened on yarnpkg/yarn as [7764](https://github.com/yarnpkg/yarn/issues/7764)

**Comment by arcanis** [comment]
This is because Node (until 12.0) doesn't support paths with spaces in `NODE_OPTIONS` (I implemented it here: https://github.com/nodejs/node/commit/3ef1512f9e416cc7656b9cd16934dffdee1b11d3). On top of this we don't use this capability at all at the moment.

We should version-check `process.version` and escape the path if needed and supported.

**Comment by arcanis** [comment]
This is where the `NODE_OPTIONS` environment variable is populated - wanna try to make the fix? We have a [contributing guide](https://next.yarnpkg.com/advanced/contributing) to help get started 🙂

https://github.com/yarnpkg/berry/blob/master/packages/plugin-pnp/sources/index.ts#L14-L21

**Comment by hlegendre** [comment]
I could try to have a look ! 😅 

Could we simply quote the `${npath.fromPortablePath(pnpPath)}` in the variable `pnpRequire` in case it contains a space. This would be on this line : https://github.com/yarnpkg/berry/blob/master/packages/plugin-pnp/sources/index.ts#L12

For node 12+, it would solve the problem. And for node < 12, it would still break but probably not more than today...

Or if it's possible to check the node_version (env.NODE_VERSION ?) from yarn, we could do it only for node 12+

PS: as you can see, I am not very knowledgeable on this stuff but willing to contribute...

**Comment by arcanis** [comment]
> PS: as you can see, I am not very knowledgeable on this stuff but willing to contribute...

Don't worry, we all start this way! Let me know if you have blockers (and you can ask help through our [Discord server](https://discord.gg/yarnpkg) too).

I think your approach (always use escaping if there are spaces) should work. I was thinking to check `process.version` which contains the Node version, but I forgot that since it doesn't work at all currently, it won't be any worse anyway, as you said 🙂

For escaping you can just use `JSON.stringify`, I think that should work for most use cases.

**Comment by arcanis** [comment]
Fixed by #644
