### ISSUE TITLE
[Bug] Fetch step of yarn install with pnp is really slow

### ISSUE THREAD

**Issue by safarmer** [yarnpkg/berry#673]
- [ ] I'd be willing to implement a fix

**Describe the bug**

I have gone through the process of switching to use PNP for a React app. When I ran `yarn install` it recommended I try out v2 of Yarn. When I ran `yarn install` with v2, all of my deps were not in the cache so they were downloaded. The result of this step was:

```
➤ YN0000: ┌ Fetch step
Many lines of:
➤ YN0013: │ type@npm:2.0.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed in 11.9m
```

**To Reproduce**

With a `package.json` with a large number of dependencies:
```
yarn --pnp
yarn policies set-version berry 
yarn install
```

**Environment if relevant (please complete the following information):**

 - OS: Linux
 - Node version v13.5.0
 - Yarn version 2.0.0-rc1

**Comment by arcanis** [comment]
We have a fix in master that should help; can you try running `yarn cache clear --all && yarn set version from sources && yarn`?

Note that cold installs will still be slower than the v1 due to us having to transform the fetched packages from tgz into zip (and even though we're doing it through wasm, it still has a cost). Hopefully registries will eventually catch up and offer to download packages as zip out of the box 🙂

(Note that we need zip because otherwise we would need to uncompress the whole archive when accessing a single file at runtime, which would be very wasteful for most Node projectsv)

**Comment by SEAPUNK** [comment]
Had the same issue; installing latest from master makes the fetch step much faster (1m vs 5m+)

Thanks for the fix!

**Comment by safarmer** [comment]
I can confirm that the time to fetch my dependencies has come down to 2.1m from 11.9m. Thanks!

**Comment by arcanis** [comment]
Awesome! I'll close this issue then 🎉
