### ISSUE TITLE
[Bug] link:`ed directory does not resolve any packages

### ISSUE THREAD

**Issue by andreialecu** [yarnpkg/berry#730]
- [ ] I'd be willing to implement a fix

**Describe the bug**

In a workspace package that has the following package.json:

```json
{
  "name": "test",
  "dependencies": {
    "@types/lodash": "^4.14.149",
    "buggy": "link:./source/buggy",
    "lodash": "^4.17.15",
    "rxjs": "^6.5.4",
    "typescript": "next"
  }
}
```

Any file in the `./source/buggy` directory will not be able to resolve and import any package dependencies.

**To Reproduce**

Repro at https://github.com/andreialecu/yarn2-link-bug

Run `yarn workspace test tsc`

**Screenshots**

![image](https://user-images.githubusercontent.com/697707/72924913-79522900-3d5a-11ea-88c7-e2f67c9bf8f6.png)

**Environment if relevant (please complete the following information):**

 - yarn -v: 2.0.0-rc.24

**Comment by arcanis** [comment]
I think it's because the `link:` protocol causes the PnP loader to think that `shared` is a package that doesn't list any dependencies (and I didn't see it because the fallback prevented me to see it on my main app where I use `link:`).

We need a way to tell the PnP loader that a path should be excluded for consideration in `findPackageLocator`, while still being a valid locator for the bookkeeping that occurs in `getPackageInformation` 🤔
