### ISSUE TITLE
Considerations for yarn-related packages

### ISSUE THREAD

**Issue by zackkrida** [yarnpkg/berry#748]
Hi all, I currently use a tool called [Volta](https://github.com/volta-cli/) to manage global JavaScript tooling. I just posted an [issue](https://github.com/volta-cli/volta/issues/651) there regarding Yarn 2 support and it brought up a few questions about how the official Yarn 2 launch will work:

1. Will the `yarnpkg/berry` repo be moved into the main `yarkpkg/yarn` repo? Because 1x and 2x are currently spread across multiple repos npm is the only canonical source of all of the 1x and 2x versions in one list: https://registry.npmjs.org/yarn

2. The previous docs site had a url to return the latest version of yarn. It currently redirects to the legacy docs: https://yarnpkg.com/latest-version. Will this be maintained on the new site, and should it even be used as a retrieval method of the latest version?

Super excited about the 2.0 release, and thanks for reading!

**Comment by arcanis** [comment]
> Will the yarnpkg/berry repo be moved into the main yarkpkg/yarn repo?

No, I think it's important to keep the history of the project. If we were to move `yarnpkg/berry` into `yarnpkg/yarn`, many links would end up broken (unless we purely "take over" the Yarn 1 repo, but I don't want to use the Yarn 1 issue tracker which is in a very sad state).

> The previous docs site had a url to return the latest version of yarn. It currently redirects to the legacy docs: https://yarnpkg.com/latest-version. Will this be maintained on the new site, and should it even be used as a retrieval method of the latest version?

I think it will, yes. Right now we wanted to preserve the behaviour pretty much as it was before the Yarn 2 release so that workflows that expect a 1.x release have time to update their workflows if they need to. In a few weeks we'll start switching the tags and `latest-version` & friends will be part of it.

**Comment by arcanis** [comment]
Also note that the `yarn.js` file for any Yarn 2 version can be retrieved by accessing the following url (and replacing `master` with the tag for `@yarnpkg/cli`). I think it's safe to assume it will stay that way in the future:

https://github.com/yarnpkg/berry/blob/master/packages/yarnpkg-cli/bin/yarn.js

**Comment by zackkrida** [comment]
Cool, thank you!
