### ISSUE TITLE
[Bug] Error with pm2

### ISSUE THREAD

**Issue by VladStepanov** [yarnpkg/berry#795]
**Describe the bug**

I try to start pm2 process via yarn/berry, but it throws an error

**To Reproduce**

```javascript
{
  "name": "node-test-api",
  "scripts": {
    "start": "pm2 start index.js"
  },
  "dependencies": {
    "express": "^4.17.1",
    "pm2": "^4.2.3"
  }
}
```
Just try to run script

**Screenshots**

![image](https://user-images.githubusercontent.com/49880862/73172603-0a832000-410c-11ea-8902-c2e67fc1b944.png)

**Environment if relevant (please complete the following information):**

 - OS: Windows 10
 - Node version v12.10.0
 - Yarn version 2.0.0-rc.27

**Additional context**

If i try to run the same command but with global pm2 installed via npm/yarn 1.x.x, it works

**Comment by arcanis** [comment]
As mentioned in the error message pm2 doesn't list the `debug` package in their dependencies:

https://cdn.jsdelivr.net/npm/@pm2/agent@0.5.26/package.json

Do you mind opening a PR to add it? Once it's done we can open a separate one against our plugin-compat so that everyone benefits from the fix:

https://github.com/yarnpkg/berry/blob/master/packages/plugin-compat/sources/extensions.ts
