### ISSUE TITLE
[Feature] Rethink `yarn link`

### ISSUE THREAD

**Issue by arcanis** [yarnpkg/berry#90]
**Describe the user story**

The `yarn link [...]` workflow is weird.

**Describe the solution you'd like**

I think `yarn link [package-name]` should be replaced by `yarn link <path-to-package>`. This would allow us to stop having to store data within the global folder when using `yarn link`, which is a bit wasteful and arguably dangerous (the registered folder for a given name might have disappeared).

We also should add the `[--all]` option which, when set, links *all* the named non-private workspaces from the target project to the current one. This would make it very easy to work on external monorepo projects like `jest`.

**Describe the drawbacks of your solution**

Changing the behavior of an existing command is a bit extreme, but in this case we have the required tools to ensure a smooth upgrade path (we can print error messages that explain what changed and how to achieve the exact same result under the new workflow).

**Describe alternatives you've considered**

We could keep the existing workflow (first `yarn link` in each linkable folder, then `yarn link <package-name>` in each linked folder), but it's really bad from a devx perspective (twice the number of commands for no reason).

**Comment by arcanis** [comment]
Fixed via #98

**Comment by kilpatty** [comment]
Is this the only way to use `yarn link`/ local linking in v2? This is adding a resolution to my package.json, which is not a problem in itself, but I tend to have different paths to local libraries than my coworkers. 

So while this still allows me to link projects locally, I can't commit and push my `package.json` because the path is hardcoded for my local disk, and it will break any resolutions from my coworkers. Again, not a problem per se, but just feels slightly more cumbersome than the previous behavior. While I save on an extra yarn command, I lose on an extra git patch when I make changes the `package.json`, but have to prevent committing the resolution. 

Is there a way to not have a hardcoded resolution path, or at least save it somewhere other than the `package.json`? 

Apologies if I'm missing something here that would allow the resolution to work for everyone, if they have different file pathing to different projects (without being forced into a monorepo).

**Comment by arcanis** [comment]
It's the only way in the v2, correct. Yarn is trying to enforce consistency in JS projects and having a single source of truth is critical to provide it, as you otherwise don't know for sure why an install is made a certain way - maybe something hidden affects it.

That being said you might be able to achieve the effect that you want with a simple trick:

**package.json**
```json
{
  "resolutions": {
    "foo": "portal:./foo"
  }
}
```

**.gitignore**
```
/foo
```

Then create a symlink to the location of your package:

```
$> ln -s ~/path/to/foo foo
$> yarn
```

Since the symlink won't be part of the repository, you and your colleagues will be free to make them point to whatever you need.

**Comment by kilpatty** [comment]
Amazing, thank you! 

Will try that out now

**Comment by Venryx** [comment]
@arcanis Thank you for the workaround; however, there are use-cases it does not cover.

My use-case:
* I have a "library-comparison" repo, and a "library" repo.
* I frequently make changes to the "library" repo, and want to test those changes in the "library-comparison" repo as swiftly as possible. (ie. avoiding npm-publish, file copying, etc.)
* I thus use `yarn link ...`. The path to the "library" repo can differ per developer, so I'd be using your workaround above.
* Problem: For developers that are merely cloning my "library-comparison" repo to run the comparison, they inherit the `portal:./foo` entry in package.json. This is bad; it means they can no longer just run `yarn` to install all the dependencies.

This problem does not exist for NPM, because npm's `link` command does not modify the `package.json` file. Granted, `npm link` has [its own issues](https://github.com/npm/cli/issues/2372). Even so, it would be nice to have a way to `yarn link ...` another package, without modifying the git-included `package.json` file.

A _generic_ solution to this problem would be some way of "overriding" fields within the `package.json` file, from some `package_userOverrides.json` file that is ignored by Git. I would be content with this, in lieu of a solution written specifically for the `yarn link` command.

Does anyone know a way to accomplish this idea of "user-specific package.json overrides"? (perhaps using Yarn hooks?)

**Comment by Venryx** [comment]
I tried the `portal:./foo` approach (too lazy to make a plugin just yet), but even it seems to not work on Windows at the moment. I'm on the latest version of Yarn/Berry. (Berry 3.0.0-rc.2)

Specifically, I do the following:
1) Create a `Portals` folder, and inside it, create a junction using: (I also tried `/d`, to create a symlink instead)
```
cmd /c mklink /j .\Portals\web-vcore C:\PATH_TO_MODULE
```
2) Tell Yarn to create a portal to the personalized/user-specific junction file/entry, by adding to `package.json`:
```
"resolutions": {
    "web-vcore": "portal:./Portals/web-vcore"
}
```
3) Run `yarn install`.

I then get this error:
```
Error: While persisting /C:/PATH_TO_PROJECT/Portals/web-vcore/ -> /C:/PATH_TO_PROJECT/node_modules/web-vcore EPERM: operation not permitted, symlink '..\Portals\web-vcore' -> 'C:\PATH_TO_PROJECT\node_modules\web-vcore'
```

The error is the same whether I use symlinks or junctions for the (manually created) `.\Portals\web-vcore` -> `C:\PATH_TO_MODULE` linkage.

**Comment by Venryx** [comment]
Okay, it looks like the EPERM issue is relating to permissions: when I run `yarn install` from an administrator terminal, no permission error occurs.

However, even then, the symlink is not created properly: for some reason the `node_modules/web-vcore` folder/symlink just does not exist after `yarn install` has completed.

I know this bug report is not very actionable for Yarn developers without a minimal repro repo, but I thought I'd mention it for others hitting the same issue, to save them some time (ie. thinking they're doing something wrong when it may just be an issue with yarn on Windows).

Anyway, I've given up for now and am just using relative paths (for some reason this approach works):
```
"resolutions": {
    "web-vcore": "link:../../@Modules/web-vcore/Main"
}
```
(It just uses relative paths to point to the directory on disk where I develop the module.)

**Comment by arcanis** [comment]
> However, even then, the symlink is not created properly: for some reason the `node_modules/web-vcore` folder/symlink just does not persist after `yarn install` has completed. (I'm assuming it was created, since the non-admin terminal errors on the command to create it, but some later step must delete it, thinking it's unused or something.)

In case you manage to repro it, feel free to open an issue, I'm sure @larixer would be interested. Portals w/ node-modules are [tested](https://github.com/yarnpkg/berry/blob/master/packages/acceptance-tests/pkg-tests-specs/sources/node-modules.test.ts#L170-L205) however, so it sounds strange 🤔

**Comment by Venryx** [comment]
Good news. I managed to create a yarn plugin that supports "user-specific yarn-links"!

Plugin source (and basic instructions) here: https://github.com/Venryx/yarn-vtools#feature-conditional-versionprotocol-overrides-for-dependencies

A short config file for the plugin, showing how to achieve conditional yarn-links using it:
```
// in YVTConfig.cjs file, in project root
exports.config = {
	dependencyOverrideGroups: [
		process.env.MYPROJECT_USER == "bob" && {
			overrides_forSelf: {
				"depA": `link:../../bob's/path/to/depA`
			}
		},
		process.env.MYPROJECT_USER == "alice" && {
			overrides_forSelf: {
				"depA": `link:/alice's/path/to/depA`
			}
		}
	]
};
```

I've confirmed that it works, and will henceforth be using it whenever I need to use yarn-links/symlinks. Finally I can have the best of both worlds between npm and yarn links!

(Npm ones are nice for letting you customize it per user, and yarn ones are nice in that they actually persist through subsequent `install` commands, and do not mess up the `node_modules` folders of linked dependencies ever; but neither of them supported both, until now.)

**Comment by slikts** [comment]
@Venryx So basically you still hardcode the user-specific paths?

The workflow of not having to run `yarn link` twice is better, but how do you link to v3 projects from v1 projects?

**Comment by Venryx** [comment]
> @Venryx So basically you still hardcode the user-specific paths?

That's how I'm currently using it, yes. But since the `YVTConfig.js` file is just a regular NodeJS script, it could be written to read from an environment variable or access an out-of-repo file to find the user's symlink list. And you could write a short helper script that populates this storage in the same way that `npm link` works.

> The workflow of not having to run yarn link twice is better, but how do you link to v3 projects from v1 projects?

I don't understand what the question/context.

**Comment by scheinercc** [comment]
Similar problem as @remie - I [posted it a few days ago also on SO](https://stackoverflow.com/q/69877428/472804). While I am glad about the solution @Venryx came up with, this seems a lot more work now than running `yarn link` twice. I am also still wondering, if there is something I should be doing differently.

**Comment by jcupps** [comment]
I agree that the old two-step process, while cumbersome, was preferable to the new behavior since it didn't result in modifications to files that are tracked in source control.

> A generic solution to this sort of problem would be some way of "overriding" fields within the package.json file, from some file that is ignored by Git (eg. package_userOverrides.json). I would be content with this, in lieu of a solution written specifically for the yarn link command.

This sounds like a good compromise, with `yarn link` automatically writing to this file. Alternatively, maybe yarn could support a new config setting in .yarnrc.yml as well as a .yarnrc.yml.local file that would override .yarnrc.yml and could be excluded from source control?

**Comment by donmccurdy** [comment]
> > The workflow of not having to run yarn link twice is better, but how do you link to v3 projects from v1 projects?
> 
> I don't understand the question/context.

I think I have the same question. I'm trying to make a PR to an open source Project A that uses/requires Yarn 3. My own Project B uses Yarn 1. I need to link B into A. But from Project B directory, now `yarn link` only allows me to link external projects _into_ B, not to prepare B for linking into A.

**Comment by KevinGhadyani-Okta** [comment]
I ran into the same issue where I have a Yarn v3 library, but the consumer is Yarn v1.

I appreciate the change that was made; it's really good, but a legacy linking might be good for these situations (which are common at work right now as we upgrade).

Best best is building, then copy-pasting into that repo's `node_modules/`.

**Comment by georeith** [comment]
+1 also run into this linking between Yarn v3 and Yarn v1 projects. A global flag would be good to allow us to opt-in to the old behaviour as there's a large amount of Yarn 1 projects still out there and there seems to be no interoperability for linking packages from projects using newer versions of yarn to them.

**Comment by larixer** [comment]
@KevinGhadyani-Okta @georeith I think there is misunderstanding happening in this issue. There is no obstacles with linking Yarn 1 and Yarn 3 projects that both use `node_modules` linking strategy. If you use Yarn 1 and want to link Yarn 3 library, you can use `YARN_IGNORE_PATH=1 yarn link` in Yarn 3 library, to execute Yarn 1's link command and then `yarn link <dependency_name>` in the Yarn 1 project. If you want to link Yarn 1 library into Yarn 3 project, you can use `yarn link ../path-to-the-library` inside Yarn 3 project.

**Comment by georeith** [comment]
great thanks @larixer that's exactly what I needed, would be good to document that on https://yarnpkg.com/cli/link as I think the confusion stems from a lack of documentation (that I could easily find) on that flag.

**Comment by WhiteMinds** [comment]
I hope the problem of the package.json being modified is solved, which is causing problems for the library developers and Monorepo.

Now Unlink and link are performed at each git commit 🙉.

**Comment by thorsent** [comment]
I do hope that the maintainers consider implementing the ability to save and load portals from a file that can be gitignored. This would be far less fragile than the current approach (convenient as it is).

In the meantime, we've added the following husky pre-commit check (typescript):

```typescript
import process from "process";
import fs from "fs";

const main = () => {
	const packageJson = JSON.parse(fs.readFileSync("./package.json").toString());
	if (Object.values(packageJson.resolutions ?? {}).find((entry: any) => entry.includes("portal:/"))) {
		console.log("package.json contains portals. Run `yarn unlink` before committing.");
		process.exit(1);
	}
	process.exit(0);
};

main();
```

**Comment by ilyaGurevich** [comment]
Sort of a related question here, is it possible to link a package in a pnpm monorepo to a yarn berry monorepo locally?

**Comment by oleksandr-danylchenko** [comment]
> There is no obstacles with linking Yarn 1 and Yarn 3 projects that both use `node_modules` linking strategy. If you use Yarn 1 and want to link Yarn 3 library, you can use `YARN_IGNORE_PATH=1 yarn link` in Yarn 3 library, to execute Yarn 1's link command and then `yarn link <dependency_name>` in the Yarn 1 project.

Unfortunately, it doesn't seem to work for my one-package repository. Running the `YARN_IGNORE_PATH=1 yarn link` has the same effect as running just the `yarn link`. I don't see that the package gets registered and I cannot link it to my Yarn 1 project.
| `YARN_IGNORE_PATH=1 yarn link` | `yarn link package-name` |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/08d3f1a4-0619-4899-95bd-cddf4b0aa5fe) | ![image](https://github.com/user-attachments/assets/db055e10-905d-4a2b-abd4-e414011fdb3d) |
