### ISSUE TITLE
[Bug] Cannot publish to a custom repository

### ISSUE THREAD

**Issue by kapooostin** [yarnpkg/berry#930]
- [ ] I'd be willing to implement a fix

**Describe the bug**

Yarn fails to publish package to a custom repository.
I use a public repository on gemfury.com. It works fine with `yarn@1.22`.

After I switched to `yarn@berry` I can still install packages from there, but an attempt to publish returns an undocumented error code and fails.
```console
$ yarn npm publish
➤ YN0000: README.md
➤ YN0000: package.json
➤ YN0035: [object Object]
➤ YN0000: Failed with errors in 0.8s
```

`yarn npm login` lets me to login to a correct repository.
```console
$ yarn npm login
➤ YN0000: Logging in to https://npm-proxy.fury.io/<myrepo>

? Username: <username>
? Password: [hidden]

➤ YN0000: Successfully logged in
```

`yarn npm whoami` returns an error:
```console
$ yarn npm whoami
➤ YN0041: HTTPError: Response code 404 (Not Found)
➤ YN0000: Failed with errors in 0.82s
```

`yarn npm info` is missing at all.
```console
$ yarn npm info
Unknown Syntax Error: Command not found; did you mean one of:

  0. yarn npm login [-s,--scope #0] [--publish]
  1. yarn npm publish [--access #0] [--tag #0] [--tolerate-republish]
  2. yarn npm whoami [-s,--scope #0] [--publish]

While running npm info
```

**To Reproduce**

My `yarnrc.yml`:
```yml
npmPublishAccess: public

npmRegistries:
  //npm-proxy.fury.io/<myrepo>:
    npmAlwaysAuth: true
    npmAuthToken: <token>

npmRegistryServer: "https://npm-proxy.fury.io/<myrepo>"

yarnPath: .yarn/releases/yarn-rc.js
```

**Environment if relevant (please complete the following information):**

 - OS: OSX
 - Node version 10.15.3
 - Yarn version 2.0.0-rc28

**Comment by arcanis** [comment]
Note that generally speaking we expect people having problems with third-party registries to investigate themselves, as otherwise we need a great deal of setup (and that doesn't scale).

Some tips:

- `yarn npm info` hasn't been released yet, it's in master (you can use `yarn set version from sources` to download it and use it).

- if `yarn npm whoami` doesn't work it means that your registry doesn't implement the endpoint; nothing we can really do here (I'd suggest to open an issue on their tracker?).

- the `➤ YN0035: [object Object]` is quite weird - the only place where it can be emitted is [here](https://github.com/yarnpkg/berry/blob/b296d7bd3cf9f5fb16d629188b929c309f070926/packages/plugin-npm-cli/sources/commands/npm/publish.ts#L119), but I'd expect it to be a string. Can you add some console.log statement here to figure out what's the true error message?

**Comment by kapooostin** [comment]
> the ➤ YN0035: [object Object] is quite weird - the only place where it can be emitted is here, but I'd expect it to be a string. Can you add some console.log statement here to figure out what's the true error message?

```js
console.log( error.response.body.error ); // { type: 'Forbidden', message: 'Account access denied' }
```

So, I see, the problem is on the side of the service. But what has changed in this command's logic so that yarn@1's `publish` works without any hiccups and this version fails?

**Comment by arcanis** [comment]
> But what has changed in this command's logic so that yarn@1's publish works without any hiccups and this version fails?

Yeah, that's the kind of thing that's super annoying to debug, since those protocols are usually completely undocumented and have to be reverse-engineered on a case-by-case basis ... 😅

Some guesses, probably wrong:

- Maybe they expect us to send an `email` address - we don't do this anymore, since it's useless on most registries and a relicate of the time the npm registry used MongoDB

- Maybe they expect the username / password to be sent unencrypted ? The `login` command now stores the token obtained during the login attempt, and we never send back the auth logins.

**Comment by deini** [comment]
@kapooostin I can't reproduce this, I tried it with the `.yarnrc.yml` you provided and one with scoped registries.

![image](https://user-images.githubusercontent.com/2752665/74186472-51930a00-4c10-11ea-998b-bbd7fecaa93a.png)

By any chance do you have `npmScopes` defined in your project's `.yarnrc.yml` or your global one?

**Comment by kapooostin** [comment]
@deini Thank you for taking a trouble to test it. 
I tried it with `npmScopes` in `.yarnrc.yml`, didn't help either:
```yml
npmScopes:
  dmail:
    npmPublishRegistry: "https://npm-proxy.fury.io/<myrepo>"
    npmRegistryServer: "https://npm-proxy.fury.io/<myrepo>"
```

I tried to login with `--scope`, still no luck. Login was successful, publishing was not.

If it works on your end, Daniel, then there's something wrong with my system. BTW, does `yarn@2` has global config now since `yarn global` was removed?

**Comment by deini** [comment]
> does yarn@2 have global config now since yarn global was removed?

You can have a `~/.yarnrc.yml`

**Comment by kapooostin** [comment]
@deini It helped me to login, finally.

My token in `project/.yarnrc.yml` was invalid and it overrode one stored in `~/.yarnrc.yml`. So the only issue left here is a display of an error.

The errors from Gemfury are sent as objects
```js
{
  type: String,
  message: String
}
```
Is it specific to them only? `yarn@1` displays the errors from Gemfury as text, not `[object Object]`.

**Comment by kapooostin** [comment]
`npm` also shows `[object Object]` on login errors, so it must be Gemfury's fault.
