### ISSUE TITLE
Does link protocol support wildcards?

### ISSUE THREAD

**Issue by traverse** [yarnpkg/berry#945]
I looked for similar questions/issues but couldn't find any so here goes. I was trying out `yarn@berry` yesterday to get a better insight into the migration path and as far as I could tell the following isn't supported currently.
```typescript
// tsconfig.json
{
  "compilerOptions": {
    "baseUrl": ".", 
    "paths": {
      "*": [
        "src/*"
      ]
    }
  }
}

// example of the imports it would allow for
import {} from 'api/models' // path is actually 'workspace/src/api/models/index.ts'
```
So if we would like to migrate we would either have to prefix all the imports e.g. `@app/api/models` or add a lot of linked packages in the `package.json`.

Are there any plans to support wildcard linking like this? Or is the preferred solution in this case using a prefix?

**Comment by arcanis** [comment]
> Are there any plans to support wildcard linking like this? Or is the preferred solution in this case using a prefix?

Yep, you should use a shared prefix. Otherwise the dependency tree becomes dynamic (new "packages" get added each time you add a new folder), and that's not something we want to support.

Additionally, a common prefix helps to avoid accidental module clashes (for example I worked in a codebase where a top-level module was named "util", thus conflicting with the builtin module from Node).

**Comment by SirensOfTitan** [comment]
@arcanis: question here re:shared prefix, let me know if I should put this elsewhere.

So if I define the prefix in package.json's dependencies:
```
"@app": "link:./src"
```

Shouldn't I be able to use imports like: `import Foo from "@app/foo/bar";`?  I get module errors using this method above.

**Comment by arcanis** [comment]
`@app` isn't a valid package name - it's just a scope. You'd want `app`, or `@app/src`.
