### ISSUE TITLE
[Bug] Yarn 2 does not run prepare script for git dependencies

### ISSUE THREAD

**Issue by trusktr** [yarnpkg/berry#957]
This issue is basically the same as described at https://github.com/yarnpkg/yarn/issues/7910, but for Yarn 2.

**Comment by arcanis** [comment]
This is expected, cf:
https://yarnpkg.com/advanced/lifecycle-scripts

Tldr: use `prepack` rather than `prepare`.

**Comment by trusktr** [comment]
@arcanis Ah, interesting. So Lerna team explicitly does not want to be compatible with the same scripts?

I hadn't known about `prepack` running on git installs (maybe a newer npm feature after prepare was used for git installs?), but it does seem like the better option.

**Comment by trusktr** [comment]
(updated my last comment, accidentally wrote "Lerna" instead of "Yarn")

**Comment by arcanis** [comment]
> Does Yarn have plans to be compatible with the same scripts as npm?

From the page I linked:

> Note that we don't support every single lifecycle script originally present in npm. This is a deliberate decision based on the observation that too many lifecycle scripts make it difficult to know which one to use in which circumstances, leading to confusion and mistakes. We are open to add the missing ones on a case-by-case basis if compelling use cases are provided.

As for

> I hadn't known about prepack running on git installs (maybe a newer npm feature after prepare was used for git installs?), but it does seem like the better option.

No, `prepack` is an fairly old script. The difference between it and `prepare` was very subtle (`prepare` runs on installs too), hence why people really didn't know which one to use.

**Comment by cinderblock** [comment]
Why doesn't `prepack` run on "git install"? _"git install" as in adding a git repository as a `package.json` dependency._

One major feature, imho, of how Npm runs `prepare` scripts is being able to directly install a git repository as a `package.json` dependency. Since a git repository should not contain compiled sources, a "build" step is often necessary to generate usable sources. Having that "build" step run as a `prepare` script means it's trivial to add a git "package" as a dependency and it will work just like it had been installed via npmjs.com.

If instead the `prepack` hook is used, it will correctly build before packing, but won't build after installing from git.

What is the intended way for Yarn to support adding/installing from (git) sources and automatically building after?

**Comment by arcanis** [comment]
> Why doesn't `prepack` run on "git install"? _"git install" as in adding a git repository as a `package.json` dependency._

It does.

**Comment by cinderblock** [comment]
My mistake. I was accidentally testing with Yarn 1.

However, my point remains, how is a package maintainer expected to make their git package work for both Yarn and Npm?

Lifecycle scripts run on "git install".
| Yarn 2.4.2 | Npm v7.15.1 | Match |
| --- | --- | --- |
| `postinstall` | `postinstall` | ✔️ |
| **`prepack`** |  | ❌ |
|  | **`prepare`** | ❌ |
|  | `prepublish` | ❌ |

A `postinstall` script is the only one they both run. So that? Or the same script in `prepack` and `prepare`? Doesn't that make Npm potentially double up on scripts?

**Comment by GNUGradyn** [comment]
even prepack doesnt seem to work in yarn 3 lol
