### ISSUE TITLE
[Regression] node_modules linker throws with ENOENT

### ISSUE THREAD

**Issue by nicolo-ribaudo** [yarnpkg/berry#988]
- [ ] I'd be willing to implement a fix

**Describe the bug**

I recently upgraded the Yarn 2 version in the Babel branch I'm using to upgrade from 2.0.0-rc.29 to https://github.com/yarnpkg/berry/pull/987, which is based on the current `master`.

With rc.29 one of our builds was passing (https://app.circleci.com/jobs/github/babel/babel/17258), but now it's failing while linking (cc @larixer): https://app.circleci.com/jobs/github/babel/babel/17270.
It throws
```
Error: ENOENT: no such file or directory, open '/home/travis/build/babel/babel/codemods/babel-plugin-codemod-object-assign-to-object-spread/node_modules/@babel/plugin-codemod-object-assign-to-object-spread/package.json
```

It's also failing in Travis (Node 12: https://travis-ci.com/babel/babel/jobs/290193686, Node 10: https://travis-ci.com/babel/babel/jobs/290193688), but it's working in another Circle CI job (https://app.circleci.com/jobs/github/babel/babel/17265) and with GitHub Actions (https://github.com/babel/babel/pull/11142/checks?check_run_id=463357994)

Please note that `@babel/plugin-codemod-object-assign-to-object-spread` doesn't depend on itself, so I don't understand why yarn expects to find that `package.json` file.

**To Reproduce**

I'm sorry about this, but I can't reproduce it locally. If needed, I can give you access to the failing CircleCI build using ssh.

**Screenshots**

**Environment if relevant (please complete the following information):**

 - OS: Linux
 - Node version 10, 12, 13
 - Yarn version `master`

**Additional context**

https://github.com/babel/babel/pull/11142/commits/1af74d9ca5cc9763a42d4387e1ae28e74c0749e6

**Comment by larixer** [comment]
@nicolo-ribaudo Thanks, I can guess what's happening and craft a fix for you to try. Because it is a speculation, this will be hit or miss. 

Symlink on itself for a top package is a normal thing for Yarn 2, this way we ensure that any package can resolve itself, its an extra guarantee and a feature of Yarn 2. This feature is kept for `node_modules` as well by default. If there will be blockers with it, we will add option to turn it off. But the current issue is not a blocker I think.

Node_modules linker adds modules to `node_modules` in two phases. During `addModule` phase the first copy of modules are added to the disk. During `cloneModule` phase the duplicates of the modules on disk are written as hardlinks, this is kind of optimization. 

For `addModule` phase we create `symlinks`:
https://github.com/yarnpkg/berry/blob/master/packages/plugin-node-modules/sources/NodeModulesLinker.ts#L429-L432
but during `cloneModule` phase we don't and this is a mistake that I believe is the reason for this issue. 

Another problem is that we do not sort `locations`:
https://github.com/yarnpkg/berry/blob/master/packages/yarnpkg-pnpify/sources/buildNodeModulesTree.ts#L89

The `locations[0]` is used for `addModule` and `locations[1...n]` are used for `cloneModules`. Because we do not sort locations the issue like this might be hard to reproduce, we should sort them to make behaviour deterministic.

**Comment by nicolo-ribaudo** [comment]
I'm investigating.
So far I found that the call which throws is https://github.com/yarnpkg/berry/blob/b39d39f914889cb56a39e69f16be72b5dcf8835a/packages/plugin-node-modules/sources/NodeModulesLinker.ts#L114

**Comment by nicolo-ribaudo** [comment]
The problem was that I was caching the top-level `node_modules` folder (and thus `node_modules/.yarn-state.yml`) but not the nested `node_modules`.

I'm closing this issue since it was caused by me, but I think that there should be a way to cache the top-level `node_modules` to save some work.
Without caching it, "Link step" takes more than 10 mins on Travis CI (on CircleCI and GitHub Actions it is faster) and is thus killed by Travis.

**Comment by larixer** [comment]
@nicolo-ribaudo No worries, thank you! `node_modules` is kinda already cached, but integrity of the cache must be preserved (all `node_modules` should be cached and restored, otherwise things will break). Another feature that can be done in this direction is to have unpacked offline mirror (currently it is compressed) and then copying might be done via copy-on-write hardlinks - this is the way yarn 1 operated, it will speed up `Link step` too, but it has downsides as well - more space on the disk for offline mirror, harder to check integrity of offline mirror, etc...

**Comment by larixer** [comment]
It is also possible to implement quick `node_modules` integrity checking via storing and comparing `mtimes` on `node_modules` directories, this way users will be able to restore part of `node_modules` dirs and yarn will use them and restore the forgotten part. Probably this behaviour should not be default and should be enabled via some flag...

**Comment by larixer** [comment]
@nicolo-ribaudo I think `mtime` idea won't work, because CI will change `mtimes` when restoring `node_modules` from the cache. However much simpler idea will work - we can actually check if all `node_modules` root dirs exist (which can be very quick, because there should not be too many such dirs in the project) and reinstall those that do not, it is very simple to implement. I have given it a shot here:
#993
