### ISSUE TITLE
[Bug] Can't switch back to Yarn v1 after trying out Yarn v2

### ISSUE THREAD

**Issue by callumlocke** [yarnpkg/berry#999]
- [ ] I'd be willing to implement a fix

**Describe the bug**

I wanted to try out Yarn v2, so I did `yarn set version 2`. This worked. But now I can't switch back to v1:

```
> yarn set version 1
^[➤ YN0000: Selecting the highest release amongst 1.22.0 and 18 others
➤ YN0000: Downloading https://github.com/yarnpkg/yarn/releases/download/v1.22.0/yarn-1.22.0.js
➤ YN0000: Saving the new release in .yarn/releases/yarn-1.22.0.js
➤ YN0000: Done in 2.35s

> yarn -v
2.0.0-rc.29
```

**To Reproduce**

1. Start with a regular Yarn 1 installation on macOS, installed via `brew`.
2. Run `yarn set version 2`
  - Running `yarn -v` now prints `2.0.0-rc.29`.
3. Run `yarn set version 1`
  - The output makes it look like this worked, but it didn't – `yarn -v` still prints `2.0.0-rc.29`.

**Environment if relevant (please complete the following information):**

 - OS: macOS
 - Node version: v12.13.0
 - Yarn version: 2.0.0-rc.29

**Additional context**

Sorry if I'm missing something obvious - I don't know much about Berry/Yarn 2, I just wanted to try it out, and now I can't get back to Yarn 1.

**Comment by Mike-Dax** [comment]
I'm not at my computer at the moment, but I'm pretty sure you'll find a `.yarn` directory in your home directory, if you delete that you should be able to install v1 again.

**Comment by o-alquimista** [comment]
I've reverted to Yarn 1 by deleting the `.yarn` directory at the root of the project, plus any other files added in the process. I checked out any changes made to the git repository, and then `yarn --version` from the project folder would again return `v1.22`.

Remember that Yarn 2 installs locally, confined to your project.

**Comment by BrandiATMuhkuh** [comment]
i'm having the same issue. it's even globally changed to `yarn -v`. I'm using win10 if that helps.
Even uninstalling yarn and installing it again does not help.

**Comment by BrandiATMuhkuh** [comment]
I "fixed" it my going into my users root directory and executing `yarn set version ^1`. Not it's globally back to v1

**Comment by NotMoni** [comment]
You can do Cmd + Shift + > to see hidden files. (dot files.)

**Comment by arcanis** [comment]
I'm not sure there's anything actionable on our side at the moment, so I'm going to close this issue.

**Comment by lfender6445** [comment]
i had a default in my root, deleting it did the trick

```sh
cat ~/.yarnrc.yml 

yarnPath: ".yarn/releases/yarn-berry.cjs"

rm -f ~/.yarnrc.yml
```

**Comment by romulocollopy** [comment]
A detail is that `.yarnrc.yml` can live in any ancestor folder.
It seems like it's generated where the command is run. So, if your project is in `~/Projects/MyApp`, it can be in `~/.Projects`

**Comment by f4z3k4s** [comment]
If you enabled yarn via `corepack enable` from above node v16.14.0, just run `corepack disable`, then install it the old way like `npm i -g yarn@1.22.1`.

**Comment by danactive** [comment]
`yarn set version classic` is the latest command for using v1

**Comment by landsman** [comment]
Omg this is mess!  Why there is no support for definition of the version in project with highest priority? It's a standard thing in other languages that I have globaly set some configuration but project override it.

I just get the project where was used yarn v1 and I spent 2 hours to figure out this got damn Yarn issue. 

Very bad developer UX! I really don't know why is Yarn so popular if this things are not resolved until now.

**Comment by nahumzs** [comment]
on unix
```sh
$ cd ~/
$ yarn set version classic
```

worked for me

**Comment by pencilcheck** [comment]
> yarn set version ^1

doesn't work for me, I need to remove `.yarnrc.yml` then running `yarn` works right away.

**Comment by douglasg14b** [comment]
`yarn set version ^1` results in: _Usage Error: No matching release found for range ^1._

**Comment by EwertonDutra** [comment]
> i had a default in my root, deleting it did the trick
> 
> ```shell
> cat ~/.yarnrc.yml 
> > yarnPath: ".yarn/releases/yarn-berry.cjs"
> 
> rm -f ~/.yarnrc.yml
> 
> npm install -g 'yarn@1.22.1'
> 
> yarn -v
> > 1.22.10
> ```

If not work
Just put the --force parameter in install

**Comment by graemechristie** [comment]
I'm still seeing this on yarnv3. Eventually deleted the .yarn folder (and every other .yarn* file I could find on my system) and yarn set version classic finally reverted to v1 for my project. Surely .. regardless of the state of my other environments, if I run yarn set version classic in a project folder, yarn should revert to version 1 for that project. This is either a bug or should be a change in the desired behaviour of yarn. Either way I'm not sure it should have been closed.

**Comment by arcanis** [comment]
There isn't a bug _per se_ - `yarn set version` updates the `.yarnrc.yml` file located in the current project, that's the intended behaviour. The problem is that you have a `yarnPath` even above, but that isn't supposed to happen - our docs never mention to run `yarn set version` at the root or anywhere else than your project. It's technically a user bug that you ended up in that situation (although it's a UX bug that you _can_ get into this situation).

That said, **I know it's a common problem**, and **we'll likely try to address that somehow in a future release** - perhaps by forbidding to run Yarn in the home directory, to avoid accidental commands. But it comes with side effects (I imagine some Docker setup are fine with running Yarn from the home directory), so it hasn't been a priority so far.

Additionally, with the 4.0 we're making Corepack the preferred way to install Yarn, so `yarnPath` should be even less common.

**Comment by xJkit** [comment]
> on mac
> 
> ```shell
> $ cd ~/
> $ yarn set version classic
> ```
> 
> worked for me

Much appreciated!!!! This solution is wonderful.

**Comment by sezanzeb** [comment]
> I'm not sure there's anything actionable on our side at the moment, so I'm going to close this issue.

I'm in a directory with a package.json file that says `engines.yarn` is `"^1.0.0"`. There is a .yarnrc that says `yarnPath: .yarn/releases/yarn-1.22.1.cjs`. And I make an additional call to `yarn set version 1.22.1`. And yarn still uses `4.13.0`.

For me as someone who does not know how yarn really works, isn't writing javascript anymore (precisely because of issues like this) and just wants things to work, hoping that maintaining old projects from former colleagues doesn't end up causing so much trouble:

This absolutely looks like a bug to me, and it's hard to use and understand. Can't you just respect the settings of the project I'm in? Why do local configurations not take precedence over global ones?

Also:
- yarn 1.22.22 refuses to set the version to berry, even if the package.json requires berry, because it won't do anything (even installing berry) if the current version doesn't match the package.json file
- yarn berry on the other hand ignores the value in package.json and local configuration and runs stuff with the wrong version

**Comment by clemyan** [comment]
@sezanzeb How did you install Yarn?

With both of the officially supported ways to install Yarn Modern, `yarn set version 1.22.1` should have worked. If it didn't then I think there is indeed a bug. Are you able reproduce that in a clean environment?

> `engines.yarn`

I don't think any version of Yarn actually checks that field? I could be wrong though since I don't know lot about how Yarn v1 worked
